<form id="permissoes" name="permissoes" enctype="application/x-www-form-urlencoded" action="add" class="form" method="post">

	<div class="inline">
		<label>Perfil</label>
		<select name="id_perfil" id="id_perfil" class="text req" title="Perfis cadastrados" onchange="ativaDivVend('vendedor', this.value); ativaDivFunc('funcionario', this.value)">
		    <option value="0">SELECIONE</option>			
			<?php
				
				foreach($this->perfis as $perfis){
					
					echo "<option value=\"" . $perfis['id'] . "\" label = \"" . $perfis['perfil'] ."\">  ". $perfis['perfil'] ." </option>";
					
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline" style="height:auto;clear:both;width:99%;height:auto">
		<label class="label">Perfis</label>
		
		<?php
		
			foreach($this->colunasPermissoes as $k => $v){
				
				if($k != "id" && $k != "id_perfil"){
					
					$arrNome = explode("_", $k);
					
					$nome = implode(" ",$arrNome);
					
					$nome = ucwords($nome);
					
					echo "<div style=\"width:33%; float:left\"><input type=\"checkbox\" id=\"$k\" name=\"$k\" value=\"1\"/>$nome</div>";
				
				}
			
			}
		
		?>

	</div>
	
	<div class="inline" style="clear:both">
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Cadastrar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){
	
	var msg = "";
	var erro = false;
	
	if($("#id_perfil").val() == "0"){
		
		erro = true;
		
		msg += "<br>O campo perfil deve ser selecionado.";
	
	}
	
	if($("#id_perfi").val() != 0 && $("#id_empresa").val() == 0){
		
		erro = true;
		
		msg += "<br>Este perfil nescessita de uma concessionaria.";
	
	}
	
	if($("#id_perfil").val() != <?php echo FUNCIONARIO; ?>){
		
		//alert($("#id_perfil").val());
		
		if($("#login").val() == ''){
		
			erro = true;
			
			msg += "<br>O campo login deve ser preenchido.";
		
		}

		if($("#senha").val() == ''){

			erro = true;
		
			msg += "<br>O campo senha deve ser preenchido.";
		
		}
		
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})

function ativaDivVend(destino, c){
	
	if(c == <?php echo VENDEDOR; ?> || c == <?php echo GERENTE; ?>){
		
		$("#"+destino).css('display','inline');
	
	}else{
	
		$("#"+destino).css('display','none');
	
	}

}

function ativaDivFunc(destino, c){
	
	if(c == <?php echo FUNCIONARIO; ?>){
		
		$("#"+destino).css('display','inline');
		$("#divLogin").css('display','none');
		$("#divSenha").css('display','none');
	
	}else{
	
		$("#"+destino).css('display','none');
		$("#divLogin").css('display','inline');
		$("#divSenha").css('display','inline');
		
	}
	
}

</script>
