<form id="permissoes" name="permissoes" enctype="application/x-www-form-urlencoded" action="<?php echo URL ?>permissoes/edt/id/<?php echo $this->id; ?>" class="form" method="post">

	<div class="inline">
		<label>Perfil</label>
		<select disabled name="id_perfil" id="id_perfil" class="text req" title="Perfis cadastrados">
		    <option value="0">SELECIONE</option>			
			<?php

				foreach($this->perfis as $perfis){
					
					if($this->permissao['id_perfil'] == $perfis['id']){
					
						echo "<option selected=\"selected\" value=\"" . $perfis['id'] . "\" label = \"" . $perfis['perfil'] ."\">  ". $perfis['perfil'] ." </option>";
					
					}else{
					
						echo "<option value=\"" . $perfis['id'] . "\" label = \"" . $perfis['perfil'] ."\">  ". $perfis['perfil'] ." </option>";
					
					}
					
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline" style="height:auto;clear:both;width:99%;height:auto">
		<label class="label">Perfis</label>
		
		<?php
		
			foreach($this->permissao as $k => $v){
				
				if($k != "id" && $k != "id_perfil"){
					
					$arrNome = explode("_", $k);
					
					$nome = implode(" ",$arrNome);
					
					$nome = ucwords($nome);
					
					if($v == 1){
					
						echo "<div style=\"width:33%; float:left\"><input type=\"checkbox\" checked=\"checked\" id=\"$k\" name=\"$k\" value=\"1\"/>$nome</div>";
					
					}else{
					
						echo "<div style=\"width:33%; float:left\"><input type=\"checkbox\" id=\"$k\" name=\"$k\" value=\"1\"/>$nome</div>";
					
					}
					
				}
			
			}
		
		?>

	</div>
	
	<div class="inline" style="clear:both">
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Salvar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){
	
	var msg = "";
	var erro = false;

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})

</script>
