<table class = 'table'>

<thead><tr><th>Descri&ccedil;&atilde;o</th><th>Cr&eacute;dito / D&eacute;bito</th><th>&Uacute;ltima Atualiza&ccedil;&atilde;o</th><th>Ações</th></tr></thead>

<tbody>

<?php
		
	//var_export($this->gruposFinanceiros);
	//exit;
		
	foreach($this->gruposFinanceiros as $e){
	
		$dataTmp = explode(" ",$e['hora_alteracao']);
		$dataTmp2 = explode("-",$dataTmp[0]);
		$e['hora_alteracao'] = implode("/",array_reverse($dataTmp2));
		$e['hora_alteracao'] = $e['hora_alteracao'] . " " . $dataTmp[1];
	
?>		
		<tr>
		<td><?php echo $e['descricao']; ?></td>
		<td><?php if($e['credito_debito'] == 0){
		
			echo "Crédito";
		
		}else echo "Débito"?></td>
		<td><?php echo $e['ultimoUsuario'] ?> - <?php echo $e['hora_alteracao'] ?></td>
		<td><input type="button" class="btn-small btn-edt" value="Editar" onclick="javascript:window.location.href='edt/id/<?php echo $e['id']?>'" /> <input type="button" class="btn-small btn-del" value="Delete" onclick="confirmaDelete('Grupo: <?php echo $e['descricao']?>', <?php echo $e['id']?>)" /></td> </tr>
<?php	
	}
?>

</tbody>
</table>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

	function confirmaDelete(msg, id){
	
		if(confirm("Deseja realmente excluir a "+msg+" ?")){
		
			window.location.href = "del/id/" + id;
		
		}
	
	}

</script>
