<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="add" class="form" method="post">
	
	<div class="inline">
		<label class="label">Marca</label>
		<select class="text req" id="marca" name="marca">
			<option value="">Selecione</option>
		<?php
			foreach($this->marcas as $marca){
		?>
		
			<option value="<?php echo $marca['marca'];?>"><?php echo $marca['marca'];?></option>
		
		<?php
			}
		?>
		</select>
	</div>
	
	<div class="inline">
		<label class="label">Modelo</label>
		<input type="text" id="modelo" name="modelo" class="text req" value="" />
	</div>
	
	<div class="inline">
		<label class="label">Ano</label>
		<input type="text" id="ano_modelo" name="ano_modelo" class="text req" value="" />
	</div>
	
	<div class="inline">
		<label class="label">Pre&ccedil;o</label>
		<input type="text" id="preco" name="preco" class="text req" value="" />
	</div>

	<div class="inline" style="clear:both;">
		<input type="hidden" id="id_empresa" name="id_empresa" value="<?php echo $_SESSION['sessionUser']['id_empresa'];?>" />
		<input type="hidden" id="codigo" name="codigo" value="000000" />
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Cadastrar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#marca").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo marca deve ser preenchido.";
	
	}
	
	if($("#modelo").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo modelo deve ser preenchido.";
	
	}
	
	if($("#ano_modelo").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo ano deve ser preenchido.";
	
	}
	
	if($("#preco").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo preço deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})
</script>
