<?php

?>

<form id="imagens" name="upload" enctype="multipart/form-data"  action="criticas" class="form" method="post">
	
	<div class="inline">
		<label class="label">Nome</label>
		<input type="text" id="nome" name="nome" readonly="readonly" class="text" value="<?php echo $_SESSION['sessionUser']['nome'] ?>" />
	</div>
	
	<div class="inline">
		<label class="label">Email</label>
		<input type="text" id="email" name="email" readonly="readonly" class="text" value="<?php echo $_SESSION['sessionUser']['email'] ?>" />
	</div>
	
	<div class="inline" style="clear:both; width:63%; height:auto;">
		<label class="label">Mensagem</label>
		<textarea class="text" style="height:200px;" name="mensagem" id="mensagem"></textarea>
	</div>
	
	<div class="inline" style="clear:both;">
		<label class="label">Anexo</label>	
		<input type="file" id="file" name="file" class="text"/>
	</div>

	<div class="inline" style="margin-top:10px;clear:both;">
		<input type="submit" class="btn-small btn-add" value="Enviar" />
	</div>
 
 </form>
 
 <div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#id_projeto").val() == 0){
		
		erro = true;
		
		msg += "<br>Selecione o perfil.";
	
	}
	
	if($("#titulo").val() == 0){
		
		erro = true;
		
		msg += "<br>O campo titulo deve ser preenchido.";
	
	}
	
	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})

//manageTabs("tab_projetos_sis","menu_projetos");

</script>
