<?php
if(!$_GET['erro']){
?>

<style type="text/css">
	.disabled { cursor: not-allowed; }
</style>

<div>
	<form method="post" action="/index/logar-v2" id="login_v2">
				    <div class="form-group">
					  	<div class="form-floating mb-3">
					    	<input type="email" class="form-control" id="user"  name="user" placeholder="Usuário">
					   	 	<label for="user">Usuário</label>
					  	</div>
					</div>
				    <div class="form-group has-danger">
						<div class="form-floating">
						    <input type="password" class="form-control" id="senha" name="senha" placeholder="Senha">
						    <label for="senha">Senha</label>
						</div>
					</div>
					<div class="invalid-feedback msg">Usuário e Senha devem ser informados.</div>
					<br>
					<?php if ($this->recaptchaEnabled): ?>
					<center>
						<div class="g-recaptcha" data-callback="enableBtn" data-expired-callback="recaptchaExpired" data-sitekey="<?php echo $this->escape($this->recaptchaSitekey); ?>"></div>
					</center>
					<br>
					<div class="d-grid gap-2 disabled">
					  	<button class="btn btn-lg btn-primary" disabled="disabled" type="button" id="entrarButton">Entrar</button>
					</div>
					<?php else: ?>
					<div class="d-grid gap-2">
					  	<button class="btn btn-lg btn-primary" type="button" id="entrarButton">Entrar</button>
					</div>
					<?php endif; ?>
				</form>
					<br>
					<div class="d-grid gap-2">
					  	<a type="button" href="/index/esqueci-senha" class="btn btn-link">Esqueci a senha</a>
					</div>
		</div>
</div>

<script type="text/javascript">
	
	function enableBtn(){
		$("#entrarButton").removeAttr("disabled");
		$("#disabled").removeClass("disabled");
	}

	function recaptchaExpired(){
		$("#entrarButton").attr("disabled", true);
		$("#disabled").addClass("disabled");
	}

	$("#entrarButton").click(function(){

		$("#user").removeClass("is-invalid");
		$("#senha").removeClass("is-invalid");
		$(".msg").css("display","none");

		let erro = false;

		if($("#user").val() == ""){
			erro = true;
			$("#user").addClass("is-invalid");
		}else{
			$("#user").addClass("is-valid");
		}
		
		if($("#senha").val() == ""){
			erro = true;
			$("#senha").addClass("is-invalid");
		}else{
			$("#senha").addClass("is-valid");
		}

		if(erro){
			$(".msg").css("display","block");
		}else{
			$("#entrarButton").attr("disabled", true);
			$("#entrarButton").html("Aguarde...");
			$("#login_v2").submit();
		}
	
	});


</script>

<?php
}else{
	echo '<div class="alert alert-dismissible alert-danger">
			<strong>Erro!</strong><br>
			Usuário ou senha incorreto. Por favor, tente novamente aqui <a href="/index/login-v2">aqui</a>, caso o erro persista, tente redefinir a senha clicando <a href="/index/esqueci-senha">aqui</a>, ou entre em contato com o administrador do sistema.
			</div>';
}
?>
