<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="add" class="form" method="post">
	
	<div class="inline">
		<label class="label">Descri&ccedil;&atilde;o</label>
		<input type="text" id="descricao" name="descricao" class="text req" value="" />
	</div>
	
	<div class="inline">
		<label class="label">Credito / Debito</label>
			<input type="radio" id="credito_debito" name="credito_debito" value="0">Credito
			<input type="radio" id="credito_debito" name="credito_debito" value="1">Debito
	</div>
	
	<div style="display:table;clear:both; margin-left: 10px">
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Cadastrar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#descricao").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo descricao deve ser preenchido.";
	
	}
	
	if($("#credito_debito").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo credito / débito deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}
	
	$(function(){
	
		if($("#msg").html().length > 0){
				
			if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
			
				$("#msg").addClass('sucess');
			
			}else{
			
				$("#msg").addClass('erro');
			
			}
		
		}

	})

}

</script>
