<div class="inline" style="margin-left:5px; margin-bottom:5px">
	<input type="button" class="btn-mini btn-include" value="Adicionar" onclick="javascript:window.location.href='<?php echo URL ?>grupos-financeiros/add'" />
</div>
<table class = 'table'>

<thead><tr><th>Descri&ccedil;&atilde;o</th><th>Cr&eacute;dito / D&eacute;bito</th><th>&Uacute;ltima Atualiza&ccedil;&atilde;o</th><th>Ações</th></tr></thead>

<tbody>

<?php
		
	//var_export($this->gruposFinanceiros);
	//exit;
		
	foreach($this->gruposFinanceiros as $e){
	
		$dataTmp = explode(" ",$e['hora_alteracao']);
		$dataTmp2 = explode("-",$dataTmp[0]);
		$e['hora_alteracao'] = implode("/",array_reverse($dataTmp2));
		$e['hora_alteracao'] = $e['hora_alteracao'] . " " . $dataTmp[1];
	
?>		
		<tr>
		<td><?php echo $e['descricao']; ?></td>
		<td><?php if($e['credito_debito'] == 0){
		
			echo "Crédito";
		
		}else echo "Débito"?></td>
		<td><?php echo $e['ultimoUsuario'] ?> - <?php echo $e['hora_alteracao'] ?></td>
		<td><input type="button" class="btn-small btn-edt" value="Editar" onclick="javascript:window.location.href='edt/id/<?php echo $e['id']?>'" /> <input type="button" class="btn-small btn-del" value="Delete" onclick="confirmaDelete('Grupo: <?php echo $e['descricao']?>', <?php echo $e['id']?>)" /></td> </tr>
<?php	
	}
?>

</tbody>
</table>
<div style="width:80%; margin-left:5px;">
	<span style="font-size:15px;" >Grupos financeiros são classificações de custos e despesas para organizar os gastos da sua loja, assim dentro desses grupos você lançará seus gastos e poderá saber, por exemplo, quanto você tem de Custo Fixo todo mês ou  ainda quanto você normalmente gasta com Impostos e Taxas. Temos disponíveis no sistema os grupos:</span>
	<br/>
	<br/>
	<ul>
		<li style="font-size:15px;">Custo Fixo</li>
		<li style="font-size:15px;">Custo Variável</li>
		<li style="font-size:15px;">Despesas Administrativas</li>
		<li style="font-size:15px;">Despesas Diversas</li>
		<li style="font-size:15px;">Impostos e Taxas</li>
		<li style="font-size:15px;">Outras Receitas</li>
		<li style="font-size:15px;">Pagamento de Funcionários</li>
	</ul>
	
	<br/>
	<span style="font-size:15px;" >Caso seja necessário você pode incluir um novo Grupo Financeiro, para isso basta clicar em Adicionar e cria esse novo grupo.</span>

	</div>
<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

	function confirmaDelete(msg, id){
	
		if(confirm("Deseja realmente excluir a "+msg+" ?")){
		
			window.location.href = "del/id/" + id;
		
		}
	
	}

</script>
