<form id="imagens" name="upload" enctype="multipart/form-data"  action="add" class="form" method="post">
	
	<div id="fotos" style="width:98.1%;">
		<div class="inline">
			<label class="label">Banner Virtual</label>	
			<input type="file" id="image" name="image" class="text" title="Fotos"/>
		</div>
	</div>

	<div class="inline" style="margin-top:10px;clear:both;">
		<input type="submit" class="btn-small btn-add" value="Upload" />
	</div>
	
	<div class="inline" style="width:<?php echo $this->w;?>px; height:<?php echo $this->h;?>px;clear:both;margin-bottom:10px">
		<label class="label">Banner Atual</label>	
		<img src="/propaganda/<?php echo $this->nomeImg; ?>?ts=<?php echo @date("Ymdhis");?>">
	</div>

	
	<div class="inline" style="margin-top:10px;clear:both;" >
		<input type="submit" class="btn-small btn-del" value="Deletar" />
	</div>
 
 </form>
 
 <div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#id_projeto").val() == 0){
		
		erro = true;
		
		msg += "<br>Selecione o perfil.";
	
	}
	
	if($("#titulo").val() == 0){
		
		erro = true;
		
		msg += "<br>O campo titulo deve ser preenchido.";
	
	}
	
	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})

manageTabs("tab_projetos_sis","menu_projetos");

</script>
