<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="lista" class="form" method="post">

		<div class="inline">
		<label class="label">Ano</label>
		<input type="text" id="ano" name="ano" class="text" value="" />
		</div>
	
		<div class="inline">
		<label class="label">Mes</label>
		<input type="text" id="mes" name="mes" class="text" value="" />
		</div>
			
		<div class="inline" style="margin-top:10px;">
		<input type="button" id="button" name="button" class="btn-small btn-find" value="Buscar">
		</div>	
			
		</form><br><br>	
			
			
			<table class = 'table' style="float:left; display:inline; width:500px; margin-bottom:0px;">
			<thead><tr><th>Resultado Final</th></tr></thead>
			<tbody>
			<tr><td><div style="float:left; display:inline; width:300px; margin-bottom:0px;" >teste de tamanho</div></td><td><div style="float:left; display:inline; width:200px; margin-bottom:0px;" >do campo</div></td></tr>
			</tbody></table>
	
			
			<br><br>
			
						
			<table class = 'table' style="float:left; display:inline; width:500px; margin-bottom:0px;">
			<thead><tr><th>Folha De Pagamento</th></tr></thead>
			<tbody>
			<tr><td><div style="float:left; display:inline; width:300px; margin-bottom:0px;" >teste de tamanho</div></td><td><div style="float:left; display:inline; width:200px; margin-bottom:0px;" >do campo</div></td></tr>
			</tbody></table>
		
			
			