
<form class="form" action="compras" method="post">
	<!-- 
	<div class="inline" id="div_select">
	<label class="label">Vendedor</label>
	<select name = "id_vendedor" id="id_vendedor" class="select">
		<option value = "0">Todos</option>
		<?php
		foreach($this->vendedores as $vendedor){
		
			if($vendedor['id'] == $this->id_vendedor){
			
				echo "<option selected='selected' value = '".$vendedor['id']."'>".$vendedor['nome']."</option>";
			
			}else{
		
				echo "<option value = '".$vendedor['id']."'>".$vendedor['nome']."</option>";
			
			}
		
		}
		?>
		</select>		
	</div>
	 -->
	<div class="inline" id="div_mes">
		<table width="100%">
			<tr>
				<td>
					<label class="label">Mês</label>
				</td>
				<td>
					<label class="label">Períodos</label>
				</td>
			</tr>
			<tr>
				<td>
					<select class="select" onChange="enviaPeriodo(this.value);" style="width:95%;">
						<option value="0">Selecione</option>
						<?php
							
							for($i = @date("m"); $i > (@date("m")-25); $i--){
							
								$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
								$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
								$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
	
								
								switch ($mesNum){
									case 1:
										$option =  "Janeiro - ".$anoNum;
										break;
										
									case 2:
										$option =  "Fevereiro - ".$anoNum;
										break;
									
									case 3:
										$option =  "Março - ".$anoNum;
										break;
										
									case 4:
										$option =  "Abril - ".$anoNum;
										break;
										
									case 5:
										$option =  "Maio - ".$anoNum;
										break;
										
									case 6:
										$option =  "Junho - ".$anoNum;
										break;
										
									case 7:
										$option =  "Julho - ".$anoNum;
										break;
										
									case 8:
										$option =  "Agosto - ".$anoNum;
										break;
										
									case 9:
										$option =  "Setembro - ".$anoNum;
										break;
									
									case 10:
										$option =  "Outubro - ".$anoNum;
										break;
										
									case 11:
										$option =  "Novembro - ".$anoNum;
										break;
										
									case 12:
										$option =  "Dezembro - ".$anoNum;
										break;
						
								}
								
								echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
							
							}
						
						?>
						
					</select>
				</td>
				<td>
					<select class="select" onChange="enviaPeriodoMaior(this.value);" style="width:95%;">
						<option value="">Selecione</option>
						<option value="12">Últimos 12 meses</option>
						<option value="6">Últimos 6 meses</option>
						<option value="3">Últimos 3 meses</option>
						<option value="1">Ano passado</option>
						<option value="0">Ano atual</option>
					</select>
				</td>
			</tr>
		</table>

	</div>
	
	<div class="inline">
		<table width="100%">
			<tr>
				<td>
					<label class="label">Data Inicial</label>
				</td>
				<td>
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<input type="text" class="text" name="data_inicial" id="data_inicial" style="width:90%;" value="<?php echo $this->data_inicial; ?>"/>
				</td>
				<td>
					<input type="text" class="text" name="data_final" id="data_final" style="width:90%;" value="<?php echo $this->data_final; ?>"/>
				</td> 
			</tr>
		</table>
	</div>
	
	<div class="inline" style="clear:both; width:50%;" id="div_botoes">
		<input type="button" class="btn-small btn-find" value="Pesquisar" onclick="valida();" />
		<input type="button" class="btn-small-xls" value="Gerar XLS" onclick="geraXls();"/>
		<input type="button" class="btn-small-imp" value="Imprimir" onclick="imprimir('print','Compras');"/>
		<input type="hidden" id="relatorio" name="relatorio" value=""/>
	</div>

</form>
<br>

	<!-- <div class="inline" style="clear:both; margin-top:20px; margin-bottom:10px; margin-left:10px; width:40%; height:auto; font-family: Arial, Helvetica, sans-serif;" id="div_num">
		<b><label class="label">N&uacute;mero de Compras: <span id="num_veiculos"><?php echo $this->qtdNegociacoes; ?></span><span id="dados"></span></label></b>
	</div> -->

<div id="print">


<style>

	/*CSS para impressão*/
@media print {
	
	.table {
		width:100%;
		border:1px solid #d4d4d4;
		margin-bottom:15px;
		margin-left:auto;
		margin-right:auto;
		padding:10px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:15px;
	}
	
	th {
	    background-color: #ccc;
	    color: #000;
	    text-align: center;
	}

	th, td {
	    padding: 2px 5px;
	    border-left:1px solid #d4d4d4;
		border-top:1px solid #d4d4d4;
	}

	th {
	    font-weight: bold;
	}

}

</style>


	<div id="table"></div>

</div>


<script type="text/javascript">

	function imprimir(id, pg) {
	
		$("td").css("font-size","10px");
	
		var oPrint, oJan;
		oPrint = window.document.getElementById(id).innerHTML;
		oJan = window.open(pg);
		oJan.document.write(oPrint);
		oJan.window.print();
		oJan.document.close();
		oJan.focus();
		
		$("td").css("font-size","12px");

	}

	function geraXls(){
		$("form").attr("action","gerar-xls");
		$("form").submit();
		$("form").attr("action","lista");
	}

	function buscaCompras(){

		$("#table").html("<center>Carregando.....</center>");

		var dataInicial = $("#data_inicial").val();
		var dataFinal = $("#data_final").val();

		$.ajax({
			type: "POST",
			url: '/relatorios/ajax/fn/compras',
			async: true,
			dataType:"text",
			data: ({'data_inicial_abertura':dataInicial, 'data_final_abertura':dataFinal}),
			success:function(resp){

				$("#table").html(resp);
				$("#relatorio").val(resp);
					
			}
		});
		
	}


	function valida(){
		
		var i = 1;
		mesInicio = $("#data_inicial").val().split("/")[1];
		mesFim = $("#data_final").val().split("/")[1];
		
		anoInicio = $("#data_inicial").val().split("/")[2];
		anoFim = $("#data_final").val().split("/")[2];

		while(mesInicio != mesFim || anoInicio != anoFim){

			mesInicio++;
			
			if(mesInicio >= 13){
				mesInicio = 1;
				anoInicio++;
			}
			
			i++;
		
		}

		if(i >= 13){
			alert("Não é permitido pesquisar poríodos maiores que 12 meses!");
		}else{
			buscaCompras();
		}

	}



	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}
	
	}
	
	
	function enviaPeriodoMaior(valor){

		if(valor == "1"){		
			var dataInicial = '01/01/<?php echo  @date("Y")-1; ?>';
			var datafinal = '31/12/<?php echo  @date("Y")-1; ?>';	
		}
		
		if(valor == "0"){		
			var dataInicial = '01/01/<?php echo  @date("Y"); ?>';
			var datafinal = '31/12/<?php echo @date("Y"); ?>';	
		}
		
		if(valor == "3"){		
			var dataInicial = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")-2, 01, @date("Y")));?>';
			var datafinal = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")+1, 0, @date("Y"))); ?>';	
		}
		
		if(valor == "6"){		
			var dataInicial = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")-5, 01, @date("Y")));?>';
			var datafinal = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")+1, 0, @date("Y"))); ?>';	
		}
		
		if(valor == "12"){		
			var dataInicial = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")-11, 01, @date("Y")));?>';
			var datafinal = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")+1, 0, @date("Y"))); ?>';	
		}

		$("#data_inicial").val(dataInicial);
		$("#data_final").val(datafinal);
		
	
	
	}

	$(document).ready(function(){
		buscaCompras();
	});

</script>