<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<style>

	.table {
		width:100%;
		border:1px solid #d4d4d4;
		margin-bottom:15px;
		margin-left:auto;
		margin-right:auto;
		padding:10px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:15px;
	}
	
	.table tr th {
	    background: #a3a3a3;
	    color: #FFF;
	    text-align: center;
	}

	.table tr th, .table tr td {
	    padding: 2px 5px;
	    border-left:1px solid #d4d4d4;
		border-top:1px solid #d4d4d4;
	}

	th {
	    font-weight: bold;
	}

</style>
<?php

$nomeArquivo = $this->tipoRelatorio." De ".$this->dataInicial." até ".$this->dataFinal;

header("Content-type: application/msexcel");
header("Content-Disposition: attachment; filename=".$nomeArquivo.".xls");

echo $this->relatorio;

exit;

?>