<form id="usuarios" name="usuarios" enctype="application/x-www-form-urlencoded" action="" class="form" method="post">

		
	<div id="divSenha" class="inline" style="display:inline">
		<label class="label">Nova Senha</label>
		<input type="password" id="senha" name="senha" class="text req" title="Senha do Usuário"/>
	</div>
	
	<div id="divConfirmaSenha" class="inline" style="display:inline">
		<label class="label">Confirmar Nova Senha</label>
		<input type="password" id="confirmaSenha" name="confirmaSenha" class="text req" title="Confirmar Senha"/>
	</div>
	
	<div class="inline" style="clear:both">
		<input type="hidden" id="id" name="id" value="<?php echo $this->idUsuario;?>"/>
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Salvar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){
	
	var msg = "";
	var erro = false;
	
	if($("#senha").val() == ''){
		
		erro = true;
	
		msg += "<br>O campo senha deve ser preenchido.";
	
	}
	
	if($("#confirmaSenha").val() == ''){
		
		erro = true;
	
		msg += "<br>O campo confirma senha deve ser preenchido.";
	
	}
	
	if($("#confirmaSenha").val() != $("#senha").val()){
		
		erro = true;
	
		msg += "<br>As senhas não correspondem. Devem ser iguais.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){

	valor = float2moeda($("#valor_fixo_mensal").val());
	$("#valor_fixo_mensal").val(valor);
	
	valor = float2moeda($("#valor_fixo").val());
	$("#valor_fixo").val(valor);

	$("#cpf").mask("999.999.999-99");
	$("#rg").mask("99.999.999-9");
	$("#valor_fixo_mensal").attr("onkeyup","validaMoedaBR(this.id)");
	$("#valor_fixo").attr("onkeyup","validaMoedaBR(this.id)");
	
	$('#telefone').focusout(function(){
    var phone, element;
    element = $(this);
    element.unmask();
    phone = element.val().replace(/\D/g, '');
    if(phone.length > 10) {
        element.mask("(99) 99999-999?9");
    } else {
        element.mask("(99) 9999-9999?9");
    }
	}).trigger('focusout');
	
	$('#celular').focusout(function(){
    var phone, element;
    element = $(this);
    element.unmask();
    phone = element.val().replace(/\D/g, '');
    if(phone.length > 10) {
        element.mask("(99) 99999-999?9");
    } else {
        element.mask("(99) 9999-9999?9");
    }
	}).trigger('focusout');
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}
	
	$('#data_nascimento').focus(function(){
		$(this).calendario({
			target:'#data_nascimento'
		});
	});
	
	$('#data_contratacao').focus(function(){
		$(this).calendario({
			target:'#data_contratacao'
		});
	});

})

function ativaDivVend(destino, c){
	
	if(c == <?php echo VENDEDOR; ?> || c == <?php echo GERENTE;?> || c == <?php echo SUPERVISOR;  ?>){
		
		$("#funcionario").css('display','none');
		$("#"+destino).css('display','inline');
	
	}else{
	
		$("#"+destino).css('display','none');
	
	}
	
}

function ativaDivFunc(destino, c){
	
	if(c == <?php echo FUNCIONARIO; ?>){
		
		$("#"+destino).css('display','inline');
		$("#divLogin").css('display','none');
		$("#divSenha").css('display','none');
	
	}else{
	
		$("#"+destino).css('display','inline');
		$("#divLogin").css('display','inline');
		$("#divSenha").css('display','inline');
		
	}
	
}

</script>
