<html>
	<head>
		<title>ENVIAR PARA UM AMIGO</title>
<style>
	table{
		#border:solid 1px;
		width:500px;
	}
	
	label{
		font:12px Arial, Helvetica, sans-serif;
		color:#666666;
	}
	
	input[type=text]{
		font:12px Arial, Helvetica, sans-serif;
		color:#666666;
		height:30px;
		width:99%;
		border:solid 2px #CD0000;
	}
	
	textarea{
		font:12px Arial, Helvetica, sans-serif;
		color:#666666;
		height:100px;
		width:99.5%;
		border:solid 2px #CD0000;
	}
	
	.header-bot {
		display:inline-block;
		background:url(/arquivos_site/images/header-but.jpg) repeat-x #9e0202;
		font-size:12px;
		font-weight:bold;
		font-family:Arial, Helvetica, sans-serif;
		color:#fff;
		#line-height:12px;
		text-decoration:none;
		border:1px solid #880707;
		padding:10px 2px 12px 0px;
		border-radius:3px;
		-moz-border-radius:3px;
		-webkit-border-radius:3px;
	}	

	.header-bot:hover{
		background:#353535;
		border-color:#242424;
	}
	
	.header-close {
		display:inline-block;
		background-color:#005500;
		font-size:12px;
		font-weight:bold;
		font-family:Arial, Helvetica, sans-serif;
		color:#fff;
		#line-height:12px;
		text-decoration:none;
		border:1px solid green;
		padding:10px 2px 12px 0px;
		border-radius:3px;
		-moz-border-radius:3px;
		-webkit-border-radius:3px;
	}	

	.header-close:hover{
		background:#353535;
		border-color:#242424;
	}
	
	.sucess{
		color:#005500;
		background-color: #AAFFAA;
		border:1px solid #005500;
	}

	.erro{
		font-size:13px;
		color:#FF0000;
		background-color: #FFCCCC;
		border:1px solid #FF0000;
	}
	
</style>

<script src="/arquivos_site/js/jquery-1.9.1.min.js" type="text/javascript"></script>

</head>
<center><div>

	<?php 
		if(!$this->enviado == "Sucesso"){
	?>

	<form action="/carros-usados/anuncio-irregular" method="post" name="anuncio_irregular">
		<table>
			<tr><td colspan="2"><label style="color:red; font-size:15px;">Inclua aqui uma mensagem nos informando a irregularidade no an&uacute;ncio para podermos corrigir.<br><br><label></td></tr>
			<tr><td colspan="2"><label style="font-size:15px;"><b>Ve&iacute;culo: </b><?php echo $this->veiculo['modelo'] ;?><br><br><label></td></tr>
			<tr><td><label><b>Nome</b></label><br><input type="text" id="nome" name="nome"></td><td><label><b>E-mail</b></label><br><input type="text" id="email" name="email"></td></tr>
			<tr><td colspan="2"><label><b>Mensagem</b></label><br><textarea name="mensagem" id="mensagem"></textarea></td></tr>
			<tr><td colspan="2"><div class="msg" id="msg" name="msg"></div></td></tr>
			<tr><td colspan="2"><center><a href="javascript:validaCampo();" class="header-bot" style="width:100px; margin-top:20px;"><center>Enviar</center></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<a href="javascript:window.close();" class="header-bot" style="width:100px;"><center>Cancelar</center></a></center></td></tr>
		</table>
		<input type="hidden" name="path" value="/carros-usados/veiculo/id/<?php echo $this->veiculo['id']; ?>"/>
		<input type="hidden" name="id_empresa" value="<?php echo $this->veiculo['id_empresa']; ?>"/>
	</form>
	<?php 
		}else{
	?>
	<div style="margin-top:100px; border: outset 1px green; background-color:#AAFFAA; font-family:Arial, Helvetica, sans-serif; color:#005500;">
		<br>
		Mensagem enviada com sucesso!<br><br>
		Obrigado.<br><br>
		<a href="javascript:window.close();" class="header-close" style="width:100px;"><center>Fechar</center></a><br><br>
	</div>
	<?php 
		}
	?>
</div>
</center>
</html>

<script type="text/javascript">
	
	function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#nome").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo nome deve ser preenchido.";
	
	}
	
	if($("#email").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo e-mail deve ser preenchido.";
	
	}
	
	if($("#mensagem").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo mensagem deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})
</script>