<script>

	$("#menu_busca").remove();

</script>

<style>

	#alfabeto{
		#margin-left:9px;
		width:100%;
	}

	#alfabeto li{
		border:solid 1px #CCCCCC;
		display:inline;
		padding:6px 10px 6px 10px;
		font-weight: bold;
		background-color:#EEEEEE;
		margin-left:1.7px;
	}
	
	#alfabeto a{
		text-decoration:none;
		color:#666666;
	}
	
	#alfabeto li:hover{
		background-color:#CCCCCC;
	}
	
	#busca_lojas{
		border:solid 1px #CCCCCC;
		width:98%;
		height:50px;
		margin-left:11px;
		background-color:#EEEEEE;
	}
	
	#busca_lojas input{
		margin-top:-5px;
		width:300px;
		height:25px;
		border:solid 1px #CCCCCC;
		#color:#666666;
		font-size:15px;
	}
	
	#busca_lojas input:hover{
		border:solid 2px #CCCCCC;
	}
	
	#busca_lojas div{
		margin-top:15px;
	}
	
	#busca_lojas span{
		margin-left:10px;
		font-weight: bold;
		font-size:15px;
		color:#CE0505;
	}
	
	#btn_buscar{
		text-decoration:none;
		padding: 6px 23px 8px 23px;
		background-color:#CE0505;
		border:solid 1px #CCCCCC;
		margin-left:10px;
	}
	
	.lojas{
		width:98%;
		margin-bottom:110px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:15px;
		clear:both;
	}
	
	.lojas tr td a{
		#text-decoration:none;
		color:#666666;
	}

	#table_busca{
		#float:top;
		margin-left:11px;
		width:98.2%;
		background-color:#E8E8E8;
		margin-bottom:10px;
		margin-top:-20px;
		height:60px;
		border-bottom: solid 2px #CFCFCF;
		border-top: solid 2px #CFCFCF;
		border-right: solid 2px #CFCFCF;
		border-left: solid 2px #CFCFCF;
		color:#666666;
	}
	
	#table_busca tr td {
		margin-left:10px;
		background-color:#E8E8E8;
		vertical-align:middle;
	}
	
	#table_busca tr td select{
		margin-left:5px;
		border-top: outset 1px #E8E8E8;
		border-left: outset 1px #E8E8E8;
		border-right: outset 1px #E8E8E8;
		border-bottom: outset 2px #E8E8E8;
		width:150px;
		height:30px;
		vertical-align:middle;
	}
	
	.texto{
		border-top: outset 1px #E8E8E8;
		border-left: outset 1px #E8E8E8;
		border-right: outset 1px #E8E8E8;
		border-bottom: outset 2px #E8E8E8;
		width:70px;
		height:25px;
		#vertical-align:middle;
	}
	
	.texto2{
		border-top: outset 1px #E8E8E8;
		border-left: outset 1px #E8E8E8;
		border-right: outset 1px #E8E8E8;
		border-bottom: outset 2px #E8E8E8;
		width:140px;
		height:25px;
		#vertical-align:middle;
	}

</style>

</header>

<section id="content">
<table id="table_busca">
	<tr>
		
		<td>
			<form method="post" id="busca_string" action="/carros-usados/busca-veiculos">
			&nbsp;&nbsp;<b>Modelo</b><br><input style="margin-left:5px;" type="text" class="texto2" name="str_veiculo" id="str_veiculo"/><br>&nbsp;&nbsp;<span style="font-size:10px;">Exemplo: Celta</span></td><td style="border-right: solid 2px #CCCCCC;"><input style="width:60px; margin-right:5px;" type="submit"  id="buttom_busca"  value="Buscar"/><br>
			</form>
		</td>
		
		<td>
			<form name="busca" method="post" action="/carros-usados/busca-veiculos">
			<table>
				<tr>
					<td>
						<img id="button_carro" src="/arquivos_site/images/button_carro.gif" onclick="buscaMarca();" />
					</td>
				</tr>
				<tr>
					<td>
						<img id="button_moto" src="/arquivos_site/images/button_moto.gif" onclick="buscaMarca(1);" />
					</td>
				</tr>
				<input type="hidden" id="segmento" name="segmento" value="carro" />
			</table>
		</td>
		<td>
			
			&nbsp;&nbsp;<b>Marca</b> <select id="marca_usado" name="marca" onChange="buscaModelo(this.value);">
					<option value="">Selecione</option>
				</select><br>&nbsp;	
		</td>
		<td>
			&nbsp;&nbsp;<b>Modelo</b> <select id="modelo_usado" name="modelo" onChange="buscaCidade(this.value);">
				<option value="">Selecione</option>
			</select><br>&nbsp;		
		</td>
		<td>
			&nbsp;&nbsp;<b>Cidade</b> <select id="cidade_usado" name="cidade">
				<option value="">Selecione</option>
			</select><br>&nbsp;		
		</td>
		<td>
			&nbsp;&nbsp;<b>Valor:</b> De <input type="text" style="margin-left:5px;" class="texto" name="minimo_preco" id="minimo_preco" onKeyUp="validaMoedaBR(this.id);"/>
			<br>&nbsp;	
		</td>
		<td>
			at&eacute; <input type="text" class="texto" name="maximo_preco" id="maximo_preco" onkeyup="validaMoedaBR(this.id);"/>
			<br>&nbsp;	
		</td>
		
		<td>
			<br><input type="submit" style="width:60px;" id="buttom_busca"  value="Buscar"/>
			<br>&nbsp;
		</td>
	</tr>
	</form>
</table>


<form action="busca-lojas" method="post">
	<div id="busca_lojas">
		<div>
			<span>Buscar </span> 
			<input type="text" id="nome_concessionaria" name="nome_concessionaria"/>
			<input type="hidden" id="letra" name="letra" value=""/>
			<a href="javascript:submeter();" id="btn_buscar"><img style="width:13px; margin-top:3px;" src="/images/lupa.png"/><a/>
		</div>
	</div>
	
</form>


<div style="margin-top:12px; margin-bottom:20px;">
	<ul id="alfabeto">
		<a href="javascript:lojaLetra('A');"><li>A</li></a>
		<a href="javascript:lojaLetra('B');"><li>B</li></a>
		<a href="javascript:lojaLetra('C');"><li>C</li></a>
		<a href="javascript:lojaLetra('D');"><li>D</li></a>
		<a href="javascript:lojaLetra('E');"><li>E</li></a>
		<a href="javascript:lojaLetra('F');"><li>F</li></a>
		<a href="javascript:lojaLetra('G');"><li>G</li></a>
		<a href="javascript:lojaLetra('H');"><li>H</li></a>
		<a href="javascript:lojaLetra('I');"><li>I</li></a>
		<a href="javascript:lojaLetra('J');"><li>J</li></a>
		<a href="javascript:lojaLetra('K');"><li>K</li></a>
		<a href="javascript:lojaLetra('L');"><li>L</li></a>
		<a href="javascript:lojaLetra('M');"><li>M</li></a>
		<a href="javascript:lojaLetra('N');"><li>N</li></a>
		<a href="javascript:lojaLetra('O');"><li>O</li></a>
		<a href="javascript:lojaLetra('P');"><li>P</li></a>
		<a href="javascript:lojaLetra('Q');"><li>Q</li></a>
		<a href="javascript:lojaLetra('R');"><li>R</li></a>
		<a href="javascript:lojaLetra('S');"><li>S</li></a>
		<a href="javascript:lojaLetra('T');"><li>T</li></a>
		<a href="javascript:lojaLetra('U');"><li>U</li></a>
		<a href="javascript:lojaLetra('V');"><li>V</li></a>
		<a href="javascript:lojaLetra('W');"><li>W</li></a>
		<a href="javascript:lojaLetra('X');"><li>X</li></a>
		<a href="javascript:lojaLetra('Y');"><li>Y</li></a>
		<a href="javascript:lojaLetra('Z');"><li>Z</li></a>
	</ul>
	
</div>
<div>
<table class="lojas">
	<?php
		
		$cont = 1;
		
		foreach($this->lojas as $loja){
			
			if($cont == 1){
			
				echo "<tr>";
			
			}
			
			echo "<td><a href='/carros-usados/busca-veiculos/".str_replace(" ","-",$loja['cidade'])."/".str_replace(" ","-",$loja['nome_fantasia'])."/id-empresa/".$loja['id']."'>".$loja['nome_fantasia']."</a></td>";
			
			
			if($cont == 3){
			
				echo "</tr>";
				
				$cont = 0;
			
			}
			
			$cont++;
		
		}
		
		if($cont != 1){
		
			echo "</tr>";
		
		}
	?>
	
</table>
</div>


<script>

	$("#buscaLojas").attr("class","current");

	function lojaLetra(letra){
	
		$("#letra").val(letra);
		
		$("form").submit();
	
	}
	
	function submeter(){
		
		$("form").submit();
	
	}
	
	buscaMarca();
	
	

</script>

<script>

	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	 
	ga('create', 'UA-41555898-1', 'sistemameucar.com.br');
	ga('send', 'pageview');
 
</script>




</section>
