<style>
	#form{
		width:98%;
	}

	#form td{
		width:33%;
		#border: solid 1px;
	}
	
	#form input[type='text']{
		height:20px;
		margin-left:2px;
		width:95%;
	}
	
	#form input[type='password']{
		height:20px;
		margin-left:2px;
		width:95%;
	}
</style>

</header>

<section id="content">
<center>

<table id="table_busca">
	<tr>
		
		<td>
			<form method="post" id="busca_string" action="/carros-usados/busca-veiculos">
			&nbsp;&nbsp;<b>Modelo</b><br><input style="margin-left:5px;" type="text" class="texto2" name="str_veiculo" id="str_veiculo"/><br>&nbsp;&nbsp;<span style="font-size:10px;">Exemplo: Celta</span></td><td style="border-right: solid 2px #CCCCCC;"><input style="width:60px; margin-right:5px;" type="submit"  id="buttom_busca"  value="Buscar"/><br>
			</form>
		</td>
		
		<td>
			<form name="busca" method="post" action="/carros-usados/busca-veiculos">
			<table>
				<tr>
					<td>
						<img id="button_carro" src="/arquivos_site/images/button_carro.gif" onclick="buscaMarca();" />
					</td>
				</tr>
				<tr>
					<td>
						<img id="button_moto" src="/arquivos_site/images/button_moto.gif" onclick="buscaMarca(1);" />
					</td>
				</tr>
				<input type="hidden" id="segmento" name="segmento" value="carro" />
			</table>
		</td>
		<td>
			
			&nbsp;&nbsp;<b>Marca</b> <select id="marca_usado" name="marca" onChange="buscaModelo(this.value);">
					<option value="">Selecione</option>
				</select><br>&nbsp;	
		</td>
		<td>
			&nbsp;&nbsp;<b>Modelo</b> <select id="modelo_usado" name="modelo" onChange="buscaCidade(this.value);">
				<option value="">Selecione</option>
			</select><br>&nbsp;		
		</td>
		<td>
			&nbsp;&nbsp;<b>Cidade</b> <select id="cidade_usado" name="cidade">
				<option value="">Selecione</option>
			</select><br>&nbsp;		
		</td>
		<td>
			&nbsp;&nbsp;<b>Valor:</b> De <input type="text" style="margin-left:5px;" class="texto" name="minimo_preco" id="minimo_preco" onKeyUp="validaMoedaBR(this.id);"/>
			<br>&nbsp;	
		</td>
		<td>
			at&eacute; <input type="text" class="texto" name="maximo_preco" id="maximo_preco" onkeyup="validaMoedaBR(this.id);"/>
			<br>&nbsp;	
		</td>
		
		<td>
			<br><input type="submit" style="width:60px;" id="buttom_busca"  value="Buscar"/>
			<br>&nbsp;
		</td>
	</tr>
	</form>
</table>
	
		<table id="form">
		<form action="/site/cadastro-site" method="post" id="cadastro_site">
			<tr>
				<td colspan="3" style="font-size:30px;">Cadastre-se e seu an&uacute;ncio estará disponivel em até 24 horas<br><br> conforme o <a href="javascript:abrirPopup('<?php echo URL ?>site/termos-uso',750,405);">termos de uso</a> após a confirmação de pagamento.<br><br><br></td>
			</tr>
			<tr>
				<td><label><b>Nome</b></label><br><input type="text" id="nome" name="nome"></td>
				<td><label><b>E-mail</b></label><br><input type="text" id="email" name="email" onKeyUp="preencheLogin();"></td>
				<td><label id="cpf_cnpj"><b>CPF</b></label><br><input type="text" id="cpf" name="cpf" value=""/></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td><label><b>RG</b></label><br><input type="text" id="rg" name="rg"></td>
				<td><label><b>Endere&ccedil;o</b></label><br><input type="text" id="endereco" name="endereco"></td>
				<td><label id="cpf_cnpj"><b>Bairro</b></label><br><input type="text" id="bairro" name="bairro" value=""/></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td><label><b>Cidade</b></label><br><input type="text" id="cidade" name="cidade"></td>
				<td><label><b>Estado</b></label><br><input type="text" id="estado" name="estado"></td>
				<td><label id="cpf_cnpj"><b>Telefone</b></label><br><input type="text" id="telefone" name="telefone" value=""/></td>
			</tr>
			<tr>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
				<td>&nbsp;</td>
			</tr>
			<tr>
				<td><label><b>Celular</b></label><br><input type="text" id="celular" name="celular"></td>
				<td></td>
				<td></td>
			</tr>
			
			<tr>
				<td>&nbsp;</td>
			</tr>
			
			<tr>
				<td colspan="3"><hr></hr></td>
			</tr>
			<tr>
				<td><label><b>Login</b></label><br><input type="text" id="login" name="login"></td>
				<td></td>
				<td></td>
			</tr>
			
			<tr>
				<td><label><b>Senha</b></label><br><input type="password" id="senha" name="senha" onKeyUp="confirmaSenha()"></td>
				<td><label><b>Confirma Senha</b></label><br><input type="password" id="senha2" name="senha" onKeyUp="confirmaSenha();"></td>
				<td><label id="status_senha"></label></td>
			</tr>
			<tr>
				<td colspan="3"><div style="align:left;"><input type="checkbox" name="newslatter" value="1" checked="checked"/>Gostaria de receber newslatter do site sistemameucar.com.br</div></td>
			</tr>
			<tr>
				<td colspan="3"><div style="align:left;"><input type="checkbox" id="aceito"/>Li e aceito os <a href="javascript:abrirPopup('<?php echo URL ?>site/termos-uso',750,405);">termos de uso</a></div></td>
			</tr>
			<tr>
				<td colspan="3"><span style="display:none; width:100%;" id="mensagem">&nbsp;Os campos marcados em vermelho s&atilde;o de preenchimento obrigat&oacute;rio.</span></td>
			</tr>
	
			<tr><td colspan="3">
				</form>
					<center>
						<div id="botao">
								<a href="javascript:validaCampo();" class="header-bot" style="width:100px; margin-top:20px;">Cadastrar</a>
						</div>
					</center>
				</td>
			</tr>
		</table>
</center>

<script type="text/javascript">

	$("#menu_busca").remove();
	
	function validaCampo(){
		
		var confirm = true;
		
		if($("#nome").val() == ""){
		
			$("#nome").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#nome").css("border","solid 1px");
			$("#nome").css("border-color","silver");
		
		}
		
		if($("#email").val() == ""){
		
			$("#email").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#email").css("border","solid 1px");
			$("#email").css("border-color","silver");
		
		}
		
		if($("#cpf").val() == ""){
		
			$("#cpf").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#cpf").css("border","solid 1px");
			$("#cpf").css("border-color","silver");
		
		}
		
		if($("#rg").val() == ""){
		
			$("#rg").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#rg").css("border","solid 1px");
			$("#rg").css("border-color","silver");
		
		}
		
		if($("#endereco").val() == ""){
		
			$("#endereco").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#endereco").css("border","solid 1px");
			$("#endereco").css("border-color","silver");
		
		}
		
		if($("#bairro").val() == ""){
		
			$("#bairro").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#bairro").css("border","solid 1px");
			$("#bairro").css("border-color","silver");
		
		}
		
		if($("#cidade").val() == ""){
		
			$("#cidade").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#cidade").css("border","solid 1px");
			$("#cidade").css("border-color","silver");
		
		}
		
		if($("#estado").val() == ""){
		
			$("#estado").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#estado").css("border","solid 1px");
			$("#estado").css("border-color","silver");
		
		}
		
		if($("#telefone").val() == ""){
		
			$("#telefone").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#telefone").css("border","solid 1px");
			$("#telefone").css("border-color","silver");
		
		}
		
		if($("#celular").val() == ""){
		
			$("#celular").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#celular").css("border","solid 1px");
			$("#celular").css("border-color","silver");
		
		}
		
		if($("#login").val() == ""){
		
			$("#login").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#login").css("border","solid 1px");
			$("#login").css("border-color","silver");
		
		}
		
		if($("#senha").val() == ""){
		
			$("#senha").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#senha").css("border","solid 1px");
			$("#senha").css("border-color","silver");
		
		}
		
		if($("#senha2").val() == ""){
		
			$("#senha2").css("border-color","red");
			confirm = false;
		
		}else{
		
			$("#senha2").css("border","solid 1px");
			$("#senha2").css("border-color","silver");
		
		}
		
		if($("#aceito").attr("checked") != "checked"){
		
			confirm = false;
			alert("É necessário aceitar os termos de uso para seguir com o cadastro!");
		
		}
		
		if(confirm){
			
			if(confirmaSenha()){
				
				$("#botao").html("<form target='pagseguro' action='https://pagseguro.uol.com.br/checkout/v2/payment.html' method='post'><input type='hidden' name='code' value='A800D378EBEBB07334A2FF96633E21F4' /><input type='image' src='https://p.simg.uol.com.br/out/pagseguro/i/botoes/pagamentos/94x52-pagar-assina.gif' name='submit' id='submit' alt='Pague com PagSeguro - é rápido, grátis e seguro!' /></form>");

			}else{
				
				$("#mensagem").html("&nbsp;Senhas est&atilde;o incorretas.");
				$("#mensagem").css("display","block");
				$("#mensagem").css("background-color","red");
				$("#mensagem").css("color","white");
			
			}
		
		}else{
			
			$("#mensagem").html("&nbsp;Os campos marcados em vermelho s&atilde;o de preenchimento obrigat&oacute;rio.");
			$("#mensagem").css("display","block");
			$("#mensagem").css("background-color","red");
			$("#mensagem").css("color","white");
		
		}
	
	}
	
	function preencheLogin(){
	
		$("#login").val($("#email").val());
	
	}
	
	function confirmaSenha(){
	
		if($("#senha").val() != $("#senha2").val()){
		
			$("#status_senha").html("&nbsp;<br><b>Senhas diferentes</b>");
			$("#status_senha").css("color","red");
			
			return false;
		
		}else{
		
			$("#status_senha").html("&nbsp;<br><b>Senha válida</b>");
			$("#status_senha").css("color","green");
			
			return true;
		
		}
		
	}
	
	$(function(){
	
		$("#submit").live('click', function(){
	
			$("#cadastro_site").submit();
	
		});
	
		$("#cep").mask("99999-999");
		$("#rg").mask("99.999.99?9-*");
		$("#cpf").mask("999.999.999-99");
		
		$('#celular').focusout(function(){
		var phone, element;
		element = $(this);
		element.unmask();
		phone = element.val().replace(/\D/g, '');
		if(phone.length > 10) {
			element.mask("(99) 99999-999?9");
		} else {
			element.mask("(99) 9999-9999?9");
		}
		}).trigger('focusout');
		
		$('#telefone').focusout(function(){
		var phone, element;
		element = $(this);
		element.unmask();
		phone = element.val().replace(/\D/g, '');
		if(phone.length > 10) {
			element.mask("(99) 99999-999?9");
		} else {
			element.mask("(99) 9999-9999?9");
		}
		}).trigger('focusout');
		
	});
	
	function abrirPopup(pagina,largura,altura) {

		w = screen.width;
		h = screen.height;
		meio_w = w/2;
		meio_h = h/2;
		altura2 = altura/2;
		largura2 = largura/2;
		meio1 = meio_h-altura2;
		meio2 = meio_w-largura2;
		window.open(pagina,'','scrollbars=no,toolbar=no,location=no,directories=no,status=no, menubar=no,resizable=no,copyhistory=no,height=' + altura + ',width=' + largura + ',top='+meio1+',left='+meio2+''); 

	}
	
	buscaMarca();
	
</script>
	
</section>
