<style>

	#resultado_fipe{
		border: solid 1px #222222;
		background-color:#444444;
		width:705px;
		height:120px;
		text-align:left;
		margin-top:40px;
		margin-right:11px;
		border-radius:3px;
		-moz-border-radius:3px;
		-webkit-border-radius:3px;
		color:#FFFFFF;
		float:right;
		font-size:18px;
	}

</style>

</header>

<section id="content">

<div id="resultado_fipe">
	<br>
	<center>
	Parab&eacute;ns seu cadastro foi realizado com sucesso, assim que verificarmos o <br>pagamento em at&eacute; 24 horas conforme regras do termos de uso voc&ecirc; ser&aacute; ativado para<br> cadastrar seu an&uacute;ncio.
	<br><br>
	Obrigado e at&eacute; breve.
	</center>
	
</div>

</section>
