<div>

	<pre>

	TERMO DE ADESÃO A SERVIÇO DE ANUNCIO DE VEÍCULO ATRAVÉS DO SITE MEU CAR
	
	
	
	IDENTIFICAÇÃO DAS PARTES:

	CONTRATANTE: Exclusivamente Pessoa física anunciante.

	CONTRATADA: Meu Car ltda.
		
	As partes acima identificadas têm, entre si, justo e acertado o presente 
	Contrato de prestação de serviço de anuncio de veículo automotor que se 
	regerá pelas cláusulas seguintes e pelas condições descritas no presente. 

	DO OBJETO DO CONTRATO 

	Cláusula 1ª. O objeto deste contrato consistirá na divulgação de veículo 
	automotor de propriedade do CONTRATANTE através do Web Site acessado 
	pelo endereço: www.sistemameucar.com.br de propriedade da CONTRATADA. 

	Parágrafo único: O serviço de anúncio ora contratado será exclusivamente 
	para a venda de veículo usado.

	DO PAGAMENTO 

	Cláusula 2ª. A CONTRATANTE deverá pagar à CONTRATADA o importe 
	de R$ 19,90 pela prestação de serviço de anuncio contratada, o qual será 
	efetivado via Pagseguro. O prazo de veiculação do anúncio será de 60 dias a 
	contar da data de publicação.

	Parágrafo único: Fica assegurado ao  CONTRATANTE  o direito de 1
	(um) anúncio gratuito por CPF pelo prazo de 30 (trinta) dias, desde que o 
	mesmo efetue o login através de sua conta pessoal no Facebook e permita 
	a divulgação do seu anúncio para seus contatos, sendo após tal prazo
	necessário a renovação e a cobrança mencionada na cláusula anterior 
	caso queira permanecer com o anúncio em veiculação.  Renovação que 
	somente ocorrerá se o anunciante solicitar, caso contrário o anúncio será 
	cancelado automaticamente sem custos para o anunciante.

	DAS OBRIGAÇÕES DO CONTRATANTE

	Cláusula 3ª. Em hipótese alguma poderá ser trocado o nome do anunciante ou 
	o veículo.

	Parágrafo único: Os anúncios reutilizados serão excluídos imediatamente da 
	veiculação sem gerar ao CONTRATANTE o direito a reembolso ou crédito de 
	qualquer natureza.

	Cláusula 4ª. Em caso de solicitação de retirada do anúncio, independente da 
	venda do veículo, não terá direito o CONTRATANTE a qualquer reembolso ou 
	crédito de qualquer natureza.

	Cláusula 5ª. Cabe ao  CONTRATANTE assegurar-se, antes de realizar 
	qualquer transação, de que o negócio proposto é idôneo e que a 
	comercialização do produto anunciado é legítima, não podendo se utilizar do 
	site para outros fins que não a oferta de veículo de sua propriedade, sendo 
	de sua inteira responsabilidade quaisquer danos causados a terceiros em 
	decorrência da exibição do anúncio.

	Cláusula 6ª. O  CONTRATANTE é o único responsável pelas transações 
	comerciais que realizar com usuários do site, não tendo a  CONTRATADA
	nenhuma responsabilidade sobre o negócio formalizado entre o contratante e 
	usuário. 

	Cláusula 7ª. O  CONTRATANTE é o único responsável pelas informações 
	fornecidas, bem como pela conferência dos dados cadastrados no site. 

	Parágrafo Primeiro: A utilização de informações falsas ou de propriedade de 
	terceiros, cadastrais ou de qualquer natureza, além de implicar na suspensão
	imediata da veiculação do anúncio, sujeitará o infrator às ações penais 
	cabíveis. 

	Parágrafo segundo: A suspensão do anúncio por infração do 
	CONTRATANTE tem caráter rescisório e não gera, em favor do mesmo, 
	quaisquer direitos a reembolso ou desconto no valor do pagamento já efetuado.

	Cláusula 8ª. Os campos a serem preenchidos deverão conter somente as 
	informações do veiculo anunciado de acordo com o padrão dos anúncios da 
	CONTRATADA, o qual faz parte integrante deste contrato, visando coibir a 
	desconformidade de dados. 

	Parágrafo primeiro: Os anúncios que forem preenchidos de forma inadequada 
	ou em desacordo com as instruções fornecidas serão excluídos da veiculação 
	até que sejam regularizados, não gerando ao  CONTRATANTE o direito a 
	reembolso ou crédito de qualquer natureza referente ao período em que o 
	anúncio ficou suspenso.

	Parágrafo segundo: As fotos que não estiverem condizendo com o veiculo 
	anunciado ou fizerem exibição de pessoas, serão canceladas e não serão 
	publicadas, não garantindo ao  CONTRATANTE direito a qualquer tipo de 
	indenização ou reembolso. 

	Cláusula 9ª. Fica expressamente proibido o  CONTRATANTE de enviar ou 
	transmitir quaisquer tipos de informações que induzam, incitem ou resultem 
	em atitudes discriminatórias, mensagens violentas ou delituosas que atentem 
	contra a moral e bons costumes e que contrariam a ordem pública, sob pena 
	de sofrer as sanções civis e criminais cabíveis.

	DAS OBRIGAÇÕES DA CONTRATADA

	Cláusula 10ª. O anúncio será publicado em até 24 horas após a confirmação 
	do pagamento, exceto fins de semana e feriados, salvo a ocorrência de algum 
	problema técnico.

	Parágrafo único: O anúncio será retirado do site após a comunicação da 
	venda do veículo ou a pedido do  CONTRANTE, estando a  CONTRATADA 
	isenta da responsabilidade de restituir o CONTRATANTE pelo valor pago.

	Cláusula 11ª. A CONTRATADA se compromete a manter sob sigilo todos os 
	dados cadastrais do  CONTRATANTE, exceto telefone, e-mail e cidade, os 
	quais a veiculação é obrigatória.

	Cláusula 12ª. A  CONTRATADA compromete-se a corrigir, no menor prazo 
	possível, eventuais falhas operacionais comunicadas pelo anunciante, não 
	respondendo por eventuais perdas, danos ou lucros cessantes resultantes de 
	tais eventos, não cabendo ao  CONTRATANTE qualquer ressarcimento ou 
	desconto do valor pago.

	DAS DISPOSIÇÕES FINAIS

	Cláusula 13ª. A  CONTRATADA não realiza intermediação das vendas e 
	compras, trocas ou qualquer tipo de transação feita pelos usuários de seu web 
	site, dedicando-se exclusivamente à prestação de serviço de disposição de 
	mídia para a divulgação de anúncios. A transação é feita diretamente entre as 
	partes interessadas.

	Cláusula 14ª. A CONTRATADA não garante ao  CONTRATANTE que as 
	vendas e os contatos se concretizarão com a efetivação desta contratação 
	e está isenta de qualquer obrigação em restituir os valores pagos para a 
	veiculação do anúncio, total ou parcial, nos casos em que o cliente não obtiver 
	o desempenho esperado.

	Cláusula 15ª. A CONTRATADA reserva-se o direito de não aceitar ou renovar 
	anúncios, a seu exclusivo critério, situação em que os valores pagos pelo 
	anunciante serão devolvidos no prazo de até dez dias úteis.

	Cláusula 16ª. A  CONTRATADA não tem qualquer responsabilidade de 
	efetivar a venda, transportar, entregar ou transferir os veículos vendidos 
	pelo CONTRATANTE em decorrência do anuncio efetivado.

	Cláusula 17ª. A  CONTRATADA não oferece garantia legal ou contratual 
	de qualquer tipo, inclusive a disposta do Código de Defesa do Consumidor 
	quanto aos produtos oferecidos através do Site, sendo qualquer garantia de 
	responsabilidade exclusiva do CONTRATANTE. 

	DO FORO

	Cláusula 18ª.  Fica eleito o Foro da Comarca de Jundiaí – SP para dirimir 
	quaisquer situações decorrentes do presente contrato.
	
	</pre>
</div>