<link rel="stylesheet" type="text/css" href="/css/avaliacoes/bootstrap2.css">
<link rel="stylesheet" type="text/css" href="/css/avaliacoes/select2.min.css">
<link rel="stylesheet" type="text/css" href="/css/avaliacoes/index.css">


<div id="div_aguarde" style="z-index: 10; text-align:center; opacity:0.8; background-color:#000;width:100%; height:1000px; position:fixed; font-size: 30px; color:#fff;">
    <div style="margin-top:200px;">Aguarde...</div>
</div>

<div class="modal" id="popup_busca" style="display:none;">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title title_reparo">Busca</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" >&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="form-group">
                    <span id="titulo_termo"></span><br>
                    <select id="termo" style="width:100%;" class="custom-select form-control-lg">
                    </select>
                </div>
            </div>
            <input type="hidden" id="tipo" value="">
            <input type="hidden" id="local" value="">
            <!-- <div class="modal-footer">
                <button type="button" class="btn btn-outline-warning" data-dismiss="modal" id="lista-busca">Buscar</button>
            </div> -->
        </div>
    </div>
</div>

<style type="text/css">
    thead tr th{
        font-size: 14px;
    }

    tbody tr td{
        font-size: 14px;
        color: #FFF;
    }
</style>
<div id="myTabContent" class="tab-content">
    <div class="tab-pane fade show active" id="geral">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th style="cursor: pointer;" onclick="popupBusca('avaliador', 'remoto')" scope="col">Avaliador</th>
                    <th style="cursor: pointer;" onclick="popupBusca('cliente', 'remoto')" scope="col">Cliente</th>
                    <th style="cursor: pointer;" onclick="popupBusca('veiculo', 'remoto')" scope="col">Veículo</th>
                    <th scope="col">Data</th>
                </tr>
            </thead>
            <tbody id="tbody_enviados" >
            
            </tbody>
        </table>
    </div>
</div>

<script type="text/javascript" src="/js/avaliacoes/jquery.min.js"></script>
<script type="text/javascript" src="/js/avaliacoes/bootstrap.min.js"></script>
<script type="text/javascript" src="/js/avaliacoes/index.js"></script>
<script type="text/javascript" src="/js/avaliacoes/fipe.js"></script>
<script type="text/javascript" src="/js/avaliacoes/list.js"></script>
<script type="text/javascript" src="/js/avaliacoes/select2.min.js"></script>