<link rel="stylesheet" type="text/css" href="/css/avaliacoes/bootstrap2.css">
<link rel="stylesheet" type="text/css" href="/css/avaliacoes/index.css">


<div id="div_aguarde" style="z-index: 10; text-align:center; opacity:0.8; background-color:#000;width:100%; height:1000px; position:fixed; font-size: 30px; color:#fff;">
    <div style="margin-top:200px;">Aguarde...</div>
</div>

        <style type="text/css">
            thead tr th{
                font-size: 14px;
            }

            tbody tr td{
                font-size: 14px;
            }
        </style>
        <div id="concessionario">
            <div id="myTabContent" class="tab-content">
                <div class="tab-pane fade show active" id="geral">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col">Avaliador</th>
                                <th scope="col">Cliente</th>
                                <th scope="col">Veículo</th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody id="tbody_geral" >
                        
                        </tbody>
                    </table>
                </div>
                <div class="tab-pane fade" id="individual">
                    <table class="table table-hover">
                        <thead>
                            <tr>
                                <th scope="col"></th>
                                <th scope="col">Cliente</th>
                                <th scope="col">Veículo</th>
                                <th scope="col">Data</th>
                            </tr>
                        </thead>
                        <tbody id="tbody">
                        
                        </tbody>
                    </table>
                </div>
            </div>

        </div>

        <script type="text/javascript" src="/js/avaliacoes/jquery.min.js"></script>
        <script type="text/javascript" src="/js/avaliacoes/bootstrap.min.js"></script>
        <script type="text/javascript" src="/js/avaliacoes/index.js"></script>
        <script type="text/javascript" src="/js/avaliacoes/fipe.js"></script>
        <script type="text/javascript" src="/js/avaliacoes/list.js"></script>