<?php















/*
	$file_path = "fotos_veiculos/10/";

    $file_path = $file_path . basename( $_FILES['uploaded_file']['name']);
    if(move_uploaded_file($_FILES['uploaded_file']['tmp_name'], $file_path)) {
       
	   echo "success";
    
	} else{
       
	   echo "fail";
   
   }
   */
?>



<!---
<form id="form" name="form" enctype="multipart/form-data" action="/service/android" class="form" method="post">

 <input type="file" name="uploaded_file"/>

<input type="submit"/ >

</form>---->