<?php
/*
	echo mb_convert_encoding($this->id_empresa, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->placa, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->marca, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->modelo, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->descricao_site, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->valor_compra, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->valor_venda, 'UTF-8', 'ISO-8859-1');
	echo mb_convert_encoding($this->opcionais, 'UTF-8', 'ISO-8859-1');
*/
?>