<form class="form" action="lista" method="post">

	<div class="inline">
		<label class="label">Nome</label>
		<input type="text" id="nome" name="nome" class="text" value="" />
	</div>
	
	<?php
	if($_SESSION['sessionUser']['id_perfil'] == 2 || $_SESSION['sessionUser']['id_perfil'] == 4 || $_SESSION['sessionUser']['id_perfil'] == 9){
	?>
	<div class="inline">
		<label class="label">Vendedor</label>
		<select id="vendedor" name="vendedor" class="text">
			<option value="">Todos</option>
			<?php echo $this->strVendedores; ?>
		</select>
	</div>
	<?php
	}
	?>

	<div class="inline" id="div_datas">
		<table>
			<tr>
				<td style="width:40%;">
					<label class="label">M&ecirc;s</label>
				</td>
				<td style="width:30%;">
					<label class="label">Data Inicial</label>
				</td>
				<td style="width:30%;">
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<select class="select" style="width:90%;" onChange="enviaPeriodo(this.value);" >
						<option value="0">Selecione</option>
						<?php

							for($i = @date("m"); $i > (@date("m")-25); $i--){
							
								$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
								$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
								$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
								
								if($mesNum == @date("m") && $anoNum == @date("Y")){
									
									$sel = "selected='selected'";
								
								}else{
									
									$sel = "";
								
								}
								
								switch ($mesNum){
									case 1:
										$option =  "Janeiro - ".$anoNum;
										break;
										
									case 2:
										$option =  "Fevereiro - ".$anoNum;
										break;
									
									case 3:
										$option =  "Mar&ccedil;o - ".$anoNum;
										break;
										
									case 4:
										$option =  "Abril - ".$anoNum;
										break;
										
									case 5:
										$option =  "Maio - ".$anoNum;
										break;
										
									case 6:
										$option =  "Junho - ".$anoNum;
										break;
										
									case 7:
										$option =  "Julho - ".$anoNum;
										break;
										
									case 8:
										$option =  "Agosto - ".$anoNum;
										break;
										
									case 9:
										$option =  "Setembro - ".$anoNum;
										break;
									
									case 10:
										$option =  "Outubro - ".$anoNum;
										break;
										
									case 11:
										$option =  "Novembro - ".$anoNum;
										break;
										
									case 12:
										$option =  "Dezembro - ".$anoNum;
										break;
						
								}
								
								echo "<option ".$sel." value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
							
							}
						
						?>
						
					</select>
				</td>
				<td>
					<input type="text" style="width:90%;" class="text" name="data_inicial" id="data_inicial" value="<?php echo "01/".@date("m")."/".@date("Y");  ?>"/>
				</td>
				<td>
					<input type="text" style="width:90%;" class="text" name="data_final" id="data_final" value="<?php echo @date("d", mktime(0, 0, 0, @date("m")+1, 0, @date("Y")))."/".@date("m")."/".@date("Y"); ?>"/>
				</td>
			</tr>
		</table>
	</div>

	<div class="inline">
		<table width="100%">
			<tr>
				<td width="50%">
					<label class="label">Marca</label>
				</td>
				<td>
					<label class="label">Modelo</label>
				</td>
			</tr>
			<tr>
				<td>
					<select id="marca" name="marca" class="text" onChange="buscaModelo(this.value, 1);">
						<option>Selecione</option>
					</select>
				</td>
				<td>
					<select id="veiculo" name="veiculo" class="text">
						<option value="">Selecione</option>
					</select>
				</td>
			</tr>
		</table>
		
	</div>
	
	<div class="inline">
		<table width="100%">
			<tr>
				<td width="50%">
					<label class="label">Origem</label>
				</td>
				<td>
					<label class="label">Resultado</label>
				</td>
			</tr>
			<tr>
				<td>
					<select id="origem" name="origem" class="text">
						<option>Todos</option>
					</select>
				</td>
				<td>
					<select title="Selecione a situação." id="resultado" name="resultado" class="text" onChange="javascript: if(this.value == 'Desistiu' || this.value == 'Concorrente'){ $('#motivo_pre').parent().css('display','inline');}else{ $('#motivo_pre').parent().css('display','none'); $('#motivo_pre').val('');}">
						<option title="Selecione a situação." style="background-color:white; color:#333;" value="">Todos</option>
						<option title="Desistiu de comprar." style="background-color:pink; color:#333;" value="Desistiu">Desistiu</option>
						<option title="Fechou a venda conosco." style="background-color:green; color:white;" value="Fechou">Fechou</option>
						<option title="Comprou do concorrente." style="background-color:red; color:white;" value="Concorrente">Concorrente</option>
						<option title="Este em negociação." style="background-color:yellow; color:#333;" value="Negociação">Negociação</option>
						<option title="Vai fechar." style="background-color:orange; color:#FFF;" value="Vai fechar">Vai fechar</option>
						<option title="Só venda." style="background-color:blue; color:#FFF;" value="Só venda">Só venda</option>
						<option title="Agendadas." style="background-color:#eee; color:#555;" value="Agendado">Agendada</option>
						<option title="Contato duplicado." style="background-color:#000; color:#fff;" value="Duplicado">Duplicado</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	
	<div class="inline" style="display:none;">
		<label class="label">Motivo</label>
		<select title="Selecione o motivo." id="motivo_pre" name="motivo_pre" class="text" onchange="">
			<option value="">Todos</option>
			<?php
			foreach($this->arrMotivos as $motivo){
				echo '<option value="'.$motivo['id'].'">'.$motivo['descricao'].'</option>';
			}
			?>
		</select>
	</div>
	
	<div class="inline" style="width:10%;">
		<label class="label">Filtros</label>
		<select id="filtro" name="filtro" class="text">
			<option value="">Selecione</option>
			<option value="Atrasada">Atrasadas</option>
			<option value="Hoje">Hoje</option>
		</select>
	</div>

	<div class="inline" style="width:20%;">
		<label class="label"></br></label>
		<input type="button" class="btn-small btn-find" onClick="buscaListaFluxo();" value="Pesquisar" />
		<input type="button" class="btn-small-xls" value="Gerar XLS" onclick="geraXls();" />
		<!--<input type="button" class="btn-mini btn-include" value="Adicionar" onclick="javascript:window.location.href='<?php echo URL ?>clientes/add-cliente-fluxo-auto-salvar'" />---->
		<input type="hidden" id="relatorio" name="relatorio" value=""/>
		<input type="hidden" id="tipo_relatorio" name="tipo_relatorio" value="Relatorio Contatos"/>
	</div>
	
</form>

<div id="table"></div>

<script>

	function geraXls(){
		$("form").attr("action","gerar-xls");
		$("form").submit();
		$("form").attr("action","lista");
	}

	function buscaModelo(strMmarca){
	
		$.ajax({
			url : '/modelos/ajax/fn/busca_modelos/marca/'+strMmarca,
			async: true,
			type : 'POST',
			dataType: 'text',
			success: function(data){

				$("#veiculo").html(data);

			}
		});
	
	}

	function buscaMarcas(){
	
		$.ajax({
			url : '/modelos/ajax/fn/busca_marca',
			async: true,
			type : 'POST',
			dataType: 'text',
			success: function(data){
				
				$("#marca").html(data);
				
			}
		});
	
	}


	$(document).ready(function(){
		
		$.ajax({
			url : '/clientes/ajax/fn/busca_origem',
			async: true,
			type : 'POST',
			dataType: 'text',
			success: function(data){
				
				$("#origem").html(data);

			}
		});
		

		$("#data_inicial").mask("99/99/9999");
		$('#data_inicial').focus(function(){
			$(this).calendario({
				target:'#data_inicial'
			});
		});
		
		$("#data_final").mask("99/99/9999");
		$('#data_final').focus(function(){
			$(this).calendario({
				target:'#data_final'
			});
		});

		buscaListaFluxo();

	});
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}else{
			
			$("#data_inicial").val("");
			$("#data_final").val("");
		
		}
	
	}

	function buscaListaFluxo(){

		$("body").prepend('<div id="div_aguarde" style="text-align:center; opacity:0.8; background-color:#000;width:100%; height:1000px; position:fixed; font-size: 30px; color:#fff;"><div style="margin-top:200px;">Atualizando! Aguarde...</div></div>');
	
		$.ajax({
			type: "POST",
			url: '/novos-relatorios/ajax/fn/relatorio_contatos',
			async: true,
			dataType:"text",
			data: ({'nome':$("#nome").val(), 'veiculo':$("#veiculo").val(), 'data_inicial':$("#data_inicial").val(), 'data_final':$("#data_final").val(), 'vendedor':$("#vendedor").val(), 'origem':$("#origem").val(), 'resultado':$("#resultado").val(), 'motivo_pre':$("#motivo_pre").val(), 'filtro':$("#filtro").val()}),
			success:function(resp){
				
				$("#table").html(resp);
				$("#relatorio").val(resp);
				
				buscaMarcas();
				
				$(".resultado_motivo").tipsy({gravity: 'n'});
				
				$("#div_aguarde").fadeOut(500);

			}

		});
	
	}

</script>