<div id="fundo_preto" style="display:none; width:100%; height:100%; background-color:#fff; opacity: 0.70; z-index:3; position:fixed;">
	<div style="width:300px; height:150px; background-color:#FFFFFF; z-index: 4; position:fixed; top:50%; margin-top:-75px; left:50%;margin-left:-150px;">
	Salvando, Aguarde...
	</div>
</div>
<form class="form" action="lista" method="post">
<div class="inline" id="div_mes">
		<label class="label">Mês</label>
		<select class="select" onChange="enviaPeriodo(this.value);" >
			<option value="0">Selecione</option>
			<?php
				
				for($i = @date("m"); $i > (@date("m")-25); $i--){
				
					$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
					$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
					$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
					
					
					
					switch ($mesNum){
						case 1:
							$option =  "Janeiro - ".$anoNum;
							break;
							
						case 2:
							$option =  "Fevereiro - ".$anoNum;
							break;
						
						case 3:
							$option =  "Março - ".$anoNum;
							break;
							
						case 4:
							$option =  "Abril - ".$anoNum;
							break;
							
						case 5:
							$option =  "Maio - ".$anoNum;
							break;
							
						case 6:
							$option =  "Junho - ".$anoNum;
							break;
							
						case 7:
							$option =  "Julho - ".$anoNum;
							break;
							
						case 8:
							$option =  "Agosto - ".$anoNum;
							break;
							
						case 9:
							$option =  "Setembro - ".$anoNum;
							break;
						
						case 10:
							$option =  "Outubro - ".$anoNum;
							break;
							
						case 11:
							$option =  "Novembro - ".$anoNum;
							break;
							
						case 12:
							$option =  "Dezembro - ".$anoNum;
							break;
			
					}
					
					echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
				
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline" id="div_datas">
		<table>
			<tr>
				<td>
					<label class="label">Data Inicial</label>
				</td>
				<td>
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<input type="text" class="text" style="width:90%" name="data_inicial" id="data_inicial" value="<?php echo "01/".@date("m/Y") ?>"/>
				</td>
				<td>
					<input type="text" class="text" style="width:90%" name="data_final" id="data_final" value="<?php echo @date("d", mktime(0, 0, 0, @date("m")+1, 0, @date("Y")))."/".@date("m")."/".@date("Y"); ?>"/>
				</td>
			</tr>
		</table>
	</div>
	
	<div class="inline">
		<br/>
		<input type="button" class="btn-small btn-find" value="Pesquisar" onClick="buscaIndicacoesCaracteristicas();" />
	</div>
	
</form>

<table class="table" id="table_indicacoes">
	
	

</table>

<script type="text/javascript">
	
	function buscaIndicacoesCaracteristicas(){
		
		var arrDataInicial = $("#data_inicial").val().split("/");
		var arrDataFinal = $("#data_final").val().split("/");
		
		$.ajax({
			type: "POST",
			url: '/novos-relatorios/ajax/fn/indicacoes_corretoras_relatorio',
			async: true,
			dataType:"text",
			data: ({"data_inicial": arrDataInicial[2]+"-"+arrDataInicial[1]+"-"+arrDataInicial[0],"data_final": arrDataFinal[2]+"-"+arrDataFinal[1]+"-"+arrDataFinal[0]}),
			success:function(resp){

				$("#table_indicacoes").html(resp);

				$("#table_indicacoes").children().children().children().children().each(function(){
			
					if($(this).get(0).nodeName == "SELECT"){
						
						if($(this).val() == 0){
							
							$(this).css("background-color","#FFFFFF");
							$(this).css("color","#000000");
						
						}
						
						if($(this).val() == 1){
							
							$(this).css("background-color","green");
							$(this).css("color","#FFFFFF");
						
						}
						
						if($(this).val() == 2){
							
							$(this).css("background-color","red");
							$(this).css("color","#FFFFFF");
						
						}
						
						if($(this).val() == 3){
							
							$(this).css("background-color","yellow");
							$(this).css("color","#000000");
						
						}
					
					}
					
				});
				
				
			}
		
		});
	
	}
	
	
	$(function(){
		
		buscaIndicacoesCaracteristicas();

	});
	
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}
	
	}

</script>