<div id="print">
<style>

.table {
	width:99%;
	border-left:1px solid #d4d4d4;
	border-top:1px solid #d4d4d4;
	margin-bottom:15px;
	margin-left:auto;
	margin-right:auto;
	font-family: Arial, Helvetica, sans-serif;
	}
	
	.table tr th, .table tr td {
		padding:5px 10px;
	}
	
	.table tr td img{
		padding-right:10px;
	}
	
	.table tr th {
		background:#a3a3a3;
		color:#FFF;
		text-align:center;
	}
	
	.table tr td {
		border-right:1px solid #d4d4d4;
		border-bottom:1px solid #d4d4d4;
		vertical-align:middle;
	}
	
	.table tr.zebra td {
		background:#F2F2F2;
	}
	
	.table .table-options {
		padding:10px;
	}
	
	.table .table-sub {
		background: #F9F9F9;
		padding:15px;
	}

	.vermelho{
		color:#FF0000;
		background-color: #FFCCCC;
		#border:1px solid #FF0000;
	}
	
	.amarelo{
		background-color: #FFF68F;
		#border:1px solid #EEC900;
	}
	
	.verde{
		color:#005500;
		background-color: #AAFFAA;
		#border:1px solid #005500;
	}
	
	#table_cabeca tr th{
		vertical-align:middle;
		text-align:center;
		border: solid 1px #CCCCCC;
		height: 30px;
		background-color: #AAAAAA;
		color:#FFFFFF;
		font-family: Arial, Helvetica, sans-serif;
		font-size: 11px;
	}
	
	#table_dados td{
		border: solid 1px #DDDDDD;
		height: 18px;
		vertical-align:middle;
		font-family: Arial, Helvetica, sans-serif;
		font-size: 11px;
	}

</style>
<form class="form" action="fechamento" method="post">
	
	<div class="inline" id="div_select">
	<label class="label">Vendedor</label>
	<select name = "id_vendedor" id="id_vendedor" class="select">
		<option value = "0">Todos</option>
		<?php
		foreach($this->vendedores as $vendedor){
		
			if($vendedor['id'] == $this->id_vendedor){
			
				echo "<option selected='selected' value = '".$vendedor['id']."'>".$vendedor['nome']."</option>";
			
			}else{
		
				echo "<option value = '".$vendedor['id']."'>".$vendedor['nome']."</option>";
			
			}
		
		}
		?>
		</select>		
	</div>
	
	<div class="inline" id="div_mes">
		<table width="100%">
			<tr>
				<td>
					<label class="label">Mês</label>
				</td>
				<td>
					<label class="label">Períodos</label>
				</td>
			</tr>
			<tr>
				<td>
					<select class="select" onChange="enviaPeriodo(this.value);" style="width:95%;">
						<option value="0">Selecione</option>
						<?php
							
							for($i = @date("m"); $i > (@date("m")-25); $i--){
							
								$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
								$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
								$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
	
								
								switch ($mesNum){
									case 1:
										$option =  "Janeiro - ".$anoNum;
										break;
										
									case 2:
										$option =  "Fevereiro - ".$anoNum;
										break;
									
									case 3:
										$option =  "Março - ".$anoNum;
										break;
										
									case 4:
										$option =  "Abril - ".$anoNum;
										break;
										
									case 5:
										$option =  "Maio - ".$anoNum;
										break;
										
									case 6:
										$option =  "Junho - ".$anoNum;
										break;
										
									case 7:
										$option =  "Julho - ".$anoNum;
										break;
										
									case 8:
										$option =  "Agosto - ".$anoNum;
										break;
										
									case 9:
										$option =  "Setembro - ".$anoNum;
										break;
									
									case 10:
										$option =  "Outubro - ".$anoNum;
										break;
										
									case 11:
										$option =  "Novembro - ".$anoNum;
										break;
										
									case 12:
										$option =  "Dezembro - ".$anoNum;
										break;
						
								}
								
								echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
							
							}
						
						?>
						
					</select>
				</td>
				<td>
					<select class="select" onChange="enviaPeriodoMaior(this.value);" style="width:95%;">
						<option value="">Selecione</option>
						<option value="12">Últimos 12 meses</option>
						<option value="6">Últimos 6 meses</option>
						<option value="3">Últimos 3 meses</option>
						<option value="1">Ano passado</option>
						<option value="0">Ano atual</option>
					</select>
				</td>
			</tr>
		</table>

	</div>
	
	<div class="inline">
		<table width="100%">
			<tr>
				<td>
					<label class="label">Data Inicial</label>
				</td>
				<td>
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<input type="text" class="text" name="data_inicial" id="data_inicial" style="width:90%;" value="<?php echo $this->data_inicial; ?>"/>
				</td>
				<td>
					<input type="text" class="text" name="data_final" id="data_final" style="width:90%;" value="<?php echo $this->data_final; ?>"/>
				</td> 
			</tr>
		</table>
	</div>
	
	<div class="inline" style="clear:both; width:50%;" id="div_botoes">
		<input type="button" class="btn-small btn-find" value="Pesquisar" onclick="valida();" />
		<input type="button" class="btn-small-xls" value="Gerar XLS" onclick="geraXls();"/>
		<input type="button" class="btn-small-imp" value="Imprimir" onclick="imprimir('print','Teste');"/>
	</div>

</form>
<br>

	<div class="inline" style="clear:both; margin-top:20px; margin-bottom:10px; margin-left:10px; width:40%; height:auto; font-family: Arial, Helvetica, sans-serif;" id="div_num">
		<b><label class="label">N&uacute;mero de Vendas: <span id="num_veiculos"><?php echo count($this->arrNegociacoes); ?></span><span id="dados"></span></label></b>
	</div>

<?php
	$divisorFI=0;
	$count=0;
	$count2=10;
	$qtdVendas = 0;

	$subVenda = 0;
	$subCusto = 0;
	$subCompra = 0;
	$subDespesas = 0;
	$subLucro = 0;
	$subLucroPorcento = 0;

	$somaValorVenda = 0;
	$somaDiasEstoque = 0;
	$somaCusto = 0;
	$somaCompra = 0;
	$somaDespesas = 0;
	$somaLucro = 0;
	$somaLucroPorcento = 0;

	$subFI = 0;
	$tabela = "";
	$strTabela = "";
	$somaFI = 0;
	$somaFIPorcento = 0;
	$somaDiasRevisao = 0;
	$somaValorDespachante = 0;
	$finalDebito = 0;

	$mediaValorVenda = 0;
	$mediaDiasEstoque = 0;
	$mediaCusto = 0;
	$mediaCompra = 0;
	$mediaDespesas = 0;
	$mediaLucro = 0;
	$mediaLucroPorcento = 0;
	$mediaFI = 0;
	$mediaFIPorcento = 0;
	$mediaDiasRevisao = 0;

		foreach($this->arrNegociacoes as $key=>$negociacao){
			
			$count++;
			$qtdVendas++;
			
			if($count2%2 != 0){
			
				$bgCor = "bgColor='#DDDDDD'";
			
			}else{
			
				$bgCor = "";
			
			}
			
			$count2++;
			
			if($negociacao['descricao_site']){
			
				$negociacao['modelo'] = $negociacao['descricao_site'];
			
			}
			
			$dataTmp = explode(" ",$negociacao['data_concretizacao']);
			$dataTmp2 = explode("-",$dataTmp[0]);
			$negociacao['data_concretizacao'] = implode("/",array_reverse($dataTmp2));
			$dataConcretizacao = $negociacao['data_concretizacao'];
			$negociacao['data_concretizacao'] = $negociacao['data_concretizacao'] . " " . $dataTmp[1];
			
			$dataIni = explode("-",$negociacao['data_aquisicao']);
			$timestamp1 = mktime(0,0,0,$dataTmp2[1],$dataTmp2[2],$dataTmp2[0]); 
			$timestamp2 = mktime(0,0,0,$dataIni[1],$dataIni[2],$dataIni[0]);
			$segundos_diferenca = $timestamp1 - $timestamp2;
			$dias_diferenca = ($segundos_diferenca /(60 * 60 * 24));
			
			$dataRev = explode("-",$negociacao['data_termino_revisao']);
			$timesRev = mktime(0,0,0,$dataRev[1],$dataRev[2],$dataRev[0]); 
			$segundos_diferenca_rev = $timesRev - $timestamp2;
			$dias_diferenca_rev = ($segundos_diferenca_rev /(60 * 60 * 24));
			
			
			$statusEstoque = "class=''";
			$statusRevisao = "class=''";
			$statusLucro = "class=''";
			$lucro = $negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']);
			
			if($dias_diferenca <= $this->arrCores['verde_estoque']){
			
				$statusEstoque = "class='verde'";
				
			}elseif($dias_diferenca <= $this->arrCores['amarelo_estoque'] && $dias_diferenca > $this->arrCores['verde_estoque']){
			
				$statusEstoque = "class='amarelo'";
				
			}elseif($dias_diferenca > $this->arrCores['amarelo_estoque']){
			
				$statusEstoque = "class='vermelho'";
				
			}
			
			if($dias_diferenca_rev <= $this->arrCores['verde_revisao']){
			
				$statusRevisao = "class='verde'";
				
			}elseif($dias_diferenca_rev <= $this->arrCores['amarelo_revisao'] && $dias_diferenca_rev > $this->arrCores['verde_revisao']){
			
				$statusRevisao = "class='amarelo'";
				
			}elseif($dias_diferenca_rev > $this->arrCores['amarelo_revisao']){
			
				$statusRevisao = "class='vermelho'";
				
			}
			
			if($lucro <= $this->arrCores['vermelho_lucro']){
			
				$statusLucro = "class='vermelho'";
				
			}elseif($lucro <= $this->arrCores['amarelo_lucro'] && $lucro > $this->arrCores['vermelho_lucro']){
			
				$statusLucro = "class='amarelo'";
				
			}elseif($lucro > $this->arrCores['amarelo_lucro']){
			
				$statusLucro = "class='verde'";
				
			}
			
			if(!isset($this->arrNegociacoes[$key+1]['id_vendedor']) || ($this->arrNegociacoes[$key+1]['id_vendedor'] != $negociacao['id_vendedor'])){
			
				if($this->id_vendedor == 0){
				
					$count += 1;
				
				}
		
				$tabelaCima = "<tr>
					<td id='td_vendedor' rowspan='".$count."'>".substr($negociacao['nomeUsuario'],0,20)."</td>
					<td ".$bgCor." id='td_cliente'>".substr($negociacao['nome'],0,20)."</td>
					<td ".$bgCor." id='td_data_venda'>".$dataConcretizacao."</td>
					<td ".$bgCor." id='td_modelo'>".substr($negociacao['modelo'],0,15)."</td>
					<td ".$bgCor." id='td_origem'>".$negociacao['origem']."</td>
					<td ".$bgCor." id='td_cor'>".$negociacao['cor']."</td>
					<td ".$bgCor." id='td_placa'>".$negociacao['placa']."</td>
					<td ".$bgCor." id='td_ano'>".substr($negociacao['ano_fabricacao'],-2)."/".substr($negociacao['ano_modelo'],-2)."</td>
					<td ".$bgCor." id='td_km'>".$negociacao['km']."</td>
					<td ".$bgCor." id='td_valor_venda'>R$ ".money_format("%i",$negociacao['valor_venda'])."</td>
					<td ".$bgCor." id='td_dias_estoque'".$statusEstoque.">".round($dias_diferenca,0)."</td>
					<td ".$bgCor." id='td_custo'>R$ ".money_format("%i",$negociacao['valor_despesas']+$negociacao['valor_aquisicao'])."</td>
					<td ".$bgCor." id='td_compra'>R$ ".money_format("%i",$negociacao['valor_aquisicao'])."</td>
					<td ".$bgCor." id='td_despesas'>R$ ".money_format("%i",$negociacao['valor_despesas'])."</td>
					<td id='td_lucroR'".$statusLucro.">R$ ".money_format("%i",$negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))."</td>
					<td id='td_lucroP' ".$statusLucro.">".round((($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100),2)."%</td>";
			
				if($negociacao['id_financeira']){
				
					$tabelaCima .= "<td ".$bgCor." id='td_fiR'>R$ ".money_format("%i",((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'])."</td>
								<td  ".$bgCor."id='td_fiP'>".round((((((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'])+($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100),2)."%</td>";
				
				}else{
				
					$tabelaCima .= "<td ".$bgCor." id='td_fiR'>R$ ".money_format("%i",0)."</td>
								<td ".$bgCor." id='td_fiP'>".round(0,2)."%</td>";
				
				}
					
				$tabelaCima .= "<td ".$bgCor." id='td_data_compra'>".$dataIni[2]."/".$dataIni[1]."/".$dataIni[0]."</td>
					<td ".$bgCor." id='td_data_revisao'>".$dataRev[2]."/".$dataRev[1]."/".$dataRev[0]."</td>
					<td ".$bgCor." id='td_dia_revisao'".$statusRevisao.">".round($dias_diferenca_rev,0)."</td>
				</tr>";
				
				
				$subVenda += $negociacao['valor_venda'];
				$subCusto += ($negociacao['valor_despesas']+$negociacao['valor_aquisicao']);
				$subCompra += $negociacao['valor_aquisicao'];
				$subDespesas += $negociacao['valor_despesas'];
				$subLucro += ($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']));
				$subLucroPorcento += (($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100);
				
				if($negociacao['id_financeira']){
				
					$divisorFI++;
					$subFI += ((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'];
			
				}
				
				$strTabela .= $tabelaCima.$tabela;
				
				if($this->id_vendedor == 0){
				
				 $strTabela .= "<tr>
								<td style='text-align:right; height:25px; font-size:12px; background-color:#EEEEEE;' colspan='8'><b>SUBTOTAL</b></td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subVenda)."</td>
								<td style='background-color:#EEEEEE;'></td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subCusto)."</td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subCompra)."</td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subDespesas)."</td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subLucro)."</td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subLucroPorcento)."</td>
								<td style='background-color:#EEEEEE;'>R$ ".money_format("%i",$subFI)."</td>
								<td style='background-color:#EEEEEE;' colspan='4'></td>
							   </tr>";
				}
				
				$tabela = "";
				$count = 0;
				$subVenda = 0;
				$subCusto = 0;
				$subCompra = 0;
				$subDespesas = 0;
				$subLucro = 0;
				$subLucroPorcento = 0;
				$subFI = 0;
		
			}else{
			
				$subVenda += $negociacao['valor_venda'];
				$subCusto += ($negociacao['valor_despesas']+$negociacao['valor_aquisicao']);
				$subCompra += $negociacao['valor_aquisicao'];
				$subDespesas += $negociacao['valor_despesas'];
				$subLucro += ($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']));
				$subLucroPorcento += (($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100);
				
				if($negociacao['id_financeira']){
				
					$divisorFI++;
					$subFI += ((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'];
			
				}
			
				$tabela .= "<tr>
					<td ".$bgCor." >".substr($negociacao['nome'],0,20)."</td>
					<td ".$bgCor." >".$dataConcretizacao."</td>
					<td ".$bgCor." >".substr($negociacao['modelo'],0,15)."</td>
					<td ".$bgCor." >".$negociacao['origem']."</td>
					<td ".$bgCor." >".$negociacao['cor']."</td>
					<td ".$bgCor." >".$negociacao['placa']."</td>
					<td ".$bgCor." >".substr($negociacao['ano_fabricacao'],-2)."/".substr($negociacao['ano_modelo'],-2)."</td>
					<td ".$bgCor." >".$negociacao['km']."</td>
					<td ".$bgCor." >R$ ".money_format("%i",$negociacao['valor_venda'])."</td>
					<td ".$statusEstoque.">".round($dias_diferenca,0)."</td>
					<td ".$bgCor." >R$ ".money_format("%i",$negociacao['valor_despesas']+$negociacao['valor_aquisicao'])."</td>
					<td ".$bgCor." >R$ ".money_format("%i",$negociacao['valor_aquisicao'])."</td>
					<td ".$bgCor." >R$ ".money_format("%i",$negociacao['valor_despesas'])."</td>
					<td ".$statusLucro.">R$ ".money_format("%i",$negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))."</td>
					<td ".$statusLucro.">".round((($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100),2)."%</td>";
			
				if($negociacao['id_financeira']){
				
					$tabela .= "<td ".$bgCor." >R$ ".money_format("%i",((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'])."</td>
								<td ".$bgCor." >".round((((((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'])+($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100),2)."%</td>";
				
				}else{
				
					$tabela .= "<td ".$bgCor." >R$ ".money_format("%i",0)."</td>
								<td ".$bgCor." >".round(0,2)."%</td>";
				
				}
					
				$tabela .= "<td ".$bgCor." >".$dataIni[2]."/".$dataIni[1]."/".$dataIni[0]."</td>
					<td ".$bgCor." >".$dataRev[2]."/".$dataRev[1]."/".$dataRev[0]."</td>
					<td ".$statusRevisao.">".round($dias_diferenca_rev,0)."</td>
				</tr>";
			}
			
			$somaValorVenda += $negociacao['valor_venda'];
			$somaDiasEstoque += $dias_diferenca;
			$somaCusto += ($negociacao['valor_despesas']+$negociacao['valor_aquisicao']);
			$somaCompra += $negociacao['valor_aquisicao'];
			$somaDespesas += $negociacao['valor_despesas'];
			$somaLucro += ($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']));
			$somaLucroPorcento += (($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao']))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100);
			
			if($negociacao['id_financeira']){
				$divisorFI++;
				$somaFI += ((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'];
			
			}
			
			$somaFIPorcento += (((((($negociacao['retorno_financeira']*1.2)*$negociacao['valor_financiado'])/100)-$negociacao['imposto_financeira'])+($negociacao['valor_venda']-($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])))/($negociacao['valor_despesas']+$negociacao['valor_aquisicao'])*100);
			$somaDiasRevisao += $dias_diferenca_rev;
			$somaValorDespachante += $negociacao['imposto'];
			
		}
		
		if($this->arrNegociacoes){
			
			$mediaValorVenda = $somaValorVenda/count($this->arrNegociacoes);
			$mediaDiasEstoque = $somaDiasEstoque/count($this->arrNegociacoes);
			$mediaCusto = $somaCusto/count($this->arrNegociacoes);
			$mediaCompra = $somaCompra/count($this->arrNegociacoes);
			$mediaDespesas = $somaDespesas/count($this->arrNegociacoes);
			$mediaLucro = $somaLucro/count($this->arrNegociacoes);
			$mediaLucroPorcento = $somaLucroPorcento/count($this->arrNegociacoes);
			$mediaFI = $somaFI/$divisorFI;
			$mediaFIPorcento = $somaFIPorcento/count($this->arrNegociacoes);
			$mediaDiasRevisao = $somaDiasRevisao/count($this->arrNegociacoes);
		
		}
		
	$strTabela .= "<tr>
				
				<td style='border:solid 2px; text-align:right;' colspan='9'><b>MÉDIA</b></td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$mediaValorVenda)."</td>
				<td style='border:solid 2px;'>".round($mediaDiasEstoque,0)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$mediaCusto)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$mediaCompra)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$mediaDespesas)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$mediaLucro)."</td>
				<td style='border:solid 2px;'>".round($mediaLucroPorcento,2)."%</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$mediaFI)."</td>
				<td style='border:solid 2px;'>".money_format("%i",$mediaFIPorcento)."%</td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'>".round($mediaDiasRevisao,0)."</td>
			 </tr>";
			 
	$strTabela .= "<tr>
				<td></td>
				<td style='border:solid 2px; text-align:left;'><b> TOTAL DE VENDAS: ".$qtdVendas." </b></td>
				<td style='border:solid 2px; text-align:right;' colspan='7'><b>TOTAL</b></td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$somaValorVenda)."</td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$somaCusto)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$somaCompra)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$somaDespesas)."</td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$somaLucro)."</td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'>R$ ".money_format("%i",$somaFI)."</td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'></td>
				<td style='border:solid 2px;'></td>
			 </tr>
			 </tbody>
			 </table>";
			 
	$strTabela = "<table id='table_dados' style='margin-top:38px; width:1400px;'>".$strTabela;
	
?>	

<div id="div_cabeca" style="height:1px;">
	<table class="" id="table_cabeca" style="height:30px; width:1400px;">
		<tr>
			<th colspan="21" style="color:#FFFFFF; height:20px; border:0px;">
				<div style="margin-top:3px; margin-left:3px; float:left;">
					Para visualizar o fim do relat&oacute;rio passe o mouse sobre o cabe&ccedil;alho da tabela na horizontal.
				</div>
			</th>
		</tr>
		<tr>
			<th id="th_vendedor">Vendedor</th>
			<th id="th_cliente">Cliente</th>
			<th id="th_data_venda">Venda</th>
			<th id="th_modelo">Modelo</th>
			<th id="th_origem">Origem</th>
			<th id="th_cor">Cor</th>
			<th id="th_placa">Placa</th>
			<th id="th_ano">Ano</th>
			<th id="th_km">KM</th>
			<th id="th_valor_venda">Venda</th>
			<th id="th_dias_estoque">Em Est</th>
			<th id="th_custo">Custo</th>
			<th id="th_compra">Compra</th>
			<th id="th_despesas">Despesas</th>
			<th id="th_lucroRP" colspan='2'>Lucro</th>
			<th id="th_fiRP" colspan='2'>F & I</th>
			<th id="th_data_compra">Compra</th>
			<th id="th_data_revisao">Retorno Revis&atilde;o</th>
			<th id="th_dia_revisao">T Re</th>
		</tr>
	</table>
</div>
<br>	

<?php
	echo $strTabela;
?>

<table class="table" style="width:70%;">
	<thead>
		<tr>
			<td colspan="2"><center><label style="font-size:15px;"><b>Resultado Final Total<b></label></center></td>
		</tr>
		<tr>
			<th>Item</th>
			<th>Valor</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td class="verde">Lucro Bruto dos Carros (<?php echo $qtdVendas." veículos vendidos"; ?>)</td>
			<td class="verde">R$ <?php echo money_format("%i",$somaLucro); ?></td>
		</tr>
		<tr>
			<td class="verde">F&I </td>
			<td class="verde">R$ <?php echo money_format("%i",$somaFI); ?></td>
		</tr>
		
		<tr>
			<td class="verde">Despachantes</td>
			<td class="verde">R$ <?php echo money_format("%i",$somaValorDespachante); ?></td>
		</tr>
		
		<?php
			$finalCredito = $somaLucro+$somaFI+$somaValorDespachante;
			$corCreditoDebito = "class='verde'";
			foreach($this->gruposFinanceiros as $chave=>$grupos){
				
				if($grupos['credito_debito'] == 0){
				
					$finalCredito += $grupos['valor_lancamento'];
				
					$corCreditoDebito = "class='verde'";
					
					echo "<tr>
							<td ".$corCreditoDebito.">".$grupos['descricao']."</td>
							<td ".$corCreditoDebito.">R$ ".money_format("%i",$grupos['valor_lancamento'])."</td>
						 </tr>";
					
				}
				
			}	
			
			echo "<tr>
					<td style='border-bottom:solid 1px; border-top:solid 1px; border-left:solid 1px;'".$corCreditoDebito."><b>TOTAL CR&Eacute;DITOS</b></td>
					<td style='border-bottom:solid 1px; border-top:solid 1px; border-right:solid 1px;'".$corCreditoDebito."><b>R$ ".money_format("%i",$finalCredito)."</b></td>
				 </tr>";

			foreach($this->gruposFinanceiros as $chave=>$grupos){
			
				if($grupos['credito_debito'] == 1){
				
					$finalDebito += $grupos['valor_lancamento'];
				
					$corCreditoDebito = "class='vermelho'";
					
					echo "<tr>
							<td ".$corCreditoDebito.">".$grupos['descricao']."</td>
							<td ".$corCreditoDebito.">R$ ".money_format("%i",$grupos['valor_lancamento'])."</td>
						</tr>";
				
				}
				
			}
			
			echo "<tr>
					<td class='vermelho'>Garantias</td>
					<td class='vermelho'>R$ ".money_format("%i",$this->garantia[0]['valor'])."</td>
				</tr>";

			echo "<tr>
					<td class='vermelho'>Folha de Pagamento</td>
					<td class='vermelho'>R$ ".money_format("%i",$this->rsFolhaPagamento)."</td>
				</tr>";

	
			
			$finalDebito += $this->garantia[0]['valor'];
			$finalDebito += $this->rsFolhaPagamento;
			
		?>
		<tr>
			<td class="vermelho" style="border-bottom:solid 1px; border-top:solid 1px; border-left:solid 1px;"><b>TOTAL D&Eacute;BITOS</b></td>
			<td class="vermelho" style="border-bottom:solid 1px; border-top:solid 1px; border-right:solid 1px;"><b>R$ <?php echo money_format("%i",$finalDebito); ?></b></td>
		</tr>
		
		<tr>
			<td style="border-bottom:solid 2px; border-top:solid 2px; border-left:solid 2px;"><b>TOTAL</b></td>
			<td style="border-bottom:solid 2px; border-top:solid 2px; border-right:solid 2px;"><b>R$ <?php echo money_format("%i",$finalCredito-$finalDebito); ?></b></td>
		</tr>
	</tbody>
</table>
<br><br><br><br><br>
<?php
	
	if($this->arrTabelas){
	
		if(count($this->arrTabelas) != 1){
		
			$finals = $this->finals;
		
			while($this->inicial != $finals){

				if($finals == 0){
					
					$finals = 12;
					
				}
			
				if(strlen($finals) == 1){
					
					
					echo $this->arrTabelas["0".$finals]['tabela'];
				
				}else{
					
					echo $this->arrTabelas["".$finals]['tabela'];
				
				}

				$finals--;
			
			}
			
			if(strlen($finals) == 1){
				
				if(isset($this->arrTabelas["0".$finals]['tabela'])){
					echo $this->arrTabelas["0".$finals]['tabela'];
				}
				
			}else{
		
				if(isset($this->arrTabelas["".$finals]['tabela'])){
					echo $this->arrTabelas["".$finals]['tabela'];
				}
				
			}
		
		}
		
		//echo count($this->arrTabelas);
	
	}
?>

</div>
<script type="text/javascript">


	function valida(){
		
		var i = 1;
		mesInicio = $("#data_inicial").val().split("/")[1];
		mesFim = $("#data_final").val().split("/")[1];
		
		anoInicio = $("#data_inicial").val().split("/")[2];
		anoFim = $("#data_final").val().split("/")[2];

		while(mesInicio != mesFim || anoInicio != anoFim){

			mesInicio++;
			
			if(mesInicio >= 13){
				mesInicio = 1;
				anoInicio++;
			}
			
			i++;
		
		}

		if(i >= 13){
			alert("Não é permitido pesquisar poríodos maiores que 12 meses!");
		}else{
			$("form").submit();
		}

	}

var vendedores = new Array();

 vendedores[0] = "Todos";

<?php
	foreach($this->vendedores as $vendedor){
			
		echo "vendedores[".$vendedor['id']."] = '".$vendedor['nome']."';\n";
			
	}
?>

function imprimir(id, pg) {
	
	$("#div_select").css("display","none");
	$("#div_datas").css("display","none");
	$("#div_botoes").css("display","none");
	$("#div_mes").css("display","none");
	
	$("#dados").html("<br>Vendedor: "+vendedores[$("#id_vendedor").val()]+"<br>Data: de "+$("#data_inicial").val()+" até "+$("#data_final").val());
	
	
	$("#th_vendedor").css("width",$("#td_vendedor").width()-8+"px");
	$("#th_cliente").css("width",$("#td_cliente").width()-8+"px");
	$("#th_data_venda").css("width",$("#td_data_venda").width()-5+"px");
	$("#th_modelo").css("width",$("#td_modelo").width()-7+"px");
	$("#th_origem").css("width",$("#td_origem").width()-5+"px");
	$("#th_cor").css("width",$("#td_cor").width()-3+"px");
	$("#th_placa").css("width",$("#td_placa").width()-3+"px");
	$("#th_ano").css("width",$("#td_ano").width()-2+"px");
	$("#th_km").css("width",$("#td_km").width()-2+"px");
	$("#th_valor_venda").css("width",$("#td_valor_venda").width()-5+"px");
	$("#th_dias_estoque").css("width",$("#td_dias_estoque").width()-2+"px");
	$("#th_custo").css("width",$("#td_custo").width()-5+"px");
	$("#th_compra").css("width",$("#td_compra").width()-5+"px");
	$("#th_despesas").css("width",$("#td_despesas").width()-4+"px");
	$("#th_lucroRP").css("width",($("#td_lucroR").width()+$("#td_lucroP").width()));
	$("#th_fiRP").css("width",($("#td_fiR").width()+$("#td_fiP").width()));
	$("#th_data_compra").css("width",$("#td_data_compra").width()-4+"px");
	$("#th_data_revisao").css("width",$("#td_data_revisao").width()-3+"px");
	$("#th_dia_revisao").css("width",$("#td_dia_revisao").width()+"px");
	
	
	var oPrint, oJan;
	oPrint = window.document.getElementById(id).innerHTML;
	oJan = window.open(pg);
	oJan.document.write(oPrint);
	oJan.window.print();
       oJan.document.close();
       oJan.focus();

	$("#div_select").css("display","inline");
	$("#div_datas").css("display","inline");
	$("#div_botoes").css("display","inline");
	$("#div_mes").css("display","inline");
	$("#dados").html("");
	
	$("#th_vendedor").css("width",$("#td_vendedor").width()+"px");
	$("#th_cliente").css("width",$("#td_cliente").width());
	$("#th_data_venda").css("width",$("#td_data_venda").width());
	$("#th_modelo").css("width",$("#td_modelo").width());
	$("#th_origem").css("width",$("#td_origem").width());
	$("#th_cor").css("width",$("#td_cor").width());
	$("#th_placa").css("width",$("#td_placa").width());
	$("#th_ano").css("width",$("#td_ano").width());
	$("#th_km").css("width",$("#td_km").width());
	$("#th_valor_venda").css("width",$("#td_valor_venda").width());
	$("#th_dias_estoque").css("width",$("#td_dias_estoque").width());
	$("#th_custo").css("width",$("#td_custo").width());
	$("#th_compra").css("width",$("#td_compra").width());
	$("#th_despesas").css("width",$("#td_despesas").width());
	$("#th_lucroRP").css("width",($("#td_lucroR").width()+$("#td_lucroP").width()));
	$("#th_fiRP").css("width",($("#td_fiR").width()+$("#td_fiP").width()));
	$("#th_data_compra").css("width",$("#td_data_compra").width());
	$("#th_data_revisao").css("width",$("#td_data_revisao").width());
	$("#th_dia_revisao").css("width",$("#td_dia_revisao").width()+"px");
	
}
	
	//$("#num_veiculos").html(<?php echo $count;?>);
	
	$("#data_inicial").mask("99/99/9999");
	$('#data_inicial').focus(function(){
		$(this).calendario({
			target:'#data_inicial'
		});
	});
	
	$("#data_final").mask("99/99/9999");
	$('#data_final').focus(function(){
		$(this).calendario({
			target:'#data_final'
		});
	});

	function geraXls(){
	
		dataInicial = $("#data_inicial").val();
		dataFinal = $("#data_final").val();
		idVendedor = $("#id_vendedor").val();
		
		if(dataInicial != ""){
			dataI = dataInicial.split("/");
			dataInicial = dataI[2]+"-"+dataI[1]+"-"+dataI[0];
		}
		
		if(dataFinal != ""){
			dataF = dataFinal.split("/");
			dataFinal = dataF[2]+"-"+dataF[1]+"-"+dataF[0];
		}

		window.location.href="/relatorios-mes/relatorio-xls/data_inicial/"+dataInicial+"/data_final/"+dataFinal+"/id_vendedor/"+idVendedor+"/nome_vendedor/"+vendedores[$("#id_vendedor").val()];
		
	}
	
	
	var posicaoLeft;
	var posicaoTop;
	
	$("#content").scroll(function(){

		posicaoLeft = $(this).scrollLeft();
		$('#div_cabeca').css({position:'relative', left:0});

	});
	
	$(document).scroll(function(){

		posicaoTop = $(this).scrollTop();
		
		if(posicaoTop >= 225){

			$('#div_cabeca').css({position:'relative', top:(posicaoTop-225)});
		
		}else{
		
			$('#div_cabeca').css({position:'relative', top:'0px'});
		
		}

	});
	
	$("#div_cabeca").mousemove(function(e){
		
		$("#content").scrollLeft(e.pageX-600);
	
	});
	
	$("#th_vendedor").css("width",$("#td_vendedor").width()+"px");
	$("#th_cliente").css("width",$("#td_cliente").width());
	$("#th_data_venda").css("width",$("#td_data_venda").width());
	$("#th_modelo").css("width",$("#td_modelo").width());
	$("#th_origem").css("width",$("#td_origem").width());
	$("#th_cor").css("width",$("#td_cor").width());
	$("#th_placa").css("width",$("#td_placa").width());
	$("#th_ano").css("width",$("#td_ano").width());
	$("#th_km").css("width",$("#td_km").width());
	$("#th_valor_venda").css("width",$("#td_valor_venda").width());
	$("#th_dias_estoque").css("width",$("#td_dias_estoque").width());
	$("#th_custo").css("width",$("#td_custo").width());
	$("#th_compra").css("width",$("#td_compra").width());
	$("#th_despesas").css("width",$("#td_despesas").width());
	$("#th_lucroRP").css("width",($("#td_lucroR").width()+$("#td_lucroP").width()));
	$("#th_fiRP").css("width",($("#td_fiR").width()+$("#td_fiP").width()));
	$("#th_data_compra").css("width",$("#td_data_compra").width());
	$("#th_data_revisao").css("width",$("#td_data_revisao").width());
	$("#th_dia_revisao").css("width",$("#td_dia_revisao").width()+"px");
	
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}
	
	}
	
	
	function enviaPeriodoMaior(valor){

		if(valor == "1"){		
			var dataInicial = '01/01/<?php echo  @date("Y")-1; ?>';
			var datafinal = '31/12/<?php echo  @date("Y")-1; ?>';	
		}
		
		if(valor == "0"){		
			var dataInicial = '01/01/<?php echo  @date("Y"); ?>';
			var datafinal = '31/12/<?php echo @date("Y"); ?>';	
		}
		
		if(valor == "3"){		
			var dataInicial = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")-2, 01, @date("Y")));?>';
			var datafinal = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")+1, 0, @date("Y"))); ?>';	
		}
		
		if(valor == "6"){		
			var dataInicial = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")-5, 01, @date("Y")));?>';
			var datafinal = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")+1, 0, @date("Y"))); ?>';	
		}
		
		if(valor == "12"){		
			var dataInicial = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")-11, 01, @date("Y")));?>';
			var datafinal = '<?php echo @date("d/m/Y", mktime(0, 0, 0, @date("m")+1, 0, @date("Y"))); ?>';	
		}

		$("#data_inicial").val(dataInicial);
		$("#data_final").val(datafinal);
		
	
	
	}
	
	
</script>
