<script type="text/javascript" src="https://www.gstatic.com/charts/loader.js"></script>
<style>	
	.graficos tr td{
		border-bottom:solid 1px #ccc;
	}
</style>
<form class="form" action="lista" method="post">

	<div class="inline">
		<label class="label">Nome</label>
		<input type="text" id="nome" name="nome" class="text" value="" />
	</div>
	
	<?php
	if($_SESSION['sessionUser']['id_perfil'] == 2 || $_SESSION['sessionUser']['id_perfil'] == 4 || $_SESSION['sessionUser']['id_perfil'] == 9){
	?>
	<div class="inline">
		<label class="label">Vendedor</label>
		<select id="vendedor" name="vendedor" class="text">
			<option value="">Todos</option>
			<?php echo $this->strVendedores; ?>
		</select>
	</div>
	<?php
	}
	?>

	<div class="inline" id="div_datas">
		<table>
			<tr>
				<td style="width:40%;">
					<label class="label">M&ecirc;s</label>
				</td>
				<td style="width:30%;">
					<label class="label">Data Inicial</label>
				</td>
				<td style="width:30%;">
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<select class="select" style="width:90%;" onChange="enviaPeriodo(this.value);" >
						<option value="0">Selecione</option>
						<?php

							for($i = @date("m"); $i > (@date("m")-25); $i--){
							
								$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
								$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
								$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
								
								if($mesNum == @date("m") && $anoNum == @date("Y")){
									
									$sel = "selected='selected'";
								
								}else{
									
									$sel = "";
								
								}
								
								switch ($mesNum){
									case 1:
										$option =  "Janeiro - ".$anoNum;
										break;
										
									case 2:
										$option =  "Fevereiro - ".$anoNum;
										break;
									
									case 3:
										$option =  "Mar&ccedil;o - ".$anoNum;
										break;
										
									case 4:
										$option =  "Abril - ".$anoNum;
										break;
										
									case 5:
										$option =  "Maio - ".$anoNum;
										break;
										
									case 6:
										$option =  "Junho - ".$anoNum;
										break;
										
									case 7:
										$option =  "Julho - ".$anoNum;
										break;
										
									case 8:
										$option =  "Agosto - ".$anoNum;
										break;
										
									case 9:
										$option =  "Setembro - ".$anoNum;
										break;
									
									case 10:
										$option =  "Outubro - ".$anoNum;
										break;
										
									case 11:
										$option =  "Novembro - ".$anoNum;
										break;
										
									case 12:
										$option =  "Dezembro - ".$anoNum;
										break;
						
								}
								
								echo "<option ".$sel." value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
							
							}
						
						?>
						
					</select>
				</td>
				<td>
					<input type="text" style="width:90%;" class="text" name="data_inicial" id="data_inicial" value="<?php echo "01/".@date("m")."/".@date("Y");  ?>"/>
				</td>
				<td>
					<input type="text" style="width:90%;" class="text" name="data_final" id="data_final" value="<?php echo @date("d", mktime(0, 0, 0, @date("m")+1, 0, @date("Y")))."/".@date("m")."/".@date("Y"); ?>"/>
				</td>
			</tr>
		</table>
	</div>

	<div class="inline">
		<table width="100%">
			<tr>
				<td width="50%">
					<label class="label">Marca</label>
				</td>
				<td>
					<label class="label">Modelo</label>
				</td>
			</tr>
			<tr>
				<td>
					<select id="marca" name="marca" class="text" onChange="buscaModelo(this.value, 1);">
						<option>Selecione</option>
					</select>
				</td>
				<td>
					<select id="veiculo" name="veiculo" class="text">
						<option value="">Selecione</option>
					</select>
				</td>
			</tr>
		</table>
		
	</div>
	
	<div class="inline">
		<table width="100%">
			<tr>
				<td width="50%">
					<label class="label" id="origem_sites_label">Origem Sites</label>
				</td>
				<td>
					<label class="label" id="origem_label">Origem</label>
				</td>
			</tr>
			<tr>
				<td>
					<select title="Selecione o site de origem dos contatos." id="origem_sites" name="origem_sites" class="text" onChange="javascript: if(this.value != ''){ $('#origem').attr('disabled','true'); $('#origem').val(''); $('#origem').css('background-color','#ccc'); }else{ $('#origem').removeAttr('disabled'); $('#origem').val(''); $('#origem').css('background-color','#fff'); }">
						<option value="">Todos</option>
						<option value="Comprecar">Comprecar</option>
						<option value="Facebook">Facebook</option>
						<option value="Icarros">Icarros</option>
						<option value="Mercado Livre">Mercado Livre</option>
						<option value="Meu Car">Meu Car</option>
						<option value="Meu Carro Novo">Meu Carro Novo</option>
						<option value="Olx">Olx</option>
						<option value="Site Loja">Site Loja</option>
						<option value="Webmotors">Webmotors</option>
					</select>
				</td>
				<td>
					<select id="origem" name="origem" class="text" onChange="javascript: if(this.value != ''){ $('#origem_sites').attr('disabled','true'); $('#origem_sites').val(''); $('#origem_sites').css('background-color','#ccc'); }else{ $('#origem_sites').removeAttr('disabled'); $('#origem_sites').val(''); $('#origem_sites').css('background-color','#fff');}">
						<option>Todos</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	
	<div class="inline">
		<table width="100%">
			<tr>
				<td width="50%">
					<label class="label">Filtros</label>
				</td>
				<td>
					<label class="label">Resultado</label>
				</td>
			</tr>
			<tr>
				<td>
					<select id="filtro" name="filtro" class="text">
						<option value="">Selecione</option>
						<option value="Atrasada">Atrasadas</option>
						<option value="Hoje">Hoje</option>
					</select>
				</td>
				<td>
					<select title="Selecione a situação." id="resultado" name="resultado" class="text" onChange="javascript: if(this.value == 'Desistiu' || this.value == 'Concorrente'){ $('#motivo_pre').parent().css('display','inline');}else{ $('#motivo_pre').parent().css('display','none'); $('#motivo_pre').val('');}">
						<option title="Selecione a situação." style="background-color:white; color:#333;" value="">Todos</option>
						<option title="Desistiu de comprar." style="background-color:pink; color:#333;" value="Desistiu">Desistiu</option>
						<option title="Fechou a venda conosco." style="background-color:green; color:white;" value="Fechou">Fechou</option>
						<option title="Comprou do concorrente." style="background-color:red; color:white;" value="Concorrente">Concorrente</option>
						<option title="Este em negociação." style="background-color:yellow; color:#333;" value="Negociação">Negociação</option>
						<option title="Vai fechar." style="background-color:orange; color:#FFF;" value="Vai fechar">Vai fechar</option>
						<option title="Só venda." style="background-color:blue; color:#FFF;" value="Só venda">Só venda</option>
						<option title="Agendadas." style="background-color:#eee; color:#555;" value="Agendado">Agendada</option>
						<option title="Contato duplicado." style="background-color:#000; color:#fff;" value="Duplicado">Duplicado</option>
					</select>
				</td>
			</tr>
		</table>
	</div>
	
	<div class="inline" style="display:none;">
		<label class="label">Motivo</label>
		<select title="Selecione o motivo." id="motivo_pre" name="motivo_pre" class="text" onchange="">
			<option value="">Todos</option>
			<?php
			foreach($this->arrMotivos as $motivo){
				echo '<option value="'.$motivo['id'].'">'.$motivo['descricao'].'</option>';
			}
			?>
		</select>
	</div>

	<div class="inline" style="width:20%;">
		<label class="label"></br></label>
		<input type="button" class="btn-small btn-find" onClick="buscaListaFluxo();" value="Pesquisar" />
		<input type="button" id="id_tresD" class="btn-small" value="2D" title="Altera os gráficos para 3D ou 2D." onclick="javascript: tresD = !tresD; google.charts.setOnLoadCallback(vendedores);" />
		<input type="button" id="id_tresD" class="btn-small" value="Leg" title="Exibe ou não a legenda dos gráficos." onclick="javascript: if(legenda == 'none'){legenda = 'right';}else{legenda = 'none';} google.charts.setOnLoadCallback(vendedores);" />
	</div>
	
</form>

<div id="table"></div>


<br/>
<br/>
<div id="erro" style="display:none; margin-left:10px; color:red; font-size:15px;">Não há dados para serem exibidos com as características buscada.</div>	
<table width="99%" class="graficos" id="graficos">
	<tr>
		<td width="50%" style="border-top:solid 1px #ccc;">
			<div id="vendedores" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	
		<td width="50%" style="border-top:solid 1px #ccc;">
			<div id="origens" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	</tr>
	<tr>
		<td width="50%">
			<div id="resultados" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	
		<td width="50%">
			<div id="forma_de_contato" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	</tr>
	<tr>
		<td width="50%">
			<div id="veiculo_grafico" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	
		<td width="50%">
			<div id="sites_anuncios" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	</tr>
</table>
<br/>
<br/>
<table width="99%" class="graficos" id="graficos_geral">
	<tr>
		<td width="100%">
			<div id="contatos_por_dia" style="width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<div id="contatos_por_vendedores" style="margin-top:50px; width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	</tr>
	<tr>
		<td width="100%">
			<div id="contatos_por_vendedores_fechados" style="margin-top:50px; width: 100%; height: 500px; position:relative; z-index:1"></div>
		</td>
	</tr>
</table>
<br/>
<br/>
<table class="table" id="table_fluxo"></table>

<script>

	var arrDadosGraficos = new Array();
	var objResp;
	var tresD = true;
	var legenda = '';
	
	function buscaModelo(strMmarca){
	
		$.ajax({
			url : '/modelos/ajax/fn/busca_modelos/marca/'+strMmarca,
			async: true,
			type : 'POST',
			dataType: 'text',
			success: function(data){

				$("#veiculo").html(data);

			}
		});
	
	}

	function buscaMarcas(){
	
		$.ajax({
			url : '/modelos/ajax/fn/busca_marca',
			async: true,
			type : 'POST',
			dataType: 'text',
			success: function(data){
				
				$("#marca").html(data);
				
			}
		});
	
	}


	$(document).ready(function(){
		
		$.ajax({
			url : '/clientes/ajax/fn/busca_origem',
			async: true,
			type : 'POST',
			dataType: 'text',
			success: function(data){
				
				$("#origem").html(data);

			}
		});
		

		$("#data_inicial").mask("99/99/9999");
		$('#data_inicial').focus(function(){
			$(this).calendario({
				target:'#data_inicial'
			});
		});
		
		$("#data_final").mask("99/99/9999");
		$('#data_final').focus(function(){
			$(this).calendario({
				target:'#data_final'
			});
		});

		
		google.charts.load('current', {'packages':['corechart']});
		google.charts.load('current', {'packages':['bar']});
		
		buscaListaFluxo();

	});
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}else{
			
			$("#data_inicial").val("");
			$("#data_final").val("");
		
		}
	
	}

	function buscaListaFluxo(){


		$("body").prepend('<div id="div_aguarde" style="text-align:center; opacity:0.8; background-color:#000;width:100%; height:1000px; position:fixed; font-size: 30px; color:#fff; z-index:10;"><div style="margin-top:200px;">Atualizando! Aguarde...</div></div>');
	
		$.ajax({
			type: "POST",
			url: '/novos-relatorios/ajax/fn/relatorio_fluxo_clientes',
			async: true,
			dataType:"text",
			data: ({'nome':$("#nome").val(), 'veiculo':$("#veiculo").val(), 'data_inicial':$("#data_inicial").val(), 'data_final':$("#data_final").val(), 'vendedor':$("#vendedor").val(), 'origem':$("#origem").val(), 'resultado':$("#resultado").val(), 'motivo_pre':$("#motivo_pre").val(), 'filtro':$("#filtro").val(), 'origem_sites':$("#origem_sites").val()}),
			success:function(resp){
				
				$("#table").html(resp);
				
				$("#table_fluxo").html($("#fluxo").html());
				$("#fluxo").remove();

				buscaMarcas();
				
				$(".resultado_motivo").tipsy({gravity: 'n'});
				
				//$("#div_aguarde").fadeOut(500);

			}

		});

		$.ajax({
			type: "POST",
			url: '/graficos/ajax/fn/contatos',
			async: true,
			dataType:"json",
			data: ({'nome':$("#nome").val(), 'veiculo':$("#veiculo").val(), 'data_inicial':$("#data_inicial").val(), 'data_final':$("#data_final").val(), 'vendedor':$("#vendedor").val(), 'origem':$("#origem").val(), 'resultado':$("#resultado").val(), 'motivo_pre':$("#motivo_pre").val(), 'filtro':$("#filtro").val(), 'origem_sites':$("#origem_sites").val()}),
			success:function(resp){
				console.log(resp);
				if(JSON.stringify(resp[0]) != '"erro"'){
					objResp = resp;

					$("#erro").css("display","none");
					$("#graficos").css("display","table");

					google.charts.setOnLoadCallback(vendedores);
					
				}else{
					$("#erro").css("display","inline");
					$("#graficos").css("display","none");
				}
				//$("#div_aguarde").fadeOut(500);
			}

		});
		
		$.ajax({
			type: "POST",
			url: '/graficos/ajax/fn/contatos_geral',
			async: true,
			dataType:"text",
			data: ({'nome':$("#nome").val(), 'veiculo':$("#veiculo").val(), 'data_inicial':$("#data_inicial").val(), 'data_final':$("#data_final").val(), 'vendedor':$("#vendedor").val(), 'origem':$("#origem").val(), 'resultado':$("#resultado").val(), 'motivo_pre':$("#motivo_pre").val(), 'filtro':$("#filtro").val()}),
			success:function(resp){
				//console.log(resp);
				arrTudo = resp.split("|");
				$("#div_aguarde").fadeOut(500);
				google.charts.setOnLoadCallback(contatosData);
			}

		});
	
	}
	
	function vendedores(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Nome');
		data.addColumn('number', 'Contatos');

		var str = JSON.stringify(objResp[0]).replace("{","");
		str = str.replace("}","");
		
		var arr = str.split(",");
		var arrTemp;
		
		for(x in arr){
			arrTemp = arr[x].split(":");
			data.addRow([acents(arrTemp[0]),parseInt(arrTemp[1])]);
			
		}

        var options = {
			title: 'Vendedores',
			legend:legenda,
			is3D: tresD
        };

        var chart = new google.visualization.PieChart(document.getElementById('vendedores'));

        chart.draw(data, options);
		
		if(tresD){
			$("#id_tresD").val("3D");
		}else{
			$("#id_tresD").val("2D");
		}
		
		google.charts.setOnLoadCallback(origem);

    }

	function origem(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Origem');
		data.addColumn('number', 'Qtd');

		var str = JSON.stringify(objResp[1]).replace("{","");
		str = str.replace("}","");
		
		var arr = str.split(",");
		var arrTemp;
		
		for(x in arr){
			arrTemp = arr[x].split(":");
			data.addRow([acents(arrTemp[0]),parseInt(arrTemp[1])]);
			
		}

        var options = {
			title: 'Origens',
			legend:legenda,
			is3D: tresD,
        };

        var chart = new google.visualization.PieChart(document.getElementById('origens'));

        chart.draw(data, options);
		
		google.charts.setOnLoadCallback(resultado);

    }
	
	function resultado(){

		if(JSON.stringify(objResp[6]).length > 2){
			var titulo = "Motivo";
			var arr = objResp[6];
		}else{
			var titulo = "Resultado";
			var arr = objResp[2];
		}
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Resultado');
		data.addColumn('number', 'Qtd');

		var str = JSON.stringify(arr).replace("{","");
		str = str.replace("}","");
		
		var arr = str.split(",");
		var arrTemp;
		
		for(x in arr){
			arrTemp = arr[x].split(":");
			data.addRow([acents(arrTemp[0]),parseInt(arrTemp[1])]);
			
		}

        var options = {
			title: titulo,
			legend:legenda,
			is3D: tresD,
        };

        var chart = new google.visualization.PieChart(document.getElementById('resultados'));

        chart.draw(data, options);
		
		google.charts.setOnLoadCallback(formaContato);

    }
	
	function formaContato(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Contatos');
		data.addColumn('number', 'Qtd');

		var str = JSON.stringify(objResp[3]).replace("{","");
		str = str.replace("}","");
		
		var arr = str.split(",");
		var arrTemp;
		
		for(x in arr){
			arrTemp = arr[x].split(":");
			data.addRow([acents(arrTemp[0]),parseInt(arrTemp[1])]);
			
		}

        var options = {
			title: 'Forma de Contato',
			legend:legenda,
			is3D: tresD,
        };

        var chart = new google.visualization.PieChart(document.getElementById('forma_de_contato'));

        chart.draw(data, options);
		
		google.charts.setOnLoadCallback(veiculos);

    }
	
	function veiculos(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Modelo');
		data.addColumn('number', 'Qtd');

		var str = JSON.stringify(objResp[4]).replace("{","");
		str = str.replace("}","");
		
		var arr = str.split(",");
		var arrTemp;
		
		for(x in arr){
			arrTemp = arr[x].split(":");
			data.addRow([acents(arrTemp[0]),parseInt(arrTemp[1])]);
			
		}

        var options = {
			title: 'Veículos',
			legend:legenda,
			is3D: tresD,
        };

        var chart = new google.visualization.PieChart(document.getElementById('veiculo_grafico'));

        chart.draw(data, options);
		
		google.charts.setOnLoadCallback(sitesAnuncios);

    }
	
	function sitesAnuncios(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string', 'Sites');
		data.addColumn('number', 'Qtd');

		var str = JSON.stringify(objResp[5]).replace("{","");
		str = str.replace("}","");
		
		var arr = str.split(",");
		var arrTemp;
		
		for(x in arr){
			arrTemp = arr[x].split(":");
			data.addRow([acents(arrTemp[0]),parseInt(arrTemp[1])]);
			
		}

        var options = {
			title: 'Sites de Anúncios',
			legend:legenda,
			is3D: tresD,
        };

        var chart = new google.visualization.PieChart(document.getElementById('sites_anuncios'));

        chart.draw(data, options);

    }

	function acents(string){
		
		string = string.replace('"','').replace('"','').replace('"','').replace('&atilde;','ã').replace('&atilde;','ã').replace('&otilde;','õ').replace('&otilde;','õ');
		string = string.replace('&ccedil;','ç').replace('&aacute;','á').replace('&eacute;','é').replace('&iacute;','í').replace('&oacute;','ó').replace('&uacute;','ú');
		string = string.replace('&ccedil;','ç').replace('&aacute;','á').replace('&eacute;','é').replace('&iacute;','í').replace('&oacute;','ó').replace('&uacute;','ú');
		string = string.replace('&acirc;','â').replace('&ecirc;','ê');
		string = string.replace('&acirc;','â').replace('&ecirc;','ê');
		
		return string;
		
	}
	
	function contatosData() {
		
		var data = new google.visualization.DataTable();
		data.addColumn('string');
		data.addColumn('number', 'Novos');
		data.addColumn('number', 'Respondidos');
		data.addColumn('number', 'Visualizados');
		
		var arr = arrTudo[0].split(":");
		
		for(x in arr){
			arrTemp = arr[x].split(",");
			data.addRow([arrTemp[0],parseInt(arrTemp[1]),parseInt(arrTemp[2]),parseInt(arrTemp[3])]);
		}

        var options = {
			legend: { position: legenda },
			hAxis:{
				textStyle:{fontSize:10}
			},
			vAxis:{
				textStyle:{fontSize:10}
			},
			chart: {
				title: ' Contatos',
				subtitle: ' Total de contatos novos, respondidos e visualizados por dia',
			},
			colors:['#008000','#000080','orange'],
			is3D: tresD
        };

        var chart = new google.charts.Bar(document.getElementById('contatos_por_dia'));

        chart.draw(data, google.charts.Bar.convertOptions(options));

		google.charts.setOnLoadCallback(contatosVendedor);
		
    }
	
	function contatosVendedor(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string');
		data.addColumn('number', 'Novos');
		data.addColumn('number', 'Respondidos');
		data.addColumn('number', 'Visualizados');
		
		var arr = arrTudo[1].split(":");
		
		for(x in arr){
			arrTemp = arr[x].split(",");
			data.addRow([arrTemp[0],parseInt(arrTemp[1]),parseInt(arrTemp[2]),parseInt(arrTemp[3])]);
		}

        var options = {
			legend: { position: legenda },
			hAxis:{
				textStyle:{fontSize:12}
			},
			vAxis:{
				textStyle:{fontSize:10}
			},
			chart: {
				title: ' Contatos por vendedor',
				subtitle: ' Total de contatos novos, respondidos e visualizados por vendedor',
			},
			colors:['#008000','#000080','orange'],
			is3D: tresD
        };

        var chart = new google.charts.Bar(document.getElementById('contatos_por_vendedores'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
		
		google.charts.setOnLoadCallback(contatosVendedorFechado);
		
    }
	
	
	function contatosVendedorFechado(){
		
		var data = new google.visualization.DataTable();
		data.addColumn('string');
		data.addColumn('number', 'Contatos');
		data.addColumn('number', 'Fechados');
		
		var arr = arrTudo[2].split(":");
		
		for(x in arr){
			arrTemp = arr[x].split(",");
			data.addRow([arrTemp[0],parseInt(arrTemp[1]),parseInt(arrTemp[2])]);
		}

        var options = {
			legend: { position: legenda },
			hAxis:{
				textStyle:{fontSize:12}
			},
			vAxis:{
				textStyle:{fontSize:10}
			},
			chart: {
				title: ' Fechados por vendedor',
				subtitle: ' Total de contatos novos e fechados por vendedor',
			},
			colors:['#000080','#008000'],
			is3D: tresD
        };

        var chart = new google.charts.Bar(document.getElementById('contatos_por_vendedores_fechados'));

        chart.draw(data, google.charts.Bar.convertOptions(options));
		
    }

</script>