<form class="form" action="lista" method="post">

	<div class="inline">
		<label class="label">Origem</label>
		<select class="select" id="origem" name="origem">
			<option value="">Todas</option>
		</select>
	</div>

	<div class="inline" id="div_mes">
		<label class="label">M&ecirc;s</label>
		<select class="select" onChange="enviaPeriodo(this.value);" >
			<option value="0">Selecione</option>
			<?php
				$select = true;
				for($i = @date("m"); $i > (@date("m")-25); $i--){
				
					$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
					$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
					$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));

					switch ($mesNum){
						case 1:
							$option =  "Janeiro - ".$anoNum;
							break;
							
						case 2:
							$option =  "Fevereiro - ".$anoNum;
							break;
						
						case 3:
							$option =  "Mar&ccedil;o - ".$anoNum;
							break;
							
						case 4:
							$option =  "Abril - ".$anoNum;
							break;
							
						case 5:
							$option =  "Maio - ".$anoNum;
							break;
							
						case 6:
							$option =  "Junho - ".$anoNum;
							break;
							
						case 7:
							$option =  "Julho - ".$anoNum;
							break;
							
						case 8:
							$option =  "Agosto - ".$anoNum;
							break;
							
						case 9:
							$option =  "Setembro - ".$anoNum;
							break;
						
						case 10:
							$option =  "Outubro - ".$anoNum;
							break;
							
						case 11:
							$option =  "Novembro - ".$anoNum;
							break;
							
						case 12:
							$option =  "Dezembro - ".$anoNum;
							break;
			
					}
					
					if($select){
					
						echo "<option selected='selected' value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
						$dataInicios = $ultimoDia."_".$mesNum."_".$anoNum;
						$select = false;
						
					}else{
						
						echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
					
					}
				
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline" id="div_datas">
		<table>
			<tr>
				<td>
					<label class="label">Data Inicial</label>
				</td>
				<td>
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<input type="text" class="text" style="width:90%" name="data_inicial" id="data_inicial" value="<?php echo $this->data_inicial; ?>"/>
				</td>
				<td>
					<input type="text" class="text" style="width:90%" name="data_final" id="data_final" value="<?php echo $this->data_final; ?>"/>
				</td>
			</tr>
		</table>
	</div>

	<div class="inline" style="clear:both">
		<input type="button" class="btn-small btn-find" onClick="buscaOrigens();" value="Pesquisar" />
		<input type="button" class="btn-small-xls" onClick="geraXls();" value="Gerar XLS" />
	</div>
	
</form>

<div id="relatorio">

</div>

<script>
	
	
	function geraXls(){
	
		dataInicial = $("#data_inicial").val();
		dataFinal = $("#data_final").val();
		idOrigem = $("#origem").val();
		
		if(dataInicial != ""){
			dataI = dataInicial.split("/");
			dataInicial = dataI[2]+"-"+dataI[1]+"-"+dataI[0];
		}
		
		if(dataFinal != ""){
			dataF = dataFinal.split("/");
			dataFinal = dataF[2]+"-"+dataF[1]+"-"+dataF[0];
		}

		window.location.href="/novos-relatorios/gerar-xls-origem/data_inicial/"+dataInicial+"/data_final/"+dataFinal+"/id_origem/"+idOrigem+"/xls/1";

	}
	
	function buscaOrigens(){
	
		$.ajax({
			url : '/novos-relatorios/ajax/fn/origem_clientes',
			async: true,
			type : 'POST',
			dataType: 'text',
			data: ({'origem':$("#origem").val(), 'data_inicial':$("#data_inicial").val(), 'data_final':$("#data_final").val()}),
			success: function(data){

				$("#relatorio").html(data);
				
			}
		});
	
	}
	
	$.ajax({
		url : '/clientes/ajax/fn/busca_origem',
		async: true,
		type : 'POST',
		dataType: 'text',
		success: function(data){
			
			$("#origem").html(data);
			
		}
	});
	
	
	$("#data_inicial").mask("99/99/9999");
	$('#data_inicial').focus(function(){
		$(this).calendario({
			target:'#data_inicial'
		});
	});
	
	$("#data_final").mask("99/99/9999");
	$('#data_final').focus(function(){
		$(this).calendario({
			target:'#data_final'
		});
	});

	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}else{
			
			$("#data_inicial").val("");
			$("#data_final").val("");
		
		}
	
	}
	
	
	enviaPeriodo('<?php echo $dataInicios; ?>');
	
	buscaOrigens();

</script>