<form class="form" action="financiamentos" method="post" id="form">
	
	<div class="inline" id="div_select">
		<label class="label">Vendedor</label>
		<select name = "id_usuario" id="id_usuario" class="select">
			<option value = "0">Todos</option>
			<?php
			foreach($this->arrUsuarios as $usuario){

				echo "<option value = '".$usuario['id']."'>".$usuario['nome']."</option>";

			}
			?>
		</select>		
	</div>

	<div class="inline" id="div_mes">
		<label class="label">Mês</label>
		<select class="select" onChange="enviaPeriodo(this.value);" >
			<option value="0">Selecione</option>
			<?php
				
				for($i = @date("m"); $i > (@date("m")-25); $i--){
				
					$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
					$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
					$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
					
					
					
					switch ($mesNum){
						case 1:
							$option =  "Janeiro - ".$anoNum;
							break;
							
						case 2:
							$option =  "Fevereiro - ".$anoNum;
							break;
						
						case 3:
							$option =  "Março - ".$anoNum;
							break;
							
						case 4:
							$option =  "Abril - ".$anoNum;
							break;
							
						case 5:
							$option =  "Maio - ".$anoNum;
							break;
							
						case 6:
							$option =  "Junho - ".$anoNum;
							break;
							
						case 7:
							$option =  "Julho - ".$anoNum;
							break;
							
						case 8:
							$option =  "Agosto - ".$anoNum;
							break;
							
						case 9:
							$option =  "Setembro - ".$anoNum;
							break;
						
						case 10:
							$option =  "Outubro - ".$anoNum;
							break;
							
						case 11:
							$option =  "Novembro - ".$anoNum;
							break;
							
						case 12:
							$option =  "Dezembro - ".$anoNum;
							break;
			
					}
					
					echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
				
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline" id="div_datas">
		<table style="border: solid 0px;">
			<tr>
				<td style="border: solid 0px; padding:0px;">
					<label class="label">Data Inicial</label>
				</td>
				<td style="border: solid 0px; padding:0px;">
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td style="border: solid 0px; padding:0px;">
					<input type="text" class="text" style="width:90%" name="data_inicial" id="data_inicial" value="<?php echo $this->dataInicial; ?>"/>
				</td>
				<td style="border: solid 0px; padding:0px;">
					<input type="text" class="text" style="width:90%" name="data_final" id="data_final" value="<?php echo $this->dataFinal; ?>"/>
				</td>
			</tr>
		</table>
	</div>
	<div class="inline" id="div_select">
		<label class="label">Loja</label>
		<select name="loja" id="loja" class="select">
			<option value="">Todas</option>
			<option value="Vila Lacerda">Vila Lacerda</option>
			<option value="Vila Arens II">Vila Arens II</option>
			<option>-----------------------------------------------------------------------------------</option>
			<option value="nao">Não visitou as lojas</option>
		</select>		
	</div>
	
	<div class="inline" id="div_select">
		<label class="label">Dispositivo</label>
		<select name="dispositivo" id="dispositivo" class="select">
			<option value="">Todas</option>
			<option value="Computador">Computador</option>
			<option value="Mobile">Mobile</option>
		</select>		
	</div>

	<div class="inline" style="clear:both">
		<input type="button" class="btn-small btn-find" value="Pesquisar" onclick="buscaPesquisa();"/>
	</div>
</form>

<div id="pesquisa">
	
</div>

<script>

	function buscaPesquisa(){

		$("#pesquisa").html("<center>Carregando.....</center>");

		var usuario = $("#id_usuario").val();
		var loja = $("#loja").val();
		var dispositivo = $("#dispositivo").val();
		var dataInicial = $("#data_inicial").val();
		var dataFinal = $("#data_final").val();

		$.ajax({
			type: "POST",
			url: '/novos-relatorios/ajax/fn/pesquisa_satisfacao',
			async: true,
			dataType:"text",
			data: ({'data_inicial':dataInicial, 'data_final':dataFinal, 'loja':loja, 'id_usuario':usuario, 'dispositivo':dispositivo}),
			success:function(resp){

				$("#pesquisa").html(resp);

			}
		});
	
	}
	
	buscaPesquisa();


	$("#data_inicial").mask("99/99/9999");
	$('#data_inicial').focus(function(){
		$(this).calendario({
			target:'#data_inicial'
		});
	});
	
	$("#data_final").mask("99/99/9999");
	$('#data_final').focus(function(){
		$(this).calendario({
			target:'#data_final'
		});
	});
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}
	
	}
	
	
</script>