<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="" class="form" method="post">
	
	<div class="inline">
		<label class="label">Data</label>
		<input type="text" id="data" name="data" class="text" value="<?php echo $this->a['data']; ?>" />
	</div>
	
	<div class="inline">
		<label class="label">Hora</label>
		<input type="text" id="hora" name="hora" class="text" value="<?php echo $this->a['data']; ?>" />
	</div>
	
	<div class="inline" style="width:63%; height:auto;">
		<label class="label">Descri&ccedil;&atilde;o</label>
		<textarea id="descricao" name="descricao" class="text" value="" ><?php echo $this->a['descricao']; ?></textarea>
	</div>
	
	<div class="inline"  style="clear:both; margin-top:10px">
		<label class="label">Baixado</label>
		<input type="checkbox" id="baixado" name="baixado" value="1" <?php echo ($this->a['baixado'] == 1) ? "checked='checked'" : ""; ?> />
	</div>
	
		
	<div class="inline" style="clear:both; margin-top:10px;">
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Cadastrar" onclick="validaCampo('')"/>
	</div>
	

</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){

	var msg = "";
	var erro = false;

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){

	$("#data").mask("99/99/99");
	$("#hora").mask("99:99:99");
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}
	
	$('#data').focus(function(){
		$(this).calendario({
			target:'#data'
		});
	});

})
</script>
