<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="<?php echo URL ?>lancamentos-financeiros/add-recorrente/id/<?php echo $this->id ?>" class="form" method="post">
		
		<?php //var_export($this->lancamentoFinanceiro); //exit;?>
	<!-------	
		<div class="inline">
		<label>Grupos Financeiros</label>
		<select name="id_financeiro_grupo" id="id_financeiro_grupo" class="text req" title="Perfis cadastrados" onchange="getItens(this.value)">
		    <option value="0">SELECIONE</option>			
			<?php
				
				foreach($this->grupos as $grupos){
					
					if($grupos['id'] == $this->lancamentoFinanceiro['idGrupo']){
					
						echo "<option selected=\"selected\" value=\"" . $grupos['id'] . "\">". $grupos['descricao'] ."</option>";
					
					}else{
					
						echo "<option value=\"" . $grupos['id'] . "\">". $grupos['descricao'] ."</option>";
					
					}
					
				}
			
			?>
			
		</select>
	</div>
	
	------->
	
			<div class="inline">
		<label>Itens Financeiros</label>
		<select name="id_financeiro_item" id="id_financeiro_item" class="text req" title="Itens cadastrados">
		    <option value="0">SELECIONE</option>			
			<?php
				
				foreach($this->itens as $itens){
					
					if($itens['id'] == $this->dadosItens['id']){
					
						echo "<option selected=\"selected\" value=\"" . strtoupper($itens['id']) . "\">". strtoupper($itens['item']) ."</option>";
					
					}else{
					
						echo "<option value=\"" . strtoupper($itens['id']) . "\">". strtoupper($itens['item']) ."</option>";
					
					}
					
					
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline">
		<label class="label">Data Lan&ccedil;amento</label>
		<input type="text" id="data_lancamento" name="data_lancamento" class="text req" value="" />
	</div>
	
	<div class="inline">
		<label class="label">Valor</label>
		<input type="text" id="valor" name="valor" class="text req" value="<?php echo $this->dadosItens['valor_padrao']; ?>" />
	</div>
	
	<div class="inline">
		<label class="label">Baixado</label>
		<input type="radio" id="baixado" name="baixado" checked="" value="0">N&atilde;o
		<input type="radio" id="baixado" name="baixado" value="1">Sim
	</div>
	
	<div class="inline" style="width:63%; height:auto; margin-bottom:10px">
		<label class="label">Observa&ccedil;&otilde;es</label>
		<textarea id="observacoes" name="observacoes" class="text" value="" ></textarea>
	</div>
	
	<div style="display:table;clear:both; margin-left: 10px">
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Cadastrar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#id_financeiro_item").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo Itens Financeiros deve ser selecionado.";
	
	}
	
	if($("#data_lancamento").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo Data Lan&ccedil;amento deve ser preenchido.";
	
	}
	
	if($("#valor").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo Valor deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}
	
	$(function(){
	
		$("#data_lancamento").mask("99/99/9999");
		$("#data_lancamento").val("<?php echo @date('d/m/Y'); ?>");
		$("#valor").attr("onkeyup","validaMoedaBR(this.id)");
		
		if($("#msg").html().length > 0){
				
			if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
			
				$("#msg").addClass('sucess');
			
			}else{
			
				$("#msg").addClass('erro');
			
			}
		
		}
		
			$('#data_lancamento').focus(function(){
				$(this).calendario({
					target:'#data_lancamento'
				});
			});

	})

</script>
