<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="add" class="form" method="post">
	
	
	
	<!--------FORMA ANTIGA DE FAZER A BUSCA DE ITENS POR GRUPOS
	<div class="inline">
		<label>Grupos Financeiros</label>
		<select name="id_financeiro_grupo" id="id_financeiro_grupo" class="text req" title="Perfis cadastrados" onchange="getItens(this.value)">
		    <option value="0">SELECIONE</option>			
			<?php
				
				foreach($this->grupos as $grupos){
					
					echo "<option value=\"" . $grupos['id'] . "\" label = \"" . $grupos['descricao'] ."\">  ". $grupos['descricao'] ." </option>";
					
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline">
		<label>Itens Financeiros</label>
		<select name="id_financeiro_item" id="id_financeiro_item" class="text req" title="Itens cadastrados">
		    <option value="0">SELECIONE</option>			
			
			
		</select>
	</div>
	------->
	
	<div class="inline">
		<label>Itens Financeiros</label>
		<select name="id_financeiro_item" id="id_financeiro_item" class="text req" title="Itens cadastrados">
		    <option value="0">SELECIONE</option>
			
			<?php
				
				foreach($this->arrItens as $itens){
					
					echo "<option value=\"" . $itens['id'] . "\" label = \"" . strtoupper($itens['item']) ."\">  ".strtoupper($itens['item'])." </option>";
					
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline">
		<label class="label">Data Lan&ccedil;amento</label>
		<input type="text" id="data_lancamento" name="data_lancamento" class="text req" value="" />
	</div>
	
	<div class="inline">
		<label class="label">Valor</label>
		<input type="text" id="valor" name="valor" class="text req" value="" />
	</div>
	
	<div class="inline">
		<label class="label">Baixado?</label>
			<input checked="checked" type="radio" id="baixado" name="baixado" value="0">N&atilde;o
			<input type="radio" id="baixado" name="baixado" value="1">Sim
	</div>
	
	<div class="inline" style="width:63%; height:auto; margin-bottom:10px">
		<label class="label">Observa&ccedil;&otilde;es</label>
		<textarea id="observacoes" name="observacoes" class="text" value="" ></textarea>
	</div>
	
	<div style="display:table;clear:both; margin-left: 10px">
		<input type="button" id="button" name="button" class="btn-small btn-add" value="Cadastrar" onclick="validaCampo('')"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">


function getItens(idGrupo){

	//$("#resClientes").css("display","block");
	
	var resp = $.ajax({
		url: '<?php echo URL ?>lancamentos-financeiros/ajax/fn/getItens',
      		async: false,
      		type: 'POST',
      		data: ({'id':idGrupo}),
      		dataType: 'text'
   	}).responseText;

	$("#id_financeiro_item").html(resp);

}

function validaCampo(){

	var msg = "";
	var erro = false;
	
	if($("#id_financeiro_grupo").val() == 0){
		
		erro = true;
		
		msg += "<br>O campo grupos financeiros deve ser selecionado.";
	
	}
	
	if($("#id_financeiro_item").val() == 0){
		
		erro = true;
		
		msg += "<br>O campo itens financeiros deve ser selecionado.";
	
	}
	
	if($("#data_lancamento").val() == 0){
		
		erro = true;
		
		msg += "<br>O campo data lan&ccedil;amento deve ser preenchido.";
	
	}
	
	if($("#valor").val() == 0){
		
		erro = true;
		
		msg += "<br>O campo valor deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}
	
	$(function(){
	
		$("#data_lancamento").mask("99/99/9999");
		$("#valor").attr("onkeyup","validaMoedaBR(this.id)");
		
		if($("#msg").html().length > 0){
				
			if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
			
				$("#msg").addClass('sucess');
			
			}else{
			
				$("#msg").addClass('erro');
			
			}
		
		}
		
			$('#data_lancamento').focus(function(){
			$(this).calendario({
			target:'#data_lancamento'
			});
		});

	})

</script>
