<script type="text/javascript" src="/js/jquery-1.3.2.min.js"></script>

<style>
	
	#cabecalho_recibo{
		width:100%;
		border: solid 2px;
		font-family: Arial, Helvetica, sans-serif;
	}
	
	#cabecalho_recibo td{
		width:33%;
		#border: solid 1px;
	}
	
	#cabecalho_recibo tr td input{
		width:40%;
		height: 30%;
		font-size:100%;
		background-color:#CCCCCC;
	}
	
	#titulo{
		font-size:18px;
	}
	
	#texto{
		margin-top: 18px;
		margin-left: 5px;
		margin-bottom: 5px;
	}
	
		
</style> 

<div class="inline" id="recibo">

	<table id="cabecalho_recibo">
	
		<tr>
		
			<td>
						
				<div>
				
					<img src="<?php echo $this->path;?>" alt="Empresa" height="100" width="145">
				</div>
			</td>
			
			<td>	
				<div >
					<?php 
						echo $this->infos;
					?>
				</div>
			</td>
			<td>
				<div align="right">
					<b>N.º&nbsp;</b><input align="right" type="text" readonly="readonly" class="text" value=" <?php echo $this->numero;?>"/><br><br>
					<b>RECIBO R$&nbsp; </b><input type="text" align="right" readonly="readonly" class="text" value="<?php echo $this->valor;?>" />
				</div>
			</td>
		</tr>
		
		
		<tr>
			<td colspan="3">
				<div id="texto">
					<?php
						echo $this->strRecibo;
					?>
				</div>
			</td>
		</tr>
		
		<tr>
			<td colspan="3">
				<div id="texto">
					<?php
						echo $this->text;
					?>
				</div>
			</td>
		</tr>
		
		<tr>
			<td colspan="2">
				<div id="texto">
					<?php
					echo $this->strData;
					?>
				</div>
			</td>
			<td align="center">_________________________________<br>assinatura</td>
		</tr>
	</table>
</div>
1º Via
<br><br>
<center>-----------------------------------------------------------------------------------------------</center>
<br><br>

<div class="inline" id="recibo">

	<table id="cabecalho_recibo">
	
		<tr>
		
			<td>
						
				<div>
				
					<img src="<?php echo $this->path;?>" alt="Empresa" height="100" width="145">
				</div>
			</td>
			
			<td>	
				<div >
					<?php 
						echo $this->infos;
					?>
				</div>
			</td>
			<td>
				<div align="right">
					<b>N.º&nbsp;</b><input align="right" type="text" readonly="readonly" class="text" value=" <?php echo $this->numero;?>"/><br><br>
					<b>RECIBO R$&nbsp; </b><input type="text" align="right" readonly="readonly" class="text" value="<?php echo $this->valor;?>" />
				</div>
			</td>
		</tr>
		
		
		<tr>
			<td colspan="3">
				<div id="texto">
					<?php
						echo $this->strRecibo;
					?>
				</div>
			</td>
		</tr>
		
		<tr>
			<td colspan="3">
				<div id="texto">
					<?php
						echo $this->text;
					?>
				</div>
			</td>
		</tr>
		
		<tr>
			<td colspan="2">
				<div id="texto">
					<?php
					echo $this->strData;
					?>
				</div>
			</td>
			<td align="center">_________________________________<br>assinatura</td>
		</tr>
	</table>
</div>
2º Via
<script type="text/javascript">

	window.print();

</script>