<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="lista" class="form" method="post">

	<div class="inline">
		<label class="label">Clientes/Concession&aacute;ria</label>
		<select id="id_cliente" name="id_cliente" class="select">
			<option value="">Selecione</option>
			<option value=""></option>
			<option value="-2"><?php echo $this->concessionaria['razao_social'];?></option>
		<?php
		
		foreach($this->clientes as $cliente){
		?>
			
			<option value="<?php echo $cliente['id'];?>"><?php echo $cliente['nome'];?></option>
		
		<?php
		}
		?>
			
		</select>
	</div>
	
	
	<div class="inline" id="div_mes">
		<label class="label">Mês</label>
		<select class="select" onChange="enviaPeriodo(this.value);" >
			<option value="0">Selecione</option>
			<?php
				
				for($i = @date("m"); $i > (@date("m")-25); $i--){
				
					$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
					$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
					$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
					
					
					
					switch ($mesNum){
						case 1:
							$option =  "Janeiro - ".$anoNum;
							break;
							
						case 2:
							$option =  "Fevereiro - ".$anoNum;
							break;
						
						case 3:
							$option =  "Março - ".$anoNum;
							break;
							
						case 4:
							$option =  "Abril - ".$anoNum;
							break;
							
						case 5:
							$option =  "Maio - ".$anoNum;
							break;
							
						case 6:
							$option =  "Junho - ".$anoNum;
							break;
							
						case 7:
							$option =  "Julho - ".$anoNum;
							break;
							
						case 8:
							$option =  "Agosto - ".$anoNum;
							break;
							
						case 9:
							$option =  "Setembro - ".$anoNum;
							break;
						
						case 10:
							$option =  "Outubro - ".$anoNum;
							break;
							
						case 11:
							$option =  "Novembro - ".$anoNum;
							break;
							
						case 12:
							$option =  "Dezembro - ".$anoNum;
							break;
			
					}
					
					echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
				
				}
			
			?>
			
		</select>
	</div>
	
	<div class="inline" id="div_datas">
		<table>
			<tr>
				<td>
					<label class="label">Data Inicial</label>
				</td>
				<td>
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<input type="text" class="text" style="width:90%" name="data_inicial" id="data_inicial" value="<?php echo $this->data_inicial; ?>"/>
				</td>
				<td>
					<input type="text" class="text" style="width:90%" name="data_final" id="data_final" value="<?php echo $this->data_final; ?>"/>
				</td>
			</tr>
		</table>
	</div>
	
	<div class="inline" style="clear:both">
		<input type="submit" class="btn-small btn-find" value="Pesquisar" />
		<input type="button" class="btn-mini btn-include" value="Novo Recibo" onclick="javascript:window.location.href='<?php echo URL ?>vale-recibo/recibo-vale'" />
	</div>

</form>
<table class = 'table'>

<thead><tr><th style="vertical-align:middle; border-right: solid 1px #FFFFFF;">Cliente/Concession&aacute;ria</th><th style="vertical-align:middle; border-right: solid 1px #FFFFFF;">Valor</th><th style="vertical-align:middle; border-right: solid 1px #FFFFFF;">Referente</th><th style="vertical-align:middle; border-right: solid 1px #FFFFFF;">Data</th><th style="width:250px; vertical-align:middle; border-right: solid 1px #FFFFFF;">Observa&ccedil;&otilde;es</th><th style="vertical-align:middle; border-right: solid 1px #FFFFFF;">Data Hora Da Emissao</th><th style="vertical-align:middle;">Usuario Que Emitiu</th></thead>

<tbody>

<?php
		$cont=0;
	foreach($this->recibos as $recibo){
		
		if($cont%2 == 0){
			$color = "#FFFFFF";
		}else{
			$color = "#EEEEEE";
		}
		
		$cont++;
	
		$dataTmp = explode("-",$recibo['data']);
		$recibo['data'] = implode("/",array_reverse($dataTmp));
		//var_export($cliente['data']);exit;
		$dataTmp = explode(" ",$recibo['data_hora']);
		$dataTmp2 = explode("-",$dataTmp[0]);
		$recibo['data_hora'] = implode("/",array_reverse($dataTmp2));
		$recibo['data_hora'] = $recibo['data_hora'] . " - " . $dataTmp[1];
	
?>		
		<tr style="background-color: <?php echo $color; ?>">
		<td style="padding:3px;"><?php echo $recibo['cliente']; ?></td>
		<td style="padding:3px;"><?php 
							
				echo number_format($recibo['valor'],2,',','.');
			
		?></td>
		
		<td style="padding:3px;"><?php 
				
				
				echo $recibo['referente'] 
			
		?></td>
		
		<td style="padding:3px;"><?php 
				
				
				echo $recibo['data'];
			
		?></td>
		
		<td style="padding:3px;"><?php 
				
				
				echo $recibo['obs'];
			
		?></td>
		
		<td style="padding:3px;"><?php 
				
				
				echo $recibo['data_hora']; 
			
		?></td>
		
		<td style="padding:3px;"><?php 
				
				
				echo $recibo['emitiu'];
			
		?></td>
		
<?php	
	}
?>

</tbody>
</table>


<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function geraRecibo(){
	
		h=850;
		w=800;
	
		LeftPosition = (screen.width) ? (screen.width-w)/2 : 0;
		TopPosition = (screen.height) ? (screen.height-h)/2 : 0;
		settings = 'height='+h+',width='+w+',top='+TopPosition+',left='+LeftPosition+',scrollbars=\'no\',resizable'
		
		nomeUsuario = $("#usuario").val();
		valorNum = $("#valor").val();
		strReferente = $("#referente").val();
		strObs = $("#obs").val();
		strData = $("#data").val();
	
		datas = strData.split("/");
		
		strData = datas[0]+"-"+ datas[1]+"-"+datas[2];
		
		url = "imprimir-recibo/usuario/"+nomeUsuario+"/valor/"+valorNum+"/referente/"+strReferente+"/obs/"+strObs+"/data/"+strData;
		
		window.open(url,"Recibo",settings);

	}
	
	$("#data").mask("99/99/9999");
	
function validaCampo(){
	
	var msg = "";
	var erro = false;
	
	if($("#usuario").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo funcion&aacute;rio deve ser selecionado.";
	
	}
	
	if($("#valor").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo valor deve ser preenchido.";
	
	}
	
	if($("#referente").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo referente deve ser preenchido.";
	
	}
	
	if($("#data").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo data deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		geraRecibo();
	
	}

}


	function confirmaDelete(msg, id){
	
		if(confirm("Deseja realmente excluir a "+msg+" ?")){
		
			window.location.href = "del/id/" + id;
		
		}
	
	}
	
	$(function(){
	
		$("#data_inicial").mask("99/99/9999");
		$("#data_final").mask("99/99/9999");
		
		if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}
	
	$('#data_inicial').focus(function(){
		$(this).calendario({
			target:'#data_inicial'
		});
	});
 
	$('#data_final').focus(function(){
		$(this).calendario({
			target:'#data_final'
		});
	});

	});
	
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}
	
	}

</script>
