<form id="form" name="form" target="_blank" enctype="application/x-www-form-urlencoded" action="imprimir-recibo" class="form" method="post">
	
	<div class="inline" style="margin-bottom:15px;">
		<label class="label">Recebi(emos)</label>
		<select id="usuario" name="usuario" class="text req" style="width:65%" onfocus="getClientes();">
			
		
		</select>
		
		<input type="button" class="btn-mini btn-include" value="Add" onclick="javascript:window.open('<?php echo URL ?>clientes/add')" />
		
		<span style="color:green; font-size:11px;">Selecione quem ir&aacute; efetuar o pagamento.</span>
	</div>

	<div class="inline" style="margin-bottom:15px;">
		<label class="label">A import&acirc;ncia</label>
		<input type="text" id="valor" name="valor" class="text req" value="" onkeyup="validaMoedaBR(this.id)"/>
		<span style="color:green; font-size:11px;">Digite o valor a ser pago. Ex.'250,00'.</span>
	</div>
	
	<div class="inline" style="margin-bottom:15px;">
		<label class="label">Referente à</label>
		<input type="text" id="referente" name="referente" class="text req" value="" />
		<span style="color:green; font-size:11px;">Digite o motivo do pagamento. Ex. 'Servi&ccedil;os Prestados'.</span>
	</div>

	<div class="inline" style="margin-bottom:15px;">
		<label class="label">Data</label>
		<input type="text" id="data" name="data" class="text req" value="<?php echo @date("d/m/Y") ?>" />
		<span style="color:green; font-size:11px;">Selecione a data do pagamento. Ex. '12/12/2012'.</span>
	</div>
	
	<div class="inline">
		<label class="label">Observa&ccedil;&otilde;es</label>
		<textarea id="obs" name="obs" class="text"></textarea>
	</div>
	
	<div class="inline" style="clear:both; margin-top:10px;">
		<input type="button" id="button" name="button" class="btn-small-imp" value="Imprimir" onclick="validaCampo()"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

	function getClientes(){
		
		$.ajax({                   
			type: "POST",
			url:"/vale-recibo/ajax/fn/getClientes",
			dataType:"html",
			//data:{idempresa:id},                       
			success:function(retorno){
				
				$("#usuario").html(retorno);
				
				//alert(retorno);
			
			}
		})

	}

	function geraRecibo(){
	
		h=850;
		w=800;
	
		LeftPosition = (screen.width) ? (screen.width-w)/2 : 0;
		TopPosition = (screen.height) ? (screen.height-h)/2 : 0;
		settings = 'height='+h+',width='+w+',top='+TopPosition+',left='+LeftPosition+',scrollbars=\'no\',resizable'
		
		nomeUsuario = $("#usuario").val();
		valorNum = $("#valor").val();
		strReferente = $("#referente").val();
		strObs = $("#obs").val();
		strData = $("#data").val();
	
		datas = strData.split("/");
		
		strData = datas[0]+"-"+ datas[1]+"-"+datas[2];
		
		url = "imprimir-recibo/usuario/"+nomeUsuario+"/valor/"+valorNum+"/referente/"+strReferente+"/obs/"+strObs+"/data/"+strData;
		
		//window.open(url,"Recibo",settings);

	}
	
	$("#data").mask("99/99/9999");
	
function validaCampo(){
	
	var msg = "";
	var erro = false;
	
	if($("#usuario").val() == -1){
		
		erro = true;
		
		msg += "<br>O campo recebi(emos) deve ser selecionado.";
	
	}
	
	if($("#valor").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo a import&acirc;ncia deve ser preenchido.";
	
	}
	
	if($("#referente").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo referente deve ser preenchido.";
	
	}
	
	if($("#data").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo data deve ser preenchido.";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		//geraRecibo();
		$("#form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}
	
		$('#data').focus(function(){
		$(this).calendario({
			target:'#data'
		});
	});
	
	getClientes();

})

</script>
