<style>

.table {
	font-family: Arial, Helvetica, sans-serif;
	font-size: 13px;
	width:99%;
	border-left:1px solid #d4d4d4;
	border-top:1px solid #d4d4d4;
	margin-bottom:15px;
	margin-left:auto;
	margin-right:auto;
}

.table tr th, .table tr td {
	padding:5px 10px;
}

.table tr td img{
	padding-right:10px;
}

.table tr th {
	background:#a3a3a3;
	color:#FFF;
	text-align:center;
}

.table tr td {
	border-right:1px solid #d4d4d4;
	border-bottom:1px solid #d4d4d4;
	vertical-align:middle;
}

.table tr.zebra td {
	background:#F2F2F2;
}

.table .table-options {
	padding:10px;
}

.table .table-sub {
	background: url(../images/bg-input.gif) repeat-x #F9F9F9;
	padding:15px;
}

</style>

<table id='table_contratos' class="table">
	<tr>
		<th colspan='2'>Clique no bot&atilde;o para gerar o contrato</th>
	</tr>
			
<?php	foreach($this->arrContratos as $contrato){
			
			echo "<tr><td>".$contrato['nome']."</td><td><input type='button' value='Gerar Contrato' onclick='geraContrato(".$contrato['id'].")'></td></tr>";
			
		}
?>
</table>

<script type="text/javascript">

function geraContrato(id){

	var idCliente = <?php echo $this->idCliente;?>;
	var idEmpresa = <?php echo $this->idEmpresa;?>;
	var idVeiculo = <?php echo $this->idVeiculo;?>;
	var idNegociacao = <?php echo $this->idNegociacao;?>;
	
	window.open("/contratos/gera-contrato/id_contrato/"+id+"/id_cliente/"+idCliente+"/id_empresa/"+idEmpresa+"/id_veiculo/"+idVeiculo+"/id_negociacao/"+idNegociacao);

	window.close();
	
}

</script>