<form class="form" action="despachantes" method="post" id="form">
	
<div class="inline" id="div_select">
	<label class="label">Despachante</label>
	<select name = "id_despachante" id="id_despachante" class="select">
		<option value = "0">Todos</option>
		<?php
		foreach($this->despachantes as $despachante){
		
			if($despachante['id'] == $this->idDespachante){
			
				echo "<option selected='selected' value = '".$despachante['id']."'>".$despachante['nome']."</option>";
			
			}else{
		
				echo "<option value = '".$despachante['id']."'>".$despachante['nome']."</option>";
			
			}
		
		}
		?>
		</select>
</div>

<div class="inline" id="div_mes">
		<label class="label">Mês</label>
		<select class="select" onChange="enviaPeriodo(this.value);" >
			<option value="0">Selecione</option>
			<?php
				
				for($i = @date("m"); $i > (@date("m")-25); $i--){
				
					$mesNum = @date("m", mktime(0, 0, 0, $i, 01, @date("Y")));
					$anoNum = @date("Y", mktime(0, 0, 0, $i, 01, @date("Y")));
					$ultimoDia = @date("d", mktime(0, 0, 0, $i+1, 0, @date("Y")));
					
					
					
					switch ($mesNum){
						case 1:
							$option =  "Janeiro - ".$anoNum;
							break;
							
						case 2:
							$option =  "Fevereiro - ".$anoNum;
							break;
						
						case 3:
							$option =  "Março - ".$anoNum;
							break;
							
						case 4:
							$option =  "Abril - ".$anoNum;
							break;
							
						case 5:
							$option =  "Maio - ".$anoNum;
							break;
							
						case 6:
							$option =  "Junho - ".$anoNum;
							break;
							
						case 7:
							$option =  "Julho - ".$anoNum;
							break;
							
						case 8:
							$option =  "Agosto - ".$anoNum;
							break;
							
						case 9:
							$option =  "Setembro - ".$anoNum;
							break;
						
						case 10:
							$option =  "Outubro - ".$anoNum;
							break;
							
						case 11:
							$option =  "Novembro - ".$anoNum;
							break;
							
						case 12:
							$option =  "Dezembro - ".$anoNum;
							break;
			
					}
					
					echo "<option value='".$ultimoDia."_".$mesNum."_".$anoNum."'>".$option."</option>";
				
				}
			
			?>
			
		</select>
	</div>


	<div class="inline" id="div_datas">
		<table>
			<tr>
				<td>
					<label class="label">Data Inicial</label>
				</td>
				<td>
					<label class="label">Data Final</label>
				</td>
			</tr>
			<tr>
				<td>
					<input type="text" class="text" style="width:90%" name="data_inicial" id="data_inicial" value="<?php echo $this->dataInicial; ?>"/>
				</td>
				<td>
					<input type="text" class="text" style="width:90%" name="data_final" id="data_final" value="<?php echo $this->dataFinal; ?>"/>
				</td>
			</tr>
		</table>
	</div>
	
	<div class="inline" style="clear:both; width:50%;" id="div_botoes">
		<input type="hidden" id="relatorio" name="relatorio" value="<?php echo $this->relatorio; ?>"/>
		<input type="hidden" id="tipo_relatorio" name="tipo_relatorio" value="Relatorio Despachantes"/>
		<input type="submit" class="btn-small btn-find" value="Pesquisar" />
		<input type="button" class="btn-small-xls" value="Gerar XLS" onclick="geraXls();"/>
		<input type="button" class="btn-small-imp" value="Imprimir" onclick="imprimir('print','Fornecedores');"/>
	</div>

</form>

<div id="print">
<link rel="stylesheet" href="/css/style.css" type="text/css" media="print">
	
	<?php
	echo $this->relatorio;
	?>

</div>

<script type="text/javascript">

	function imprimir(id, pg) {
	
		var oPrint, oJan;
		oPrint = window.document.getElementById(id).innerHTML;
		oJan = window.open(pg);
		oJan.document.write(oPrint);
		oJan.window.print();
		oJan.document.close();
		oJan.focus();

}

	function geraXls(){
	
		$("form").attr("action","gerar-xls");
		$("form").submit();
		$("form").attr("action","despachantes");
	
	}
	
	$("#data_inicial").mask("99/99/9999");
	$('#data_inicial').focus(function(){
		$(this).calendario({
			target:'#data_inicial'
		});
	});
	
	$("#data_final").mask("99/99/9999");
	$('#data_final').focus(function(){
		$(this).calendario({
			target:'#data_final'
		});
	});
	
	
	function enviaPeriodo(valor){
		
		if(valor != "0"){
		
			var arrData = valor.split("_");
			var datafinal = arrData[0]+"/"+arrData[1]+"/"+arrData[2];
			var dataInicial = "01/"+arrData[1]+"/"+arrData[2];
			
			$("#data_inicial").val(dataInicial);
			$("#data_final").val(datafinal);
		
		}
	
	}

</script>