<form id="form" name="form" enctype="application/x-www-form-urlencoded" action="patrimonio" class="form" method="post">
	<label class="label" style="margin-left:10px;">Em Caixa</label>
	<table class="table">
		<thead>
			<tr>
				<th>Origem</th>
				<th>Especie</th>
				<th>Valor</th>
				<th colspan="2" style="width:20%;">A&ccedil;&otilde;es</th>
			</tr>
		</thead>
		
		<tbody id="despesas_negociacao">
			<tr id="despesas_negociacao_line_0">
				<td><input type="text" id="origem_0" class="text" value="" /></td>
				<td><input type="text" id="espacie_0" class="text" value="" /></td>
				<td><input type="text" id="valor_0" class="text" value="" onkeyup="calculaValorDespesas(); validaMoedaBR(this.id);"/></td>
				<td>
					<input type="button" id="btn_0" class="btn-mini btn-include" value="Add" onclick="adddespesa();calculaValorDespesas();">
				
				<input type="button" class="btn-small btn-del" id="deleta" value="Deletar"/>
				</td>
			</tr>
		</tbody>
	</table>
	
	<div class="inline">
		<label class="label">Custo de Ve&iacute;culos em Estoque</label>
		<input type="text" id="custo_veiculo" class="text" readonly="readonly" value="<?php echo money_format("%i",$this->custoEstoque); ?>"/>
	</div>
	
	<div class="inline">
		<label class="label">A Receber</label>
		<input type="text" id="receber" class="text" readonly="readonly" value="<?php echo money_format("%i",$this->aReceber); ?>"/>
	</div>
	
	<div class="inline">
		<label class="label">Total em Caixa</label>
		<input type="text" id="em_caixa" class="text" readonly="readonly" value=""/>
	</div>
	
	<div class="inline" style="clean:both;">
		<label class="label">Total Patrim&ocirc;nio</label>
		<input type="text" id="patrimonio" name="patrimonio" class="text" readonly="readonly" value=""/>
	</div>
	
	<div class="inline" id="div_select">
		<label class="label">Data</label>
		<select name = "data" id="data" class="select">
			<option value = "">Selecione</option>
			<?php
			foreach($this->data as $data){

				echo "<option value = '".$data['data_america']."'>".$data['data_extenso']."</option>";

			}
			?>
		</select>
	</div>
	
	<div class="inline" style="clear:both">
		<input type="button" class="btn-small btn-add" value="Salvar" onclick="valida();"/>
	</div>
	
</form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<div>
	
	<center>
		<canvas id="line1" width="900px" height="300" style="cursor: default; "></canvas>
		<div style="margin-bottom:40px; margin-top:-10px;"><img src="/images/legenda_grafico.jpg"></div>
	</center>
	
</div>
<center>
<div id="print" style='width:900px'>
<link rel="stylesheet" href="/css/style.css" type="text/css" media="print">

	<?php
	echo $this->relatorio;
	?>

</div>
</center>

<script type="text/javascript">

	function valida(){
	
		
	var msg = "";
	var erro = false;
	
	if($("#data").val() == ""){
		
		erro = true;
		
		msg += "<br>O campo data deve ser selecionado.";
		
	}
	
	if($("#patrimonio").val() == "0,00"){
		
		erro = true;
		
		msg += "<br>O patrimonio não pode ser 0,00";
	
	}

	if(erro){
		
		msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})


	function calculaValorDespesas(){
	
		var elemento = new Array();
		valor = 0;
	
		receber = parseFloat($("#receber").val());
		estoque = parseFloat($("#custo_veiculo").val());
		
		$("#despesas_negociacao tr td").each(function(){
			
			elemento = $(this).children().attr('id').split("_");

			if(elemento[0] == "valor"){
			
				valor += parseFloat($(this).children().val().replace(",","."));

			}
		
		});
		
		$("#em_caixa").val(float2moeda(valor));
		
		$("#patrimonio").val(float2moeda(receber+estoque+valor));

	}


	<?php
		echo "desenhaGraficoLinhaBarra(".$this->graficoAtual .",".$this->graficoAnterior .",".$this->media .",".$this->valorMaior .", 'Gráfico de Evolução de Patrimônio');";
	?>
	
	var despesasAdd = 0;
	
	function adddespesa(){

		despesasAdd++;

		var line = $("#despesas_negociacao_line_0").clone();
		
		$("#despesas_negociacao").append(line);
		
		$("#despesas_negociacao tr:last td").each(function(){

			var idLine = $(this).children().attr('id').split("_");
			$(this).children().attr('id', idLine[0]+"_"+despesasAdd);
			
			if($(this).children().val() == "Deletar"){
				
				$(this).children().attr('onclick', "deletarAdd("+despesasAdd+"); calculaValorDespesas();");
			
			}
			
			$(this).parent().attr('id', "despesas_negociacao_line_"+despesasAdd);
			
			

		});

	}
	
	function deletarAdd(id){
		
		$("#despesas_negociacao_line_"+id).remove();
		
	}
	
	receber = parseFloat($("#receber").val());
	estoque = parseFloat($("#custo_veiculo").val());
	$("#patrimonio").val(float2moeda(receber+estoque));

</script>