<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Meucar - <?php echo $this->message; ?></title>
</head>
<body>

<?php
	if($this->message == "404"){

	   echo "<center><h1>404</h1></center>";
     echo "<center><div style='font-size:18px; margin-top:50px;'>P&aacute;gina n&atilde;o encontrada, por favor verifique o endere&ccedil;o e tente novamente.</div></center>";
	
	}else{
	
		/*//echo "<center><div style='font-size:18px; margin-top:50px;'>A&ccedil;&atilde;o n&atilde;o reconhecida, verifique a a&ccedil;&atilde;o solicitada e tente novamente, caso o erro persista <a target='_blanck' href='/carros-usados/contato'>avise-nos.</a></div></center>";
		echo "<center><div style='font-size:18px; margin-top:50px;'>Se você tem conta no icarros e está tentando atualizar alguma informação, esse erro pode ter sido causado por falha no servidor do Icarros, por favor tente novamente <a href='javascript:location.reload();'>aqui</a>, caso o erro persista <a target='_blanck' href='/carros-usados/contato'>avise-nos.</a></div></center>";*/
	
	}

 ?>

 <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
 <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
 <br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
 
  <h1>An error occurred</h1>
  <h2><?php echo $this->message ?></h2>

  <?php if (isset($this->exception)): ?>
  
  <h3>Exception information:</h3>
  <p>
      <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>

  <?php endif ?>
  

</body>
</html>
