<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<style>

	.table {
		width:99%;
		border-left:1px solid #d4d4d4;
		border-top:1px solid #d4d4d4;
		margin-bottom:15px;
		margin-left:auto;
		margin-right:auto;
		padding:10px;
		font-family: Arial, Helvetica, sans-serif;
		font-size:12px;
	}
	
	.cabeca {
		background:#a3a3a3;
		color:#FFF;
		text-align:center;
		padding:5px 10px;
	}
	
	.tds {
		border-right:1px solid #d4d4d4;
		border-bottom:1px solid #d4d4d4;
		vertical-align:middle;
		padding:5px 10px;
	}

</style>
<?php

$nomeArquivo = $this->tipoRelatorio." De ".$this->dataInicial." até ".$this->dataFinal;

header("Content-type: application/msexcel");
header("Content-Disposition: attachment; filename=".$nomeArquivo.".xls");

echo $this->relatorio;

exit;

?>