
<form id="form" name="form" enctype="multipart/form-data" action="ler-xlsx" class="form" method="post">
	<div class="inline">
		<input type="file" name="xlsx" id="xlsx" />
	</div>

	<div class="inline" style="clear:both; margin-top:10px;">
		<input type="button" id="bnt" class="btn-small btn-add" value="Salvar" onclick="valida();"/>
	</div>

	<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>


</form>



<script type="text/javascript">

	$(document).ready(() => {
		if($("#msg").html() != ""){
			if(!$("#msg").html().indexOf("ERRO")) {
				$("#msg").addClass('erro');
			}else{
				$("#msg").addClass('sucess');
			}
		}
	});

	function valida() {

		let erro = false;


		if($("#xlsx").val() == ""){
			erro = true;
		}

		if(erro){
			$("#msg").addClass('erro');
			$("#msg").html("Por favor, adicione uma planilha!")
		}else{
			$("#form").submit();
		}
	}

</script>