<style>



	.legenda_silver{

		position: relative;

		background: silver;

		border: 1px solid #fff;

		color: #fff;

	}

	.legenda_silver:after, .legenda_silver:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.legenda_silver:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: silver;

		border-width: 11px;

		margin-top: -22px;

	}

	.legenda_silver:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 0px;

		margin-top: 0px;

	}







	.legenda_azul{

		position: relative;

		background: #436EEE;

		border: 1px solid #fff;

		color: #fff;

	}

	.legenda_azul:after, .legenda_azul:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.legenda_azul:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: #436EEE;

		border-width: 11px;

		margin-top: -22px;

	}

	.legenda_azul:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 0px;

		margin-top: 0px;

	}

	

	



	.legenda_yellow{

		position: relative;

		background: #FFD700;

		border: 1px solid #fff;

		color: #fff;

	}

	.legenda_yellow:after, .legenda_yellow:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.legenda_yellow:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: #FFD700;

		border-width: 11px;

		margin-top: -22px;

	}

	.legenda_yellow:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 0px;

		margin-top: 0px;

	}

	

	.legenda_red{

		position: relative;

		background: red;

		border: 1px solid #fff;

		color: #fff;

	}

	.legenda_red:after, .legenda_red:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.legenda_red:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: red;

		border-width: 11px;

		margin-top: -22px;

	}

	.legenda_red:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 0px;

		margin-top: 0px;

	}



	.legenda_green{

		position: relative;

		background: green;

		border: 1px solid #fff;

		color: #fff;

	}

	.legenda_green:after, .legenda_green:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.legenda_green:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: green;

		border-width: 11px;

		margin-top: -22px;

	}

	.legenda_green:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 0px;

		margin-top: 0px;

	}

	

	.green {

		position: relative;

		background: green;

		border: 3px solid #fff;

		/*height: 53px;*/

		color: #fff;

	}

	.green:after, .green:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.green:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: green;

		border-width: 21px;

		margin-top: -42px;

	}

	.green:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 26px;

		margin-top: -4px;

	}

	

	.silver {

		position: relative;

		background: silver;

		border: 3px solid #fff;

		height: 44px;

		color: #fff;

	}

	.silver:after, .silver:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.silver:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: silver;

		border-width: 22px;

		margin-top: -42px;

	}

	.silver:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 26px;

		margin-top: -4px;

	}

	

	.red {

		position: relative;

		background: red;

		border: 3px solid #fff;

		height: 44px;

		color: #fff;

	}

	.red:after, .red:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.red:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: red;

		border-width: 22px;

		margin-top: -42px;

	}

	.red:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 26px;

		margin-top: -4px;

	}

	

	.yellow {

		position: relative;

		background: #FFD700;

		border: 3px solid #fff;

		/*height: 44px;*/

		color: #fff;

	}

	.yellow:after, .yellow:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.yellow:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: #FFD700;

		border-width: 22px;

		margin-top: -42px;

	}

	.yellow:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 26px;

		margin-top: -4px;

	}

	

	.blue {

		position: relative;

		background: #436EEE;

		border: 3px solid #fff;

		height: 44px;

		color: #fff;

	}

	.blue:after, .blue:before {

		left: 100%;

		border: solid transparent;

		content: " ";

		height: 0;

		width: 0;

		position: absolute;

		pointer-events: none;

	}



	.blue:after {

		border-color: rgba(0, 128, 0, 0);

		border-left-color: #436EEE;

		border-width: 22px;

		margin-top: -42px;

	}

	.blue:before {

		border-color: rgba(194, 225, 245, 0);

		border-left-color: #fff;

		border-width: 26px;

		margin-top: -4px;

	}

	

	.arrow_text{

		color:#fff;

		padding: 10px;

		padding-left: 23px;

		padding-right: 0px;

		cursor:pointer;

		width: 67px;

		height:22px;

		font-weight: bold;

	}



	.tipo_estoque{

		color:#fff;

		padding-top: 10px;

		padding-bottom: 20px;

		padding-left: 5px;

		padding-right: 5px;

		cursor:pointer;

	}

	

	.data{

		width:100%;

		pointer-events: none;

		background-color: #ccc;

	}

	

	#table_legenda{

		border-right:solid 1px silver;

	}

	

	#table_legenda tr th{

		text-align:center;

		background-color:silver;

		padding:5px;

	}

	

	#table_legenda tr td{

		padding-right:15px;

		padding-top:7px;

		padding-bottom:7px;

		border-bottom:solid 1px silver;

	}



	.span_data{

		font-size: 10px;

		color: #fff;

	}



	.popup td{

		padding:5px;

	}



	@keyframes animacaoVencida {

	  	50% {background: orange;}

	 	100% { background: red;}

	}



	.vencida{ 

		animation: animacaoVencida ease 5s infinite alternate;

	}

	

</style>

<table id="table_legenda">

	<tr>

		<th colspan="5">LEGENDA</th>

	</tr>

	<tr>

		<td>

			<div class="legenda_green" style="after::background-color: red;">

				<div style="padding:5px;">

					Verde = Etapa concluida

				</div>

			</div>

		</td>

		<td>

			<div class="legenda_red" style="after::background-color: red;">

				<div style="padding:5px;">

					Vermelho = Etapa atrasada

				</div>

			</div>

		</td>

		<td>

			<div class="legenda_yellow" style="after::background-color: red;">

				<div style="padding:5px;">

					Amarelo = Etapa agendada

				</div>

			</div>

		</td>

		<td>

			<div class="legenda_azul" style="after::background-color: red;">

				<div style="padding:5px;">

					Azul = Etapa em andamento

				</div>

			</div>

		</td>

		<td>

			<div class="legenda_silver" style="after::background-color: red;">

				<div style="padding:5px;">

					Cinza = Etapa desnecessária

				</div>

			</div>

		</td>

	</tr>

	<tr>

		<td><b style="color: orange;"><span style="background-color: orange; color:#fff; padding:5px;">R</span> = Repasse</b></td>

		<td><b style="color: red;"><span style="background-color: red; color:#fff; padding:5px;">V</span> = Consignado Virtual</b></td>

		<td><b style="color: blue;"><span style="background-color: blue; color:#fff; padding:5px;">C</span> = Consignado</b></td>

		<td><b style="color: green;"><span style="background-color: green; color:#fff; padding:5px;">E</span> = Estoque</b></td>

		<td><b style="margin-left:5px;"><i>!</i> = Informações em observação</b></td>

	</tr>

</table>

<br/>

<table >



<?php



	//var_export($this->arrPeriodoPreparacao);





$cont = 0;

foreach($this->arrVeiculos as $veiculo){

$cont++;

?>



<tr>

	<td >

		<div class="tipo_estoque" style="background-color:<?php if($veiculo['consignado'] == 0){echo "green";}elseif($veiculo['consignado'] == 1){echo "blue";}elseif($veiculo['consignado'] == 2){echo "orange";}elseif($veiculo['consignado'] == 3){echo "red";} ?>; z-index:15;">

			<?php if($veiculo['consignado'] == 0){echo "<b title='Estoque'>E</b>";}elseif($veiculo['consignado'] == 1){echo "<b title='Consignado'>C</b>";}elseif($veiculo['consignado'] == 2){echo "<b title='Repasse'>R</b>";}elseif($veiculo['consignado'] == 3){echo "<b title='Consignado virtual'>V</b>";}?>

		</div>

	</td>

	<td>

		<div style="<?php echo $veiculo['vendido']?'background-color:#A9D0F5;':'background-color:#436EEE;'; ?> z-index:14;" title="<?php echo "&Uacute;LTIMA ALTERA&Ccedil;&Atilde;O:\nUsu&aacute;rio: ".$veiculo['nome_usuario_preparacao']."\nData e Hora: ".implode("/",array_reverse(explode("-",current(explode(" ",$veiculo['data_hora'])))))." às ".end(explode(" ",$veiculo['data_hora']))."\nItem Alterado: ".ucfirst($veiculo['item_alterado']); ?>">

			<div style="width:180px; padding-left:3px;" class="arrow_text" onclick="window.open('/veiculos/edt/id/<?php echo $veiculo['id']; ?>')">

				<?php echo substr($veiculo['descricao_site'], 0, 13)." - ".$veiculo['placa']; ?><br>

				<span class="span_data"><b>Data de início</b>: <?php echo implode("/", array_reverse(explode("-", $veiculo['data_inicio_preparacao']))); ?></span>

				<input type="hidden" id="data_inicio_preparacao_<?php echo $veiculo['id']; ?>" value="<?php echo $veiculo['data_inicio_preparacao']; ?>">

			</div>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['mecanico']==0){echo "yellow";}elseif($veiculo['mecanico']==1){echo "green";}elseif($veiculo['mecanico']==2){echo "silver";}elseif($veiculo['mecanico']==4){echo "blue";}else{echo "red";} ?>" style="z-index:13;">

			<div class="arrow_text" onclick="openPopup(this, 'mecanico', <?php echo $veiculo['id']; ?>)" style="margin-left: -15px;">

				Mecânico<?php if($veiculo['mecanico_obs']){echo "&nbsp;<i style='font-weight:bold;'	>!</i>";} ?>

				<br/><span class="span_data" id="data_final_mecanico_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['mecanico_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Mecânico - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="mecanico_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('mecanico', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['mecanico']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['mecanico']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['mecanico']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['mecanico']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['mecanico']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="mecanico_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['data_inicio_preparacao']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_mecanico_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['mecanico']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="mecanico_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('mecanico', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['mecanico_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="mecanico_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['mecanico_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="mecanico_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['mecanico_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('mecanico',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['funilaria']==0){echo "yellow";}elseif($veiculo['funilaria']==1){echo "green";}elseif($veiculo['funilaria']==2){echo "silver";}elseif($veiculo['funilaria']==4){echo "blue";}else{echo "red";} ?>" style="z-index:12;">

			<div class="arrow_text" onclick="openPopup(this, 'funilaria', <?php echo $veiculo['id']; ?>)">

				Funilaria<?php if($veiculo['funilaria_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_funilaria_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['funilaria_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Funilaria - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="funilaria_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('funilaria', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['funilaria']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['funilaria']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['funilaria']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['funilaria']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['funilaria']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="funilaria_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['funilaria_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_funilaria_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['funilaria']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="funilaria_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('funilaria', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['funilaria_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="funilaria_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['funilaria_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="funilaria_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['funilaria_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('funilaria',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['martelinho']==0){echo "yellow";}elseif($veiculo['martelinho']==1){echo "green";}elseif($veiculo['martelinho']==2){echo "silver";}elseif($veiculo['martelinho']==4){echo "blue";}else{echo "red";} ?>" style="z-index:11;">

			<div class="arrow_text" onclick="openPopup(this, 'martelinho', <?php echo $veiculo['id']; ?>)">

				Martelinho<?php if($veiculo['martelinho_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_martelinho_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['martelinho_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Martelinho - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="martelinho_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('martelinho', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['martelinho']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['martelinho']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['martelinho']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['martelinho']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['martelinho']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="martelinho_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['martelinho_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_martelinho_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['martelinho']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="martelinho_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('martelinho', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['martelinho_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="martelinho_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['martelinho_date_concluido']))); ?>" />

					</td>

				</tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="martelinho_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['martelinho_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('martelinho',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['eletrica']==0){echo "yellow";}elseif($veiculo['eletrica']==1){echo "green";}elseif($veiculo['eletrica']==2){echo "silver";}elseif($veiculo['eletrica']==4){echo "blue";}else{echo "red";} ?>" style="z-index:10;">

			<div class="arrow_text" onclick="openPopup(this, 'eletrica', <?php echo $veiculo['id']; ?>)">

				Elétrica<?php if($veiculo['eletrica_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_eletrica_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['eletrica_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Elétrica - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="eletrica_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('eletrica', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['eletrica']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['eletrica']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['eletrica']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['eletrica']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['eletrica']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="eletrica_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['eletrica_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_eletrica_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['eletrica']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="eletrica_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('eletrica', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['eletrica_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="eletrica_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['eletrica_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="eletrica_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['eletrica_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('eletrica',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['tapecaria']==0){echo "yellow";}elseif($veiculo['tapecaria']==1){echo "green";}elseif($veiculo['tapecaria']==2){echo "silver";}elseif($veiculo['tapecaria']==4){echo "blue";}else{echo "red";} ?>" style="z-index:9;">

			<div class="arrow_text" onclick="openPopup(this, 'tapecaria', <?php echo $veiculo['id']; ?>)">

				Tapeçaria<?php if($veiculo['tapecaria_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_tapecaria_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['tapecaria_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Tapeçaria - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="tapecaria_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('tapecaria', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['tapecaria']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['tapecaria']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['tapecaria']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['tapecaria']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['tapecaria']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="tapecaria_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['tapecaria_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_tapecaria_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['tapecaria']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="tapecaria_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('tapecaria', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['tapecaria_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="tapecaria_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['tapecaria_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="tapecaria_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['tapecaria_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('tapecaria',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['lavacar']==0){echo "yellow";}elseif($veiculo['lavacar']==1){echo "green";}elseif($veiculo['lavacar']==2){echo "silver";}elseif($veiculo['lavacar']==4){echo "blue";}else{echo "red";} ?>" style="z-index:8;">

			<div class="arrow_text" onclick="openPopup(this, 'lavacar', <?php echo $veiculo['id']; ?>)">

				Lavacar<?php if($veiculo['lavacar_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_lavacar_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['lavacar_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Lavacar - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="lavacar_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('lavacar', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['lavacar']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['lavacar']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['lavacar']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['lavacar']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['lavacar']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="lavacar_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['lavacar_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_lavacar_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['lavacar']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="lavacar_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('lavacar', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['lavacar_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="lavacar_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['lavacar_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="lavacar_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['lavacar_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('lavacar',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['volante']==0){echo "yellow";}elseif($veiculo['volante']==1){echo "green";}elseif($veiculo['volante']==2){echo "silver";}elseif($veiculo['volante']==4){echo "blue";}else{echo "red";} ?>" style="z-index:7;">

			<div class="arrow_text" onclick="openPopup(this, 'volante', <?php echo $veiculo['id']; ?>)">

				Volante<?php if($veiculo['volante_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_volante_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['volante_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Volante - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="volante_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('volante', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['volante']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['volante']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['volante']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['volante']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['volante']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="volante_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['volante_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_volante_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['volante']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="volante_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('volante', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['volante_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="volante_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['volante_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="volante_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['volante_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('volante',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['calotas']==0){echo "yellow";}elseif($veiculo['calotas']==1){echo "green";}elseif($veiculo['calotas']==2){echo "silver";}elseif($veiculo['calotas']==4){echo "blue";}else{echo "red";} ?>" style="z-index:6;">

			<div class="arrow_text" onclick="openPopup(this, 'calotas', <?php echo $veiculo['id']; ?>)">

				Calotas<?php if($veiculo['calotas_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_calotas_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['calotas_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 16; display: none; box-shadow: 5px 5px 2px #444;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Calotas - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="calotas_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('calotas', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['calotas']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['calotas']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['calotas']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['calotas']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['calotas']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="calotas_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['calotas_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_calotas_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['calotas']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="calotas_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('calotas', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['calotas_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="calotas_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['calotas_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="calotas_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['calotas_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('calotas',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['pneus']==0){echo "yellow";}elseif($veiculo['pneus']==1){echo "green";}elseif($veiculo['pneus']==2){echo "silver";}elseif($veiculo['pneus']==4){echo "blue";}else{echo "red";} ?>" style="z-index:5;">

			<div class="arrow_text" onclick="openPopup(this, 'pneus', <?php echo $veiculo['id']; ?>)">

				Pneus<?php if($veiculo['pneus_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_pneus_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['pneus_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 17; display: none; box-shadow: 5px 5px 2px #444; margin-left:-350px;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Pneus - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div>

					</td>

					<td>

						<div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="pneus_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('pneus', <?php echo $veiculo['id']; ?>, false)">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['pneus']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['pneus']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['pneus']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['pneus']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['pneus']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="pneus_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['pneus_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_pneus_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['pneus']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="pneus_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('pneus', <?php echo $veiculo['id']; ?>, false)" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['pneus_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="pneus_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['pneus_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="pneus_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['pneus_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('pneus',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['chaveiro']==0){echo "yellow";}elseif($veiculo['chaveiro']==1){echo "green";}elseif($veiculo['chaveiro']==2){echo "silver";}elseif($veiculo['chaveiro']==4){echo "blue";}else{echo "red";} ?>" style="z-index:4;">

			<div class="arrow_text" onclick="openPopup(this, 'chaveiro', <?php echo $veiculo['id']; ?>)">

				Chaveiro<?php if($veiculo['chaveiro_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_chaveiro_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['chaveiro_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 17; display: none; box-shadow: 5px 5px 2px #444; margin-left:-350px;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Chaveiro - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="chaveiro_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('chaveiro',<?php echo $veiculo['id']; ?>, false);">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['chaveiro']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['chaveiro']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['chaveiro']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['chaveiro']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['chaveiro']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="chaveiro_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['chaveiro_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_chaveiro_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['chaveiro']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="chaveiro_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('chaveiro',<?php echo $veiculo['id']; ?>, false);" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['chaveiro_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="chaveiro_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['chaveiro_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="chaveiro_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['chaveiro_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('chaveiro',<?php echo $veiculo['id']; ?>,true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['pincelar']==0){echo "yellow";}elseif($veiculo['pincelar']==1){echo "green";}elseif($veiculo['pincelar']==2){echo "silver";}elseif($veiculo['pincelar']==4){echo "blue";}else{echo "red";} ?>" style="z-index:3;">

			<div class="arrow_text" onclick="openPopup(this, 'pincelar', <?php echo $veiculo['id']; ?>)">

				Pincelar<?php if($veiculo['pincelar_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_pincelar_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['pincelar_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 17; display: none; box-shadow: 5px 5px 2px #444; margin-left:-350px;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Pincelar - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="pincelar_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('pincelar',<?php echo $veiculo['id']; ?>, false);">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['pincelar']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['pincelar']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['pincelar']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['pincelar']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['pincelar']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="pincelar_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['pincelar_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_pincelar_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['pincelar']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="pincelar_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('pincelar',<?php echo $veiculo['id']; ?>, false);" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['pincelar_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="pincelar_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['pincelar_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="pincelar_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['pincelar_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('pincelar',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>

		<div class="<?php if($veiculo['outros']==0){echo "yellow";}elseif($veiculo['outros']==1){echo "green";}elseif($veiculo['outros']==2){echo "silver";}elseif($veiculo['outros']==4){echo "blue";}else{echo "red";} ?>" style="z-index:2;">

			<div class="arrow_text" onclick="openPopup(this, 'outros', <?php echo $veiculo['id']; ?>)">

				Outros<?php if($veiculo['outros_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_outros_<?php echo $veiculo['id']; ?>" title="Data final para concluir este serviço" ><?php echo implode("/", array_reverse(explode("-", $veiculo['outros_date_concluido']))); ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 17; display: none; box-shadow: 5px 5px 2px #444; margin-left:-350px;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Outros - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>

					<td width="30%">

					Status<br/>

					<select id="outros_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('outros',<?php echo $veiculo['id']; ?>, false);">

						<option value="">Selecione</option>

						<option <?php echo ($veiculo['outros']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>

						<option <?php echo ($veiculo['outros']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

						<option <?php echo ($veiculo['outros']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>

						<option <?php echo ($veiculo['outros']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>

						<option <?php echo ($veiculo['outros']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>

					</select><br/><br/>

					</td>

					<td width="20%">

						Início<br/>

						<input type="text" id="outros_data_entrada_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['outros_date_entrada']))); ?>" />

					</td>

					<td width="10%">

						Dias<br/>

						<input type="text" id="dias_preparacao_outros_<?php echo $veiculo['id']; ?>" class="data"  value="<?php echo $this->arrPeriodoPreparacao['outros']; ?>">

					</td>

					<td width="17%">

						Dias extras<br/>

						<input type="number" id="outros_dias_extras_<?php echo $veiculo['id']; ?>" style="width:100%" onchange="salvarPreparacaoTodos('outros',<?php echo $veiculo['id']; ?>, false);" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['outros_dias_extras']))); ?>"/>

					</td>

					<td width="20%">

						Fim<br/>

						<input type="text" id="outros_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['outros_date_concluido']))); ?>" />

					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="outros_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['outros_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('outros',<?php echo $veiculo['id']; ?>, true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

	<td>
		<?php
			$dataFinal = implode("/", array_reverse(explode("-", @date("Y-m-d"))));
			$dataFinalPrevista = implode("/", array_reverse(explode("-", $veiculo['outros_date_concluido'])));
			if($veiculo['concluido_date_concluido'] && $veiculo['concluido_date_concluido'] != "0000-00-00"){
				$dataFinal = implode("/", array_reverse(explode("-", $veiculo['concluido_date_concluido'])));
				$dataFinalPrevista = implode("/", array_reverse(explode("-", $veiculo['concluido_date_concluido'])));
			}
		?>

		<div class="<?php if($veiculo['concluido']==0){echo "yellow";}elseif($veiculo['concluido']==1){echo "green";}elseif($veiculo['concluido']==2){echo "silver";}elseif($veiculo['concluido']==4){echo "blue";}else{echo "red";} ?>" style="z-index:1;">

			<div class="arrow_text" onclick="openPopup(this, 'concluido', <?php echo $veiculo['id']; ?>)">

				Lista&nbsp;final<?php if($veiculo['concluido_obs']){echo "<i style='font-weight:bold;'>!</i>";} ?>

				<br/><span class="span_data" id="data_final_concluido_<?php echo $veiculo['id']; ?>" title="Data final para concluir todos os serviços" ><?php echo $dataFinalPrevista; ?></span>

			</div>

		</div>

		<div class="obs_date" style="width:450px; background-color:#fff; z-index: 17; display: none; box-shadow: 5px 5px 2px #444; margin-left:-400px;">

			<table class="popup" style="width:99%; margin-left:10px;">

				<tr>

					<td colspan="5">

						<div style="padding: 10px 0px 10px 0px; font-size:15px; font-weight: bold;">Lista final - <?php echo $veiculo['descricao_site']; ?> - <?php echo $veiculo['placa']; ?></div></td><td><div style="cursor:pointer; margin-right:10px; font-weight: bold;" onclick="closePopup();">X</div>

					</td>

				</tr>

				<tr>
					<td>

						Status<br/>

						<select id="concluido_<?php echo $veiculo['id']; ?>" class="select" onchange="salvarPreparacaoTodos('outros',<?php echo $veiculo['id']; ?>, false);">

							<option value="">Selecione</option>
							<option <?php echo ($veiculo['concluido']==1)?"selected='selected'":"" ?> style="background-color:green; color:#fff;" value="1">Realizado</option>

							<!-- 
							<option <?php echo ($veiculo['concluido']==0)?"selected='selected'":"" ?> style="background-color:#FFD700; color:#fff;" value="0">Agendar</option>
							<option <?php echo ($veiculo['concluido']==3)?"selected='selected'":"" ?> style="background-color:red; color:#fff;" value="3">Em atraso</option>
							<option <?php echo ($veiculo['concluido']==2)?"selected='selected'":"" ?> style="background-color:silver; color:#fff;" value="2">Sem reparos</option>
							<option <?php echo ($veiculo['concluido']==4)?"selected='selected'":"" ?> style="background-color:blue; color:#fff;" value="4">Em manutenção</option>
 							-->
						</select><br/><br/>

					</td>

					<td width="20%">
						Previsão<br/>
						<input type="text" class="data" value="<?php echo implode("/", array_reverse(explode("-", $veiculo['outros_date_concluido']))); ?>" />
					</td>

					<td width="20%">
						Concluido<br/>
						<input type="text" id="concluido_data_concluido_<?php echo $veiculo['id']; ?>" class="data" value="<?php echo $dataFinal; ?>" />
					</td>

				</tr>

				<tr>

					<td colspan="5"> 

						Observações<br/>

						<textarea placeholder="Obs" id="concluido_obs_<?php echo $veiculo['id']; ?>" style="width:100%; height: 100px;"><?php echo $veiculo['concluido_obs']; ?></textarea><br/><br/>

						<input type="button" value="Salvar" onClick="salvarPreparacaoTodos('concluido','<?php echo $veiculo['id']; ?>', true);" /><br/><br/>

					</td>

				</tr>

			</table>

		</div>

	</td>

</tr>

<?php

	}

?>

</table>

<script type="text/javascript">

	var status;
	var dataEntrada;
	var dataConcluido;
	var diasExtras;
	var idGlobal;
	var servicoGlobal;

	function closePopup(){
		$(".obs_date").css("display", "none");
		if(idGlobal){
			$("#"+servicoGlobal+"_"+idGlobal).val(status);
			$("#"+servicoGlobal+"_data_entrada_"+idGlobal).val(dataEntrada);
			$("#"+servicoGlobal+"_data_concluido_"+idGlobal).val(dataConcluido);
			$("#"+servicoGlobal+"_dias_extras_"+idGlobal).val(diasExtras);
		}

		salvarPreparacaoTodos(servicoGlobal, idGlobal, false);
	}


	function openPopup(este, servico, id){
		closePopup();
		idGlobal = id;
		servicoGlobal = servico;
		status = $("#"+servicoGlobal+"_"+idGlobal).val();
		dataEntrada = $("#"+servicoGlobal+"_data_entrada_"+idGlobal).val();
		dataConcluido = $("#"+servicoGlobal+"_data_concluido_"+idGlobal).val();
		diasExtras = $("#"+servicoGlobal+"_dias_extras_"+idGlobal).val();

		$(este).parent().next().css("display", "block");
		$(este).parent().next().css("position", "absolute");
		$(este).parent().next().css("margin-top", "-40px");
	}

	$(document).ready(function(){
		verificaData();
	});

	function verificaData(){

		$("input").each(function(){

			if($(this).attr("id")){

				arrTemp = $(this).attr("id").split("_");

				if(arrTemp[1]+"_"+arrTemp[2] == "data_concluido"){

					var dia = $(this).val().split("/")[0];
					var mes = $(this).val().split("/")[1];
					var ano = $(this).val().split("/")[2];
					var times = new Date(ano, mes, dia).getTime();

					var diaHoje = new Date().getDate();
					var mesHoje = (new Date().getMonth()+1);
					var anoHoje = new Date().getFullYear();
					if(diaHoje < 10){
						diaHoje = "0"+diaHoje;
					}
					if(mesHoje < 10){
						mesHoje = "0"+mesHoje;
					}
					var timesHoje = new Date(anoHoje, mesHoje, diaHoje).getTime();

					arrTempId = $(this).attr("id").split("_");

					if($("#"+arrTempId[0]+"_"+arrTempId[3]).val() != 2 && $("#"+arrTempId[0]+"_"+arrTempId[3]).val() != 1){

						if(timesHoje > times){

							$(this).addClass("vencida");

							$("#data_final_"+arrTempId[0]+"_"+arrTempId[3]).addClass("vencida");

						}else{

							$(this).removeClass("vencida");

							$("#data_final_"+arrTempId[0]+"_"+arrTempId[3]).removeClass("vencida");

						}

					}else{
						if($("#"+arrTempId[0]+"_"+arrTempId[3]).val() != 1){
							$("#data_final_"+arrTempId[0]+"_"+arrTempId[3]).html("Sem reparos");
						}
					}

				}

			}

		});

	}

	function retornaDataFinal(dataInicio, diasPreparacao, diasExtras){

		var timestamp = new Date(dataInicio.split("/")[2], parseInt(dataInicio.split("/")[1]), parseInt(dataInicio.split("/")[0])+parseInt(diasPreparacao)+parseInt(diasExtras));
		var mes = timestamp.getMonth();
		var dia = timestamp.getDate();

		if(dia < 10){
			dia = "0"+dia;
		}
		if(mes < 10){
			mes = "0"+mes;
		}

		var retorno = dia+"/"+mes+"/"+timestamp.getFullYear();

		if(retorno == "NaN/NaN/NaN"){
			return "";
		}else{
			return retorno;
		}


	}

	function salvarPreparacaoTodos(servico, id, salvar){

		var jSon = new Array();
		var idServico = $("#"+servico+"_"+id).val();
		var dataEntrada = $("#"+servico+"_data_entrada_"+id).val();
		var dataConclusao = $("#"+servico+"_data_concluido_"+id).val();
		var diasExtras = $("#"+servico+"_dias_extras_"+id).val();
		var obs = $("#"+servico+"_obs_"+id).val();

		if(idServico == 4){

			if($("#mecanico_"+id).val() == 4 && servico != "mecanico"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#funilaria_"+id).val() == 4 && servico != "funilaria"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#martelinho_"+id).val() == 4 && servico != "martelinho"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#eletrica_"+id).val() == 4 && servico != "eletrica"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#tapecaria_"+id).val() == 4 && servico != "tapecaria"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#lavacar_"+id).val() == 4 && servico != "lavacar"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#volante_"+id).val() == 4 && servico != "volante"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#calotas_"+id).val() == 4 && servico != "calotas"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#pneus_"+id).val() == 4 && servico != "pneus"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#chaveiro_"+id).val() == 4 && servico != "chaveiro"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#pincelar_"+id).val() == 4 && servico != "pincelar"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#outros_"+id).val() == 4 && servico != "outros"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#concluido_"+id).val() == 4 && servico != "concluido"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

		}

		var arrServicos = new Array();
		arrServicos[0] = "mecanico";
		arrServicos[1] = "funilaria";
		arrServicos[2] = "martelinho";
		arrServicos[3] = "eletrica";
		arrServicos[4] = "tapecaria";
		arrServicos[5] = "lavacar";
		arrServicos[6] = "volante";
		arrServicos[7] = "calotas";
		arrServicos[8] = "pneus";
		arrServicos[9] = "chaveiro";
		arrServicos[10] = "pincelar";
		arrServicos[11] = "outros";
		arrServicos[12] = "concluido";

		var edita = false;

		if($("#data_inicio_preparacao_"+id).val() != "" && $("#data_inicio_preparacao_"+id).val() != "0000-00-00"){

			for (var i = 0; i < arrServicos.length; i++) {

				if(arrServicos[i] == servico){

					edita = true;

				}

				if(edita == true){

					if($("#"+arrServicos[i]+"_"+id).val() == 2){

						$("#"+arrServicos[i]+"_data_concluido_"+id).val(retornaDataFinal($("#"+arrServicos[i]+"_data_entrada_"+id).val(), 0, 0));

						$("#data_final_"+arrServicos[i]+"_"+id).html("Sem reparos");

						$("#"+arrServicos[i+1]+"_data_entrada_"+id).val(retornaDataFinal($("#"+arrServicos[i]+"_data_entrada_"+id).val(), 0, 0));

					}else{

						if(arrServicos[i] == "concluido"){
							//$("#concluido_data_concluido_"+id).val($("#data_final_"+arrServicos[i-1]+"_"+id).html());
							$("#data_final_concluido_"+id).html($("#data_final_"+arrServicos[i-1]+"_"+id).html());
						}else{

							$("#"+arrServicos[i]+"_data_concluido_"+id).val(retornaDataFinal($("#"+arrServicos[i]+"_data_entrada_"+id).val(), $("#dias_preparacao_"+arrServicos[i]+"_"+id).val(), $("#"+arrServicos[i]+"_dias_extras_"+id).val()));
							$("#data_final_"+arrServicos[i]+"_"+id).html(retornaDataFinal($("#"+arrServicos[i]+"_data_entrada_"+id).val(), $("#dias_preparacao_"+arrServicos[i]+"_"+id).val(), $("#"+arrServicos[i]+"_dias_extras_"+id).val()));
							$("#"+arrServicos[i+1]+"_data_entrada_"+id).val(retornaDataFinal($("#"+arrServicos[i]+"_data_entrada_"+id).val(), $("#dias_preparacao_"+arrServicos[i]+"_"+id).val(), $("#"+arrServicos[i]+"_dias_extras_"+id).val()));

						}

					}

					jSon[jSon.length] = {
						id_veiculo:id,
						id_servico:$("#"+arrServicos[i]+"_"+id).val(),
						dataEntrada:$("#"+arrServicos[i]+"_data_entrada_"+id).val(),
						dataConclusao:$("#"+arrServicos[i]+"_data_concluido_"+id).val(),
						obs:$("#"+arrServicos[i]+"_obs_"+id).val(),
						servico_nome:arrServicos[i],
						dias_extras:$("#"+arrServicos[i]+"_dias_extras_"+id).val()
					};

				}

			}

			if(salvar){

				$.ajax({
					type: "POST",
					url:"/veiculos/nova-preparacao",
					dataType:"TEXT",
					data:{'data':jSon},               
					success:function(retorno){
						location.reload();
					}
				});

			}

			verificaData();

		}
	}

	/*function salvarPreparacao(servico, id){

		

		if(servico == "concluido" && ($("#concluido_data_concluido_"+id).val() == "" || $("#concluido_data_concluido_"+id).val() == "00/00/0000")){

			alert("O campo Data deve ser preenchido");

			return false;

		}



		var idServico = $("#"+servico+"_"+id).val();

		var dataEntrada = $("#"+servico+"_data_entrada_"+id).val();

		var dataConclusao = $("#"+servico+"_data_concluido_"+id).val();

		var obs = $("#"+servico+"_obs_"+id).val();

		

		if(idServico == 4){

			if($("#mecanico_"+id).val() == 4 && servico != "mecanico"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#funilaria_"+id).val() == 4 && servico != "funilaria"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#martelinho_"+id).val() == 4 && servico != "martelinho"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#eletrica_"+id).val() == 4 && servico != "eletrica"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#tapecaria_"+id).val() == 4 && servico != "tapecaria"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#lavacar_"+id).val() == 4 && servico != "lavacar"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#volante_"+id).val() == 4 && servico != "volante"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#calotas_"+id).val() == 4 && servico != "calotas"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#pneus_"+id).val() == 4 && servico != "pneus"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#chaveiro_"+id).val() == 4 && servico != "chaveiro"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#pincelar_"+id).val() == 4 && servico != "pincelar"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#outros_"+id).val() == 4 && servico != "outros"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

			if($("#concluido_"+id).val() == 4 && servico != "concluido"){

				alert("Só é possível uma etapa em manutenção!");

				return false;

			}

		}



		$(".obs_date").css("display", "none");



		$.ajax({

			type: "POST",

			url:"/veiculos/ajax",

			dataType:"html",

			data:{fn:'preparacao', id_veiculo:id, id_servico:idServico, dataEntrada:dataEntrada, dataConclusao:dataConclusao, obs:obs, servico_nome:servico},                       

			success:function(retorno){

				location.reload();

			}

		});



	}

	*/



	$(".arrow_text").click(function(e){

		

	});



	/*$(function(){

		$('.data').mask("99/99/9999");

		

		<?php

		foreach($this->arrVeiculos as $veiculo){

		?>

		

		$('#mecanico_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#mecanico_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#funilaria_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#funilaria_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#martelinho_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#martelinho_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#eletrica_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#eletrica_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#tapecaria_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#tapecaria_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#lavacar_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#lavacar_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#volante_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#volante_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#calotas_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#calotas_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#pneus_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#pneus_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#chaveiro_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#chaveiro_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#pincelar_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#pincelar_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#outros_data_entrada_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#outros_data_entrada_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#concluido_data_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#concluido_data_<?php echo $veiculo['id']; ?>'

			});

		});

		

		

		

		$('#mecanico_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#mecanico_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#funilaria_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#funilaria_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#martelinho_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#martelinho_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#eletrica_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#eletrica_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#tapecaria_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#tapecaria_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#lavacar_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#lavacar_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#volante_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#volante_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#calotas_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#calotas_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#pneus_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#pneus_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#chaveiro_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#chaveiro_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#pincelar_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#pincelar_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#outros_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#outros_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});

		

		$('#concluido_data_concluido_<?php echo $veiculo['id']; ?>').focus(function(){

			$(this).calendario({

				target:'#concluido_data_concluido_<?php echo $veiculo['id']; ?>'

			});

		});



		<?php

		}

		?>



	});*/



</script>