<form id="simulador" name="simulador" enctype="application/x-www-form-urlencoded" action="configura-simulador" class="form" method="post">
<table class="table">
	<tr>
		<th>12 Meses</th><th>24 Meses</th><th>36 Meses</th><th>48 Meses</th><th>60 Meses</th><th>Per&iacute;odo</th>
	</tr>
	
	<?php 
		foreach($this->dados as $dados){
		
			if($dados['antes_depois'] == 1){
			
				$periodo = "Depois de ".(@date("Y")-7);
				
			}else{
			
				$periodo = "Antes de ".(@date("Y")-7);
			
			}
		
			echo "<tr>
					<td><input type='text' name='meses_12-".$dados['id']."' id='meses_12-".$dados['id']."' value='".$dados['meses_12']."'/></td>
					<td><input type='text' name='meses_24-".$dados['id']."' id='meses_24-".$dados['id']."' value='".$dados['meses_24']."'/></td>
					<td><input type='text' name='meses_36-".$dados['id']."' id='meses_36-".$dados['id']."' value='".$dados['meses_36']."'/></td>
					<td><input type='text' name='meses_48-".$dados['id']."' id='meses_48-".$dados['id']."' value='".$dados['meses_48']."'/></td>
					<td><input type='text' name='meses_60-".$dados['id']."' id='meses_60-".$dados['id']."' value='".$dados['meses_60']."'/></td>
					<td>".$periodo."</td>
				  </tr>";
		
		}
	?>
		
</table>

		<div class="inline" style="clear:both">
			<input type="button" id="button" name="button" class="btn-small btn-add" value="Salvar" onclick="validaCampo('')"/>
		</div>
	
<form>

<div class="msg" id="msg" name="msg"><?php echo $this->mensagem;?></div>

<script type="text/javascript">

function validaCampo(){
	
	var msg = "";
	var erro = false;
	
	if($("#meses_12-1").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_24-1").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_36-1").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_48-1").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_60-1").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_12-2").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_24-2").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_36-2").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_48-2").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}
	
	if($("#meses_60-2").val() == ""){
		
		erro = true;
		
		msg = "Todos os campos devem ser preenchidos.";
	
	}

	if(erro){
		
		//msg = msg.substr(4);
		$("#msg").removeClass('sucess');
		$("#msg").addClass('erro');
		$("#msg").html(msg);
	
	}else{
		
		$("form").submit();
	
	}

}

$(function(){
	
	if($("#msg").html().length > 0){
			
		if($("#msg").attr("class") == "msg" && $("#msg").html().substr(0 ,4) != "Erro"){
		
			$("#msg").addClass('sucess');
		
		}else{
		
			$("#msg").addClass('erro');
		
		}
	
	}

})

</script>